### ISSUE TITLE
PubSub running performance tests

### ISSUE THREAD

**Issue by johnsimons** [Particular/NServiceBus#1919]
I get the following exception when running PubSub.ps1:
```
Unhandled Exception: Raven.Client.Exceptions.NonAuthoritativeInformationException: Document Subscriptions/bba8ece5-a307-
c852-7de5-4d5c5e80a1ef returned Non Authoritative Information (probably modified by a transaction in progress) and Allow
NonAuthoritativeInformation  is set to false
   at Raven.Client.Document.InMemoryDocumentSessionOperations.TrackEntity[T](JsonDocument documentFound) in c:\Builds\Ra
venDB-Stable\Raven.Client.Lightweight\Document\InMemoryDocumentSessionOperations.cs:line 335
   at Raven.Client.Document.SessionOperations.MultiLoadOperation.<Complete>b__4[T](JsonDocument document) in c:\Builds\R
avenDB-Stable\Raven.Client.Lightweight\Document\SessionOperations\MultiLoadOperation.cs:line 71
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Raven.Client.Document.SessionOperations.MultiLoadOperation.Complete[T]() in c:\Builds\RavenDB-Stable\Raven.Client.
Lightweight\Document\SessionOperations\MultiLoadOperation.cs:line 70
   at Raven.Client.Document.DocumentSession.LoadInternal[T](String[] ids) in c:\Builds\RavenDB-Stable\Raven.Client.Light
weight\Document\DocumentSession.cs:line 347
   at NServiceBus.Persistence.Raven.SubscriptionStorage.RavenSubscriptionStorage.GetSubscriptions(IEnumerable`1 messageT
ypes, IDocumentSession session) in c:\Projects\NServiceBus\src\NServiceBus.Core\Persistence\Raven\SubscriptionStorage\Ra
venSubscriptionStorage.cs:line 87
   at NServiceBus.Persistence.Raven.SubscriptionStorage.RavenSubscriptionStorage.NServiceBus.Unicast.Subscriptions.Messa
geDrivenSubscriptions.ISubscriptionStorage.Subscribe(Address client, IEnumerable`1 messageTypes) in c:\Projects\NService
Bus\src\NServiceBus.Core\Persistence\Raven\SubscriptionStorage\RavenSubscriptionStorage.cs:line 30
   at PubSubTestCase.Run() in c:\Projects\NServiceBus\src\NServiceBus.PerformanceTests\PubSub\PubSubTestCase.cs:line 101

   at Runner.Program.Main(String[] args) in c:\Projects\NServiceBus\src\NServiceBus.PerformanceTests\Program.cs:line 32
PS C:\Projects\NServiceBus\src\NServiceBus.PerformanceTests\TestSuites> .\PubSub.ps1
```

**Comment by bbrandt** [comment]
I'm unable to find ..\.\bin\release\Runner.exe that is required to run PubSub.ps1.

Didn't see any instructions for setup of the required SQLServer DB as well:
Sqlcmd: Error: Microsoft SQL Server Native Client 11.0 : SQL Server Network Interfaces: Error Locating Server/Instance S
pecified [xFFFFFFFF]. .
Sqlcmd: Error: Microsoft SQL Server Native Client 11.0 : Login timeout expired.
Sqlcmd: Error: Microsoft SQL Server Native Client 11.0 : A network-related or instance-specific error has occurred while
 establishing a connection to SQL Server. Server is not found or not accessible. Check if instance name is correct and i
f SQL Server is configured to allow remote connections. For more information see SQL Server Books Online..

**Comment by johnsimons** [comment]
@bbrandt did u compile the project in Release mode ?

**Comment by bbrandt** [comment]
I am now running in Release mode.  Running VS2013 as Administrator.

I'm trying to run NServiceBus.PerformanceTests.exe directly with these parameters:
PubSub numberofsubscribers=10 numberofmessages=10000 numberofthreads=10 storage=msmq

I get an ArgumentNullException from queue.SetPermissions() in [MsmqQueueCreator.cs](https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/Transports/Msmq/MsmqQueueCreator.cs#L115).  Looks like its passed in as null in [PubSubTestCase.cs](https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.PerformanceTests/PubSub/PubSubTestCase.cs#L107)

Here's the full msg:
```
2015-04-17 12:18:24.054 ERROR NServiceBus.Transports.Msmq.MsmqQueueCreator Could
 not create queue PubSubPerformanceTest.Subscriber0@FC2026 or check its existenc
e. Processing will still continue.
System.ArgumentNullException: Value cannot be null.
Parameter name: user
   at System.Messaging.MessageQueue.SetPermissions(String user, MessageQueueAcce
ssRights rights, AccessControlEntryType entryType)
   at NServiceBus.Transports.Msmq.MsmqQueueCreator.SetPermissionsForQueue(Messag
eQueue queue, String account) in c:\src\NServiceBus\src\NServiceBus.Core\Transpo
rts\Msmq\MsmqQueueCreator.cs:line 110
   at NServiceBus.Transports.Msmq.MsmqQueueCreator.SetPermissionsForQueue(String
 queuePath, String account) in c:\src\NServiceBus\src\NServiceBus.Core\Transport
s\Msmq\MsmqQueueCreator.cs:line 96
   at NServiceBus.Transports.Msmq.MsmqQueueCreator.CreateQueueIfNecessary(Addres
s address, String account) in c:\src\NServiceBus\src\NServiceBus.Core\Transports
\Msmq\MsmqQueueCreator.cs:line 51
```

Tried changing the null parameter to my own windows user account.  Got past that and got be errors below.  I don't have anymore time to spare at the moment so I'm giving up for now.


```
2015-04-17 12:30:15.829 WARN  NServiceBus.Timeout.Hosting.Windows.TimeoutPersist
erReceiver Failed to fetch timeouts from the timeout storage
System.NullReferenceException: Object reference not set to an instance of an obj
ect.
   at NServiceBus.Timeout.Hosting.Windows.TimeoutPersisterReceiver.Poll(Object o
bj) in c:\src\NServiceBus\src\NServiceBus.Core\Timeout\Hosting\Windows\TimeoutPe
rsisterReceiver.cs:line 88
   at System.Threading.Tasks.Task.Execute()
2015-04-17 12:30:15.835 INFO  NServiceBus.CircuitBreakers.RepeatedFailuresOverTi
meCircuitBreaker The circuit breaker for TimeoutStorageConnectivity is now in th
e armed state
2015-04-17 12:30:19.027 WARN  NServiceBus.CircuitBreakers.RepeatedFailuresOverTi
meCircuitBreaker The circuit breaker for TimeoutStorageConnectivity will now be
triggered
2015-04-17 12:30:19.079 ERROR NServiceBus Repeated failures when fetching timeou
ts from storage, endpoint will be terminated.
System.NullReferenceException: Object reference not set to an instance of an obj
ect.
   at NServiceBus.Timeout.Hosting.Windows.TimeoutPersisterReceiver.Poll(Object o
bj) in c:\src\NServiceBus\src\NServiceBus.Core\Timeout\Hosting\Windows\TimeoutPe
rsisterReceiver.cs:line 88
   at System.Threading.Tasks.Task.Execute()
2015-04-17 12:30:19.090 WARN  NServiceBus.Timeout.Hosting.Windows.TimeoutPersist
erReceiver Failed to fetch timeouts from the timeout storage
System.NullReferenceException: Object reference not set to an instance of an obj
ect.
   at NServiceBus.Timeout.Hosting.Windows.TimeoutPersisterReceiver.Poll(Object o
bj) in c:\src\NServiceBus\src\NServiceBus.Core\Timeout\Hosting\Windows\TimeoutPe
rsisterReceiver.cs:line 88
   at System.Threading.Tasks.Task.Execute()
```

**Comment by danielmarbach** [comment]
PerformanceTests are no longer a part of NServiceBus. They have been moved to https://github.com/Particular/ProductionTests and tuned to enable more scenarios in the future. I'm closing this issue.

**Comment by bbrandt** [comment]
I can't seem to see https://github.com/Particular/ProductionTests.  Is it a private repo?  If so, is it planned to be released to the public?

**Comment by danielmarbach** [comment]
@bbrandt @SimonCropp is looking into this and will make it public
