### ISSUE TITLE
InvalidOperationException under heavy load with StructureMap and Unity containers

### ISSUE THREAD

**Issue by jdrat2000** [Particular/NServiceBus#2037]
We've had a couple of reports of exceptions under heavy load.  One when using StructureMap, the other when using Unity.  They are slightly diffrent but per @johnsimons  request, I am combining them into a single issue.
### StructureMap Issue

(case 4525)
We have a very high volume service handling events raised by a central
publisher. Several hundred times a day the below error is raised. This
just started happening a few days ago. We are running version 3.2.8 and
are currently in the process of updating to the latest.

```
System.InvalidOperationException: Collection was modified; enumeration
operation may not execute.
at System.Collections.Generic.Dictionary`2.Enumerator.MoveNext()
at StructureMap.StringExtensions.Each[T](IEnumerable`1 enumerable,
Action`1 action) in c:\code\structuremap\Source\StructureMap\Extensions.cs:line
10
at StructureMap.InstanceFactory.Clone() in c:\code\structuremap\Source\
StructureMap\InstanceFactory.cs:line 137
at StructureMap.PipelineGraph.ToNestedGraph() in
c:\code\structuremap\Source\StructureMap\PipelineGraph.cs:line 102
at StructureMap.Container.GetNestedContainer() in
c:\code\structuremap\Source\StructureMap\Container.cs:line 441
at NServiceBus.ObjectBuilder.StructureMap.StructureMapObjectBuilder.
BuildChildContainer()
at NServiceBus.ObjectBuilder.Common.CommonObjectBuilder.
NServiceBus.ObjectBuilder.IBuilder.CreateChildBuilder()
at NServiceBus.Unicast.UnicastBus.TransportMessageReceived(Object
sender, TransportMessageReceivedEventArgs e)
at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
at NServiceBus.Unicast.Transport.Transactional.TransactionalTransport.
OnTransportMessageReceived(TransportMessage msg)
```
### Unity Issue

 (case 4135)
It seems there's an issues when using a Unity 2.x container and starting
satellites. We use a lot of injection in our handlers and in our production
environment we see that the parallel tasks for starting satellites poses an
issue on startup. In special the second level retry processor satellite.
The results in the second level retry processor not starting correctly and
not handling its queue.

Any ideas on how to solve this?

Helpful information to include
Product name: NServiceBus
Version: 4.0.4
Stacktrace:

```
2014-02-25 16:25:25,726 [21] DEBUG NServiceBus.Satellites.SatelliteLauncher
[(null)] - Starting 1/3
'NServiceBus.SecondLevelRetries.SecondLevelRetriesProcessor,
NServiceBus.Core, Version=4.0.0.0, Culture=neutral,
PublicKeyToken=9fc386479f8a226c' satellite
2014-02-25 16:25:25,726 [22] DEBUG NServiceBus.Unicast.UnicastBus [(null)]
- Started
NServiceBus.Unicast.Subscriptions.MessageDrivenSubscriptions.StorageInitializer,
NServiceBus.Core, Version=4.0.0.0, Culture=neutral,
PublicKeyToken=9fc386479f8a226c.
2014-02-25 16:25:25,742 [8] DEBUG
Pms.Framework.Unity.UnityServiceHostFactory [(null)] - Creating service
host for server AdminService with Uri's
http://----.com/services/application/AdminService.svc,
2014-02-25 16:25:25,742 [21] ERROR NServiceBus.Unicast.UnicastBus [(null)]
- System.AggregateException: One or more errors occurred. --->
Microsoft.Practices.Unity.ResolutionFailedException: Resolution of the
dependency failed, type =
"NServiceBus.Unicast.Transport.TransportReceiver", name = "(none)".
Exception occurred while: while resolving.
Exception is: InvalidOperationException - Collection was modified;
enumeration operation may not execute.
-----------------------------------------------
At the time of the exception, the container was:

Resolving NServiceBus.Unicast.Transport.TransportReceiver,(none)
---> System.InvalidOperationException: Collection was modified;
enumeration operation may not execute.
at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource
resource)
at
System.Collections.Generic.Dictionary`2.KeyCollection.Enumerator.MoveNext()
at
Microsoft.Practices.Unity.UnityContainer.FillTypeRegistrationDictionary(IDictionary`2
typeRegistrations)
at Microsoft.Practices.Unity.UnityContainer.get_Registrations()
at
Microsoft.Practices.Unity.UnityContainerExtensions.IsRegistered(IUnityContainer
container, Type typeToCheck, String nameToCheck)
at
Microsoft.Practices.Unity.UnityContainerExtensions.IsRegistered(IUnityContainer
container, Type typeToCheck)
at
NServiceBus.ObjectBuilder.Unity.PropertyInjectionBuilderStrategy.PreBuildUp(IBuilderContext
context)
at
Microsoft.Practices.ObjectBuilder2.StrategyChain.ExecuteBuildUp(IBuilderContext
context)
at Microsoft.Practices.Unity.UnityContainer.DoBuildUp(Type t, Object
existing, String name, IEnumerable`1 resolverOverrides)
--- End of inner exception stack trace ---
at Microsoft.Practices.Unity.UnityContainer.DoBuildUp(Type t, Object
existing, String name, IEnumerable`1 resolverOverrides)
at Microsoft.Practices.Unity.UnityContainer.Resolve(Type t, String name,
ResolverOverride[] resolverOverrides)
at
Microsoft.Practices.Unity.UnityContainerExtensions.Resolve(IUnityContainer
container, Type t, ResolverOverride[] overrides)
at NServiceBus.ObjectBuilder.Unity.UnityObjectBuilder.Build(Type
typeToBuild)
at
NServiceBus.ObjectBuilder.Common.CommonObjectBuilder.NServiceBus.ObjectBuilder.IBuilder.Build[T]()
at
NServiceBus.Satellites.SatelliteLauncher.<>c__DisplayClass4.<Start>b__2(Int32
index)
at System.Threading.Tasks.Parallel.<>c__DisplayClassf`1.<ForWorker>b__c()
at System.Threading.Tasks.Task.InnerInvoke()
at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
at
System.Threading.Tasks.Task.<>c__DisplayClass11.<ExecuteSelfReplicating>b__10(Object
param0)
--- End of inner exception stack trace ---
at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean
includeTaskCanceledExceptions)
at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout,
CancellationToken cancellationToken)
at System.Threading.Tasks.Task.Wait()
at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32
fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1
body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit,
Action`1 localFinally)
at System.Threading.Tasks.Parallel.For(Int32 fromInclusive, Int32
toExclusive, Action`1 body)
at NServiceBus.Satellites.SatelliteLauncher.Start()
at NServiceBus.Unicast.UnicastBus.<>c__DisplayClass18.<Start>b__16()
---> (Inner Exception #0)
Microsoft.Practices.Unity.ResolutionFailedException: Resolution of the
dependency failed, type =
"NServiceBus.Unicast.Transport.TransportReceiver", name = "(none)".
Exception occurred while: while resolving.
Exception is: InvalidOperationException - Collection was modified;
enumeration operation may not execute.
-----------------------------------------------
At the time of the exception, the container was:

Resolving NServiceBus.Unicast.Transport.TransportReceiver,(none)
---> System.InvalidOperationException: Collection was modified;
enumeration operation may not execute.
at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource
resource)
at
System.Collections.Generic.Dictionary`2.KeyCollection.Enumerator.MoveNext()
at
Microsoft.Practices.Unity.UnityContainer.FillTypeRegistrationDictionary(IDictionary`2
typeRegistrations)
at Microsoft.Practices.Unity.UnityContainer.get_Registrations()
at
Microsoft.Practices.Unity.UnityContainerExtensions.IsRegistered(IUnityContainer
container, Type typeToCheck, String nameToCheck)
at
Microsoft.Practices.Unity.UnityContainerExtensions.IsRegistered(IUnityContainer
container, Type typeToCheck)
at
NServiceBus.ObjectBuilder.Unity.PropertyInjectionBuilderStrategy.PreBuildUp(IBuilderContext
context)
at
Microsoft.Practices.ObjectBuilder2.StrategyChain.ExecuteBuildUp(IBuilderContext
context)
at Microsoft.Practices.Unity.UnityContainer.DoBuildUp(Type t, Object
existing, String name, IEnumerable`1 resolverOverrides)
--- End of inner exception stack trace ---
at Microsoft.Practices.Unity.UnityContainer.DoBuildUp(Type t, Object
existing, String name, IEnumerable`1 resolverOverrides)
at Microsoft.Practices.Unity.UnityContainer.Resolve(Type t, String name,
ResolverOverride[] resolverOverrides)
at
Microsoft.Practices.Unity.UnityContainerExtensions.Resolve(IUnityContainer
container, Type t, ResolverOverride[] overrides)
at NServiceBus.ObjectBuilder.Unity.UnityObjectBuilder.Build(Type
typeToBuild)
at
NServiceBus.ObjectBuilder.Common.CommonObjectBuilder.NServiceBus.ObjectBuilder.IBuilder.Build[T]()
at
NServiceBus.Satellites.SatelliteLauncher.<>c__DisplayClass4.<Start>b__2(Int32
index)
at System.Threading.Tasks.Parallel.<>c__DisplayClassf`1.<ForWorker>b__c()
at System.Threading.Tasks.Task.InnerInvoke()
at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
at
System.Threading.Tasks.Task.<>c__DisplayClass11.<ExecuteSelfReplicating>b__10(Object
param0)<---
could not be started.
```

**Comment by dario-l** [comment]
Unfortunately, I have similar issue with version 3.1.4.143.

StackTrace:
```
2015-03-27 18:50:33.2998 Error Cssb.Infrastructure.Mvc.ErrorHelper 101 System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.Collections.Generic.Dictionary`2.ValueCollection.Enumerator.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at StructureMap.Graph.CloseGenericFamilyPolicy.Build(Type type) in c:\BuildAgent\work\996e173a8ceccdca\src\StructureMap\Graph\CloseGenericFamilyPolicy.cs:line 27
   at StructureMap.Graph.PluginGraph.<>c__DisplayClass11.<HasFamily>b__f(IFamilyPolicy x) in c:\BuildAgent\work\996e173a8ceccdca\src\StructureMap\Graph\PluginGraph.cs:line 208
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at StructureMap.Graph.PluginGraph.HasFamily(Type pluginType) in c:\BuildAgent\work\996e173a8ceccdca\src\StructureMap\Graph\PluginGraph.cs:line 208
   at StructureMap.Graph.PluginGraph.HasDefaultForPluginType(Type pluginType) in c:\BuildAgent\work\996e173a8ceccdca\src\StructureMap\Graph\PluginGraph.cs:line 224
   at StructureMap.Container.TryGetInstance(Type pluginType) in c:\BuildAgent\work\996e173a8ceccdca\src\StructureMap\Container.cs:line 272
   at Softio.Web.Mvc.Validation.FluentValidatorFactory.CreateInstance(Type validatorType) in c:\Projects\Cssb\trunk\src\Softio\Softio.Web\Mvc\Validation\FluentValidatorFactory.cs:line 11
   at FluentValidation.Mvc.FluentValidationModelValidatorProvider.GetValidators(ModelMetadata metadata, ControllerContext context) in c:\Projects\FluentValidation\src\FluentValidation.Mvc4\FluentValidationModelValidatorProvider.cs:line 75
   at System.Web.Mvc.ModelValidatorProviderCollection.<GetValidators>d__0.MoveNext()
   at System.Web.Mvc.ModelValidator.CompositeModelValidator.<Validate>d__1.MoveNext()
   at System.Web.Mvc.DefaultModelBinder.OnModelUpdated(ControllerContext controllerContext, ModelBindingContext bindingContext)
   at System.Web.Mvc.DefaultModelBinder.BindComplexModel(ControllerContext controllerContext, ModelBindingContext bindingContext)
   at System.Web.Mvc.ControllerActionInvoker.GetParameterValue(ControllerContext controllerContext, ParameterDescriptor parameterDescriptor)
   at System.Web.Mvc.ControllerActionInvoker.GetParameterValues(ControllerContext controllerContext, ActionDescriptor actionDescriptor)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<BeginInvokeAction>b__19(AsyncCallback asyncCallback, Object asyncState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResultBase`1.Begin(AsyncCallback callback, Object state, Int32 timeout)
   at System.Web.Mvc.Async.AsyncResultWrapper.Begin[TResult](AsyncCallback callback, Object state, BeginInvokeDelegate beginDelegate, EndInvokeDelegate`1 endDelegate, Object tag, Int32 timeout)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.BeginInvokeAction(ControllerContext controllerContext, String actionName, AsyncCallback callback, Object state)
   at System.Web.Mvc.Controller.<BeginExecuteCore>b__1c(AsyncCallback asyncCallback, Object asyncState, ExecuteCoreState innerState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallBeginDelegate(AsyncCallback callback, Object callbackState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResultBase`1.Begin(AsyncCallback callback, Object state, Int32 timeout)
   at System.Web.Mvc.Async.AsyncResultWrapper.Begin[TState](AsyncCallback callback, Object callbackState, BeginInvokeDelegate`1 beginDelegate, EndInvokeVoidDelegate`1 endDelegate, TState invokeState, Object tag, Int32 timeout, SynchronizationContext callbackSyncContext)
   at System.Web.Mvc.Controller.BeginExecuteCore(AsyncCallback callback, Object state)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResultBase`1.Begin(AsyncCallback callback, Object state, Int32 timeout)
   at System.Web.Mvc.Async.AsyncResultWrapper.Begin[TState](AsyncCallback callback, Object callbackState, BeginInvokeDelegate`1 beginDelegate, EndInvokeVoidDelegate`1 endDelegate, TState invokeState, Object tag, Int32 timeout, SynchronizationContext callbackSyncContext)
   at System.Web.Mvc.Controller.BeginExecute(RequestContext requestContext, AsyncCallback callback, Object state)
   at System.Web.Mvc.MvcHandler.<BeginProcessRequest>b__4(AsyncCallback asyncCallback, Object asyncState, ProcessRequestState innerState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallBeginDelegate(AsyncCallback callback, Object callbackState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResultBase`1.Begin(AsyncCallback callback, Object state, Int32 timeout)
   at System.Web.Mvc.Async.AsyncResultWrapper.Begin[TState](AsyncCallback callback, Object callbackState, BeginInvokeDelegate`1 beginDelegate, EndInvokeVoidDelegate`1 endDelegate, TState invokeState, Object tag, Int32 timeout, SynchronizationContext callbackSyncContext)
   at System.Web.Mvc.MvcHandler.BeginProcessRequest(HttpContextBase httpContext, AsyncCallback callback, Object state)
   at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)
```
