### ISSUE TITLE
ActivationException on Assemblies to Scan Selection

### ISSUE THREAD

**Issue by billism1** [Particular/NServiceBus#2053]
When starting NServiceBus (4.4.2), during the process of selecting assemblies to scan, an unhandled exception can be thrown if an assembly exists in the current directory (or sub-directory of the current directory) that has a name/namespace that System.Reflection.Assembly.Load cannot handle.

This issue occurred as follows: On one of our development servers running an NServiceBus endpoint, we have ServiceControl (1.0.0-Beta7.15), which uses NServiceBus.Host.exe version 4.4.2 and uses embedded RavenDB. This morning the machine stopped unexpectedly. When the machine came back up, the ServiceControl service failed to start, with the following stack trace dump:

```
Unhandled Exception: Microsoft.Practices.ServiceLocation.ActivationException: Activation error occured while trying to get instance of type WindowsHost, key "Particular.ServiceControl.EndpointConfig, ServiceControl, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null" ---> System.IO.FileNotFoundException: Could not load file or assembly '1318669970.6%2bKPg23SbWD0MPCu3zZmiw%3d%3d.nodebug, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark&stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, Evidence assemblySecurity, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean forIntrospection)
   at System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, Evidence assemblySecurity, StackCrawlMark& stackMark, Boolean forIntrospection)
   at System.Reflection.Assembly.Load(String assemblyString)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at NServiceBus.Hosting.GenericHost..ctor(IConfigureThisEndpoint specifier, String[] args, List`1 defaultProfiles, String endpointName, IEnumerable`1 scannableAssembliesFullName) in c:\BuildAgent\work\31f8c64a6e8a2d7c\src\NServiceBus.Core\Hosting\GenericHost.cs:line 49
   at NServiceBus.Hosting.Windows.WindowsHost..ctor(Type endpointType, String[]args, String endpointName, Boolean runOtherInstallers, IEnumerable`1 scannableAssembliesFullName) in c:\BuildAgent\work\31f8c64a6e8a2d7c\src\NServiceBus.Hosting.Windows\WindowsHost.cs:line 26
   at NServiceBus.Hosting.Windows.HostServiceLocator.DoGetInstance(Type serviceType, String key) in c:\BuildAgent\work\31f8c64a6e8a2d7c\src\NServiceBus.Hosting.Windows\HostServiceLocator.cs:line 31
   at Microsoft.Practices.ServiceLocation.ServiceLocatorImplBase.GetInstance(Type serviceType, String key) in c:\Home\Chris\Projects\CommonServiceLocator\main\Microsoft.Practices.ServiceLocation\ServiceLocatorImplBase.cs:line 49
   --- End of inner exception stack trace ---
   at Microsoft.Practices.ServiceLocation.ServiceLocatorImplBase.GetInstance(Type serviceType, String key) in c:\Home\Chris\Projects\CommonServiceLocator\main\Microsoft.Practices.ServiceLocation\ServiceLocatorImplBase.cs:line 57
   at Microsoft.Practices.ServiceLocation.ServiceLocatorImplBase.GetInstance[TService](String key) in c:\Home\Chris\Projects\CommonServiceLocator\main\Microsoft.Practices.ServiceLocation\ServiceLocatorImplBase.cs:line 103
   at Topshelf.Internal.ServiceController`1.BuildInstance() in c:\Projects\TopShelfForNSB\src\Topshelf\Internal\ServiceController.cs:line 93
   at Magnum.StateMachine.EventActionList`1.Execute(T stateMachine, Event event, Object parameter) in :line 0   at NServiceBus.Hosting.Windows.Program.Main(String[] args) in c:\BuildAgent\work\31f8c64a6e8a2d7c\src\NServiceBus.Hosting.Windows\Program.cs:line 150
```

Apparently, in between the normal running of the service and the unexpected restart, the following 2 files were created by the embedded RavenDB runtime:

```
C:\Program Files (x86)\Particular Software\ServiceControl\Raven\CompiledIndexCache\1318669970.6%2bKPg23SbWD0MPCu3zZmiw%3d%3d.nodebug.dll
and
C:\Program Files (x86)\Particular Software\ServiceControl\Raven\CompiledIndexCache\1318669970.6%2bKPg23SbWD0MPCu3zZmiw%3d%3d.nodebug.dll.cs
```

The above DLL assembly is what is causing the unhandled exception.

**Comment by manishkumar1689** [comment]
Check your connectionstring for database connection
