### ISSUE TITLE
Provide a better warning when message mappings are defined and the message conventions haven't been resolved

### ISSUE THREAD

**Issue by indualagarsamy** [Particular/NServiceBus#2388]
**Steps to repro**
1. Have an POCO message library
2. Reference this POCO message library in a NSB Server endpoint. 
3. Add message mappings that uses this POCO library
4. Do not have message conventions defined. Note that the endpoint starts up without any errors or warning. 
This is misleading. A warning or an error will be more useful to the user to correct this misconfiguration.

**Comment by dbelcham** [comment]
@Particular/nservicebus-maintainers is this still relevant in the v6 world?

**Comment by timbussmann** [comment]
We have warnings about violating best practices when sending/publishing messages which don't conform to the specific command/event interfaces or conventions. I think this essentially covers the mappings scenario (at runtime though)?

I think there is nothing actually verifying that a type handled by a message handler is a valid message type?

**Comment by andreasohlund** [comment]
In v7 configuring a message route using `.Routing().RouteToEndpoint(typeof(TheMessage),"Endpoint2");` will throw the following at startup:

```
System.Exception
  HResult=0x80131500
  Message=Cannot configure routing for type 'TheMessage' because it is not considered a message. Message types have to either implement NServiceBus.IMessage interface or match a defined message convention.
  Source=NServiceBus.Core
  StackTrace:
   at NServiceBus.TypeRouteSource.<GenerateRoutes>d__3.MoveNext()
   at NServiceBus.Features.ConfiguredUnicastRoutes.Apply(UnicastRoutingTable unicastRoutingTable, Conventions conventions)
   at NServiceBus.RoutingComponent.Initialize(ReadOnlySettings settings, Func`2 toTransportAddress, PipelineSettings pipelineSettings, ReceiveConfiguration receiveConfiguration)
   at NServiceBus.InitializableEndpoint.InitializeRouting(TransportInfrastructure transportInfrastructure, ReceiveConfiguration receiveConfiguration)
   at NServiceBus.InitializableEndpoint.<Initialize>d__1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.Endpoint.<Start>d__1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Program.<Main>d__0.MoveNext() in C:\Users\andre\Documents\GitHub\docs.particular.net\samples\learning-transport\Core_7\Endpoint1\Program.cs:line 19
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Program.<Main>()
```

So I think we can close this issue @indualagarsamy ?

**Comment by andreasohlund** [comment]
>I think there is nothing actually verifying that a type handled by a message handler is a valid message type?

@timbussmann this is correct, receiving a message that doesn't match the convention throws this:

``` 
2018-09-21 10:42:11.023 INFO  DefaultFactory Logging to 'C:\Users\andre\Documents\GitHub\docs.particular.net\samples\learning-transport\Core_7\Endpoint2\bin\Debug\netcoreapp2.1\' with level Info
2018-09-21 10:42:11.438 INFO  NServiceBus.LicenseManager No valid license could be found. Falling back to trial license with start date '2018-11-30'.

Press any key to exit
2018-09-21 10:42:15.261 ERROR NServiceBus.RecoverabilityExecutor Moving message 'f5521b21-9129-4af6-a988-a962008f70a4' to the error queue 'error' because processing failed due to an exception:
System.InvalidOperationException: No handlers could be found for message type: TheMessage
   at NServiceBus.LoadHandlersConnector.Invoke(IIncomingLogicalMessageContext context, Func`2 stage) in C:\BuildAgent\work\b549d46003942065\src\NServiceBus.Core\Pipeline\Incoming\LoadHandlersConnector.cs:line 57
   at NServiceBus.MutateIncomingMessageBehavior.InvokeIncomingMessageMutators(IIncomingLogicalMessageContext context, Func`2 next) in C:\BuildAgent\work\b549d46003942065\src\NServiceBus.Core\MessageMutators\MutateInstanceMessage\MutateIncomingMessageBehavior.cs:line 60
   at NServiceBus.DeserializeLogicalMessagesConnector.Invoke(IIncomingPhysicalMessageContext context, Func`2 stage) in C:\BuildAgent\work\b549d46003942065\src\NServiceBus.Core\Pipeline\Incoming\DeserializeLogicalMessagesConnector.cs:line 33
   at NServiceBus.UnitOfWorkBehavior.InvokeUnitsOfWork(IIncomingPhysicalMessageContext context, Func`2 next) in C:\BuildAgent\work\b549d46003942065\src\NServiceBus.Core\UnitOfWork\UnitOfWorkBehavior.cs:line 40
   at NServiceBus.UnitOfWorkBehavior.InvokeUnitsOfWork(IIncomingPhysicalMessageContext context, Func`2 next) in C:\BuildAgent\work\b549d46003942065\src\NServiceBus.Core\UnitOfWork\UnitOfWorkBehavior.cs:line 62
   at NServiceBus.MutateIncomingTransportMessageBehavior.InvokeIncomingTransportMessagesMutators(IIncomingPhysicalMessageContext context, Func`2 next) in C:\BuildAgent\work\b549d46003942065\src\NServiceBus.Core\MessageMutators\MutateTransportMessage\MutateIncomingTransportMessageBehavior.cs:line 59
   at NServiceBus.ProcessingStatisticsBehavior.Invoke(IIncomingPhysicalMessageContext context, Func`2 next) in C:\BuildAgent\work\b549d46003942065\src\NServiceBus.Core\Performance\Statistics\ProcessingStatisticsBehavior.cs:line 25
   at NServiceBus.TransportReceiveToPhysicalMessageProcessingConnector.Invoke(ITransportReceiveContext context, Func`2 next) in C:\BuildAgent\work\b549d46003942065\src\NServiceBus.Core\Pipeline\Incoming\TransportReceiveToPhysicalMessageProcessingConnector.cs:line 39
   at NServiceBus.MainPipelineExecutor.Invoke(MessageContext messageContext) in C:\BuildAgent\work\b549d46003942065\src\NServiceBus.Core\Pipeline\MainPipelineExecutor.cs:line 34
   at NServiceBus.LearningTransportMessagePump.ProcessFile(ILearningTransportTransaction transaction, String messageId) in C:\BuildAgent\work\b549d46003942065\src\NServiceBus.Core\Transports\Learning\LearningTransportMessagePump.cs:line 274

```

Would we want to prevent endpoints to startup when we detect this? (or perhaps log a warning)

**Comment by timbussmann** [comment]
not sure why we shouldn't just accept this message as a handler would indicate that this is a message and wouldn't require any further conventions on the handling side?

**Comment by andreasohlund** [comment]
@indualagarsamy ping https://github.com/Particular/NServiceBus/issues/2388#issuecomment-423459528

can we close this?
