### ISSUE TITLE
Persister errors are logged as INFO, should be ERROR

### ISSUE THREAD

**Issue by synhershko** [Particular/NServiceBus#2404]
See log below - it was using the internalized RavenDB (e.g. 2.0) as persistence.

```
2014-09-21 01:12:34,616 [29] INFO NServiceBus.Unicast.Transport.TransportReceiver [(null)] - Failed to process message
System.Transactions.TransactionAbortedException: The transaction has aborted. ---> System.IO.IsolatedStorage.IsolatedStorageException: Unable to create mutex. (Exception from HRESULT: 0x80131464)
at System.IO.IsolatedStorage.IsolatedStorageFile.Open(String infoFile, String syncName)
at System.IO.IsolatedStorage.IsolatedStorageFile.Lock(Boolean& locked)
at System.IO.IsolatedStorage.IsolatedStorageFileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, IsolatedStorageFile isf)
at System.IO.IsolatedStorage.IsolatedStorageFileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, IsolatedStorageFile isf)
at System.IO.IsolatedStorage.IsolatedStorageFile.CreateFile(String path)
at Raven.Client.Document.RavenClientEnlistment.Prepare(PreparingEnlistment preparingEnlistment) in c:\Builds\RavenDB-Stable\Raven.Client.Lightweight\Document\RavenClientEnlistment.cs:line 51
--- End of inner exception stack trace ---
at System.Transactions.TransactionStatePromotedAborted.PromotedTransactionOutcome(InternalTransaction tx)
at System.Transactions.CommittableTransaction.Commit()
at System.Transactions.TransactionScope.InternalDispose()
at System.Transactions.TransactionScope.Dispose()
at NServiceBus.Transports.Msmq.MsmqDequeueStrategy.Action() in y:\BuildAgent\work\31f8c64a6e8a2d7c\src\NServiceBus.Core\Transports\Msmq\MsmqDequeueStrategy.cs:line 269
2014-09-21 01:12:34,678 [23] INFO NServiceBus.Unicast.Transport.TransportReceiver [(null)] - Failed to process message
System.Transactions.TransactionAbortedException: The transaction has aborted. ---> System.IO.IsolatedStorage.IsolatedStorageException: Unable to create mutex. (Exception from HRESULT: 0x80131464)
at System.IO.IsolatedStorage.IsolatedStorageFile.Open(String infoFile, String syncName)
at System.IO.IsolatedStorage.IsolatedStorageFile.Lock(Boolean& locked)
at System.IO.IsolatedStorage.IsolatedStorageFileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, IsolatedStorageFile isf)
at System.IO.IsolatedStorage.IsolatedStorageFileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, IsolatedStorageFile isf)
at System.IO.IsolatedStorage.IsolatedStorageFile.CreateFile(String path)
at Raven.Client.Document.RavenClientEnlistment.Prepare(PreparingEnlistment preparingEnlistment) in c:\Builds\RavenDB-Stable\Raven.Client.Lightweight\Document\RavenClientEnlistment.cs:line 51
--- End of inner exception stack trace ---
at System.Transactions.TransactionStatePromotedAborted.PromotedTransactionOutcome(InternalTransaction tx)
at System.Transactions.CommittableTransaction.Commit()
at System.Transactions.TransactionScope.InternalDispose()
at System.Transactions.TransactionScope.Dispose()
at NServiceBus.Transports.Msmq.MsmqDequeueStrategy.Action() in y:\BuildAgent\work\31f8c64a6e8a2d7c\src\NServiceBus.Core\Transports\Msmq\MsmqDequeueStrategy.cs:line 269
```

**Comment by andreasohlund** [comment]
The new recoverability seam in v6 will now catch this and handle retries/logging etc just like any other error. I don't see any need to logg errors from persisters using different levels (INFO for immediate, WARN  for delayed retries and ERR when moving to error queue)

Closing this
