### ISSUE TITLE
When TransactionScope timeouts the real error is not available in the log

### ISSUE THREAD

**Issue by mauroservienti** [Particular/NServiceBus#2598]
If message handling fails due to TransactionScope timeout (default is 60 seconds) in the logs the logged error is the following:

> 2014-12-10 14:45:22.098 INFO  NServiceBus.Unicast.Transport.TransportReceiver Failed to process   message
System.Exception: Failed to send message to address: audit@BEAKER --->   System.Messaging.MessageQueueException: Cannot enlist the transaction.
   at System.Messaging.MessageQueue.SendInternal(Object obj, MessageQueueTransaction  internalTransaction, MessageQueueTransactionType transactionType)
    at System.Messaging.MessageQueue.Send(Object obj, MessageQueueTransactionType transactionType)
   at NServiceBus.Transports.Msmq.MsmqMessageSender.Send(TransportMessage message, SendOptions sendOptions) in c:\BuildAgent\work\1b05a2fea6e4cd32\src\NServiceBus.Core\Transports\Msmq\MsmqMessageSender.cs:line 60

The above error is technically correct, audit in this case was enabled and since the Transaction timed out the audit system cannot enlist in the transaction but the error is really misleading since points the user to look in the wrong direction;

If audit is fully disabled the real error pops up:

> 2014-12-10 16:25:45.828 INFO  NServiceBus.Unicast.Transport.TransportReceiver Failed to process message
System.Transactions.TransactionAbortedException: The transaction has aborted.
  at System.Transactions.TransactionStatePromotedAborted.BeginCommit(InternalTransaction tx, Boolean asyncCommit, AsyncCallback asyncCallback, Object asyncState)
  at System.Transactions.CommittableTransaction.Commit()
  at System.Transactions.TransactionScope.InternalDispose()
  at System.Transactions.TransactionScope.Dispose()
  at NServiceBus.Transports.Msmq.MsmqDequeueStrategy.Action() in c:\BuildAgent\work\1b05a2fea6e4cd32\src\NServiceBus.Core\Transports\Msmq\MsmqDequeueStrategy.cs:line 268

I expect to see in the logs every time also the real underlying reason of the failure.

**Comment by johnsimons** [comment]
Since it is impossible to know what the real error is, I'm closing this issue
