### ISSUE TITLE
Wrong log level in logs when TransactionScope timeouts

### ISSUE THREAD

**Issue by mauroservienti** [Particular/NServiceBus#2599]
When a Transaction timeouts the logged information is logged as INFO and not as ERROR, even if it will cause a retry:

> 2014-12-10 16:25:45.828 INFO  NServiceBus.Unicast.Transport.TransportReceiver Failed to process message
System.Transactions.TransactionAbortedException: The transaction has aborted.
  at System.Transactions.TransactionStatePromotedAborted.BeginCommit(InternalTransaction tx, Boolean asyncCommit, AsyncCallback asyncCallback, Object asyncState)
  at System.Transactions.CommittableTransaction.Commit()
  at System.Transactions.TransactionScope.InternalDispose()
  at System.Transactions.TransactionScope.Dispose()
  at NServiceBus.Transports.Msmq.MsmqDequeueStrategy.Action() in c:\BuildAgent\work\1b05a2fea6e4cd32\src\NServiceBus.Core\Transports\Msmq\MsmqDequeueStrategy.cs:line 268

The problem is that if the user sets up a log filter in production they are filtered out, thus the message fail but the error is not available in the logs.

**Comment by johnsimons** [comment]
@mauroservienti this issue has been raised a few times and since it is a breaking change, can you please raise this in the requirements.
