### ISSUE TITLE
Unable to cast object of type 'NServiceBus.Pipeline.Contexts.OutgoingContext' to type 'NServiceBus.Pipeline.Contexts.IncomingContext'. thrown

### ISSUE THREAD

**Issue by johnsimons** [Particular/NServiceBus#2714]
Reproducible in v5.2.0

If a user calls either:

- Bus.DoNotContinueDispatchingCurrentMessageToHandlers();
- Bus.HandleCurrentMessageLater();

on a `IMutateOutgoingMessages` when we are not in the receiving context, the code blows up with:
```
System.InvalidCastException was unhandled by user code
  HResult=-2147467262
  Message=Unable to cast object of type 'NServiceBus.Pipeline.Contexts.OutgoingContext' to type 'NServiceBus.Pipeline.Contexts.IncomingContext'.
  Source=NServiceBus.Core
  StackTrace:
       at NServiceBus.Unicast.UnicastBus.DoNotContinueDispatchingCurrentMessageToHandlers() in c:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Unicast\UnicastBus.cs:line 756
       at ClassLibrary29.DF.MutateOutgoing(Object message) in c:\Users\john\Documents\Visual Studio 2013\Projects\ClassLibrary29\EndpointConfig.cs:line 93
       at NServiceBus.MutateOutgoingMessageBehavior.Invoke(OutgoingContext context, Action next) in c:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\MessageMutator\MutateOutgoingMessageBehavior.cs:line 24
       at NServiceBus.BehaviorChain`1.InvokeNext(T context) in c:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Pipeline\BehaviorChain.cs:line 109
       at NServiceBus.BehaviorChain`1.<>c__DisplayClass5.<InvokeNext>b__2() in c:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Pipeline\BehaviorChain.cs:line 95
       at NServiceBus.SendValidatorBehavior.Invoke(OutgoingContext context, Action next) in c:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Unicast\Behaviors\SendValidatorBehavior.cs:line 21
       at NServiceBus.BehaviorChain`1.InvokeNext(T context) in c:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Pipeline\BehaviorChain.cs:line 109
       at NServiceBus.BehaviorChain`1.Invoke() in c:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Pipeline\BehaviorChain.cs:line 61
       at NServiceBus.Pipeline.PipelineExecutor.Execute[T](BehaviorChain`1 pipelineAction, T context) in c:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Pipeline\PipelineExecutor.cs:line 129
       at NServiceBus.Pipeline.PipelineExecutor.InvokePipeline[TContext](IEnumerable`1 behaviors, TContext context) in c:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Pipeline\PipelineExecutor.cs:line 86
       at NServiceBus.Pipeline.PipelineExecutor.InvokeSendPipeline(DeliveryOptions deliveryOptions, LogicalMessage message) in c:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Pipeline\PipelineExecutor.cs:line 116
       at NServiceBus.Unicast.UnicastBus.InvokeSendPipeline(DeliveryOptions sendOptions, LogicalMessage message) in c:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Unicast\UnicastBus.cs:line 629
       at NServiceBus.Unicast.UnicastBus.SendMessage(SendOptions sendOptions, LogicalMessage message) in c:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Unicast\UnicastBus.cs:line 610
       at NServiceBus.Unicast.UnicastBus.SendLocal(Object message) in c:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Unicast\UnicastBus.cs:line 445
       at ClassLibrary29.F.Start() in c:\Users\john\Documents\Visual Studio 2013\Projects\ClassLibrary29\EndpointConfig.cs:line 37
       at NServiceBus.Unicast.UnicastBus.<Start>b__9(IWantToRunWhenBusStartsAndStops toRun) in c:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Unicast\UnicastBus.cs:line 685
       at System.Threading.Tasks.Parallel.<>c__DisplayClassf`1.<ForWorker>b__c()
  InnerException: 
```

## Code to repro

```c#
public class EndpointConfig : IConfigureThisEndpoint
{
    public void Customize(BusConfiguration configuration)
    {
        configuration.UsePersistence<InMemoryPersistence>();
        configuration.RegisterComponents(c => c.ConfigureComponent<DF>(DependencyLifecycle.InstancePerCall));
    }
}

class F : IWantToRunWhenBusStartsAndStops
{
    public IBus Bus { get; set; }

    public void Start()
    {
        Bus.SendLocal(new MyMessage());
            
    }

    public void Stop()
    {
    }
}

class MyMessage : ICommand
{
}

class D:IHandleMessages<MyMessage>
{
    public void Handle(MyMessage message)
    {
    }
}

class DF: IMutateOutgoingMessages
{
    public IBus Bus { get; set; }

    public object MutateOutgoing(object message)
    {
        Bus.DoNotContinueDispatchingCurrentMessageToHandlers();
        Bus.HandleCurrentMessageLater();
        return message;
    }
}
```

**Comment by johnsimons** [comment]
@Particular/nservicebus do we patch this ?

**Comment by danielmarbach** [comment]
@johnsimons this affects the sending side and the exception is thrown back to the caller. So no message is being lost. Annoying but not critical.

**Comment by johnsimons** [comment]
I didn't say it was critical :wink:, I think it would still be nice to put a patch out.

**Comment by udidahan** [comment]
Why would they validate on the sending side?

**Comment by johnsimons** [comment]
> Why would they validate on the sending side?

@udidahan I asked the same question to the user in the mailing list.
But regardless how we got here, an exception is still being thrown :disappointed:

**Comment by andreasohlund** [comment]
I don't see this as a patch. 

User calls:

     Bus.DoNotContinueDispatchingCurrentMessageToHandlers();
        Bus.HandleCurrentMessageLater();

which isn't valid to call if there is no incoming message being processed. If they do we throw, yes it's not a good ex but we can fix that in the next minor/major.

This IMO is another reason why its's good that we move to a more "context" based approach where we provide a context parameter containing the operations that's valid for the scenario at hand.

We should take this into account when changing the mutator api in v6. Does this make sense?

**Comment by johnsimons** [comment]
@andreasohlund for your info "patch" means whatever next version is, and I agree this is not a critical patch so it can be deployed in whatever the next version is.

So, are we patching v5 or we are only addressing this in vnext aka v6 ?

**Comment by andreasohlund** [comment]
Since there is no 5.3 on the radar yet I'd say v6 for now?

**Comment by johnsimons** [comment]
ok thanks @andreasohlund

**Comment by andreasohlund** [comment]
@Particular/nservicebus-maintainers pretty sure the handler context/mutator context have fixed this? close?

**Comment by danielmarbach** [comment]
Haven't seen this for a while

**Comment by timbussmann** [comment]
> @Particular/nservicebus-maintainers pretty sure the handler context/mutator context have fixed this? close?

:+1: Let's close this.
