### ISSUE TITLE
`DelayedDeliveryFeature` makes assumptions about `UnicastBusConfig` begin present

### ISSUE THREAD

**Issue by danielmarbach** [Particular/NServiceBus#2913]
## Who's affected
Developers trying out develop 6.0.0-unstable0878 and later without a `UnicastBusConfig` defined (i.ex. self-hosting)

## Symptons
1. Starting an endpoint without a `UnicastBusConfig` throw a `NullReferenceException`

## Steps to reproduce
1. Take [Startup Shutdown Sequence Sample](http://docs.particular.net/samples/startup-shutdown-sequence/) and upgrade it to latest v6 develop
2. Start the endpoint

```
System.NullReferenceException was unhandled
  HResult=-2147467261
  Message=Object reference not set to an instance of an object.
  Source=NServiceBus.Core
  StackTrace:
       at NServiceBus.Features.DelayedDeliveryFeature.<>c.<.ctor>b__0_0(SettingsHolder s) in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\DelayedDelivery\DelayedDeliveryFeature.cs:line 19
       at NServiceBus.Features.FeatureActivator.SetupFeatures(FeatureConfigurationContext context) in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Features\FeatureActivator.cs:line 103
       at NServiceBus.Configure.Initialize() in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Configure.cs:line 97
       at NServiceBus.Bus.Create(BusConfiguration configuration) in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Bus.cs:line 17
       at Program.Main() in C:\particular\docs.particular.net\samples\startup-shutdown-sequence\Version_6\Sample\Program.cs:line 20
  InnerException: 
```

**Comment by danielmarbach** [comment]
@SzymonPobiega @DavidBoike what would be the best way to fix this?

**Comment by danielmarbach** [comment]
The code causing the trouble is this one:

```
         Defaults(s =>
            {
                var timeoutManagerAddressConfiguration = new TimeoutManagerAddressConfiguration(s.GetConfigSection<UnicastBusConfig>().TimeoutManagerAddress);
                s.Set<TimeoutManagerAddressConfiguration>(timeoutManagerAddressConfiguration);
            });
```

**Comment by andreasohlund** [comment]
Since this was only there to support the distributor overriding the TM address I think we can just remove it? (with proper doco, obsoletes etc)

**Comment by SzymonPobiega** [comment]
@andreasohlund so you suggest remove the possibility of using a remote TM?

**Comment by andreasohlund** [comment]
I guess I do :)  What is the use case for a remote TM? (given that we are obsoleteing the Distributor)

**Comment by SzymonPobiega** [comment]
I don't see any to be honest.

**Comment by danielmarbach** [comment]
Something less running in the same endpoint and taking its ressources?

**Comment by andreasohlund** [comment]
Have we heard anything from customers where they have asked for this?

@yvesgoeleven I have a faint memory that you had a Azure specific angle on this?

**Comment by yvesgoeleven** [comment]
@andreasohlund a separate TM makes sense as a workaround for the lack of leader election when running multiple copies of an endpoint with TM sattelite
