### ISSUE TITLE
NserviceBus.Host 'Should_default_to_msmq_if_no_other_transport_is_configured' failing

### ISSUE THREAD

**Issue by petersgiles** [Particular/NServiceBus#3246]
In NServiceBus.Host this test `Should_default_to_msmq_if_no_other_transport_is_configured` is failing with this stack trace

Is there something missing or a new thing I have to do when configuring the bus to ensure it doesn't fail anymore. Is this test still relevant? 

```C#
Test(s) failed. System.Collections.Generic.KeyNotFoundException : The given key (NServiceBus.Transports.TransportDefinition) was not present in the dictionary.
   at NServiceBus.Settings.SettingsHolder.Get(String key) in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Settings\SettingsHolder.cs:line 93
   at NServiceBus.Settings.SettingsHolder.Get[T]() in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Settings\SettingsHolder.cs:line 71
   at NServiceBus.Hosting.Tests.With_transport_tests.Should_default_to_msmq_if_no_other_transport_is_configured() in C:\BuildAgent\work\fc89e968acb99302\src\NServiceBus.Hosting.Tests\With_transport_tests.cs:line 31

```

**Comment by andreasohlund** [comment]
That test looks really funky, we would we need to test that, the core is the one responsible for doing that default? (which I think we should stop doing)

I'd say remove the test?

**Comment by WilliamBZA** [comment]
Is this still an issue? Test is passing.

It does seem though that the test should be moved to Core as it only tests and uses Core functionality. There is no code in NserviceBus.Host that is being called within the test.

I propose moving the test to Core.

**Comment by petersgiles** [comment]
It's possible that I need to update the core in NSB Host its been a while. I have removed the test from the Host. It definitely doesn't belong there.

**Comment by WilliamBZA** [comment]
Ok. Seems a non-issue then. Marking as closed.
