### ISSUE TITLE
v6 endpoint cannot subscribe to messages from v5 endpoint

### ISSUE THREAD

**Issue by mikeminutillo** [Particular/NServiceBus#3388]
When a v6 endpoint sends a Subscribe control message to a v5 endpoint it is missing the ReplyTo address and the v5 endpoint rejects it.

v5 rejection message

```
2016-02-01 09:58:15.2792|24|Info|NServiceBus.Unicast.Transport.TransportReceiver|Failed to process message
System.InvalidOperationException: Subscription message arrived without a valid ReplyToAddress
   at NServiceBus.SubscriptionReceiverBehavior.Invoke(IncomingContext context, Action next)
   at NServiceBus.BehaviorChain`1.InvokeNext(T context)
   at NServiceBus.BehaviorChain`1.<>c__DisplayClass4_0.<InvokeNext>b__0()
   at NServiceBus.UnitOfWorkBehavior.Invoke(IncomingContext context, Action next)
   at NServiceBus.BehaviorChain`1.InvokeNext(T context)
   at NServiceBus.BehaviorChain`1.<>c__DisplayClass4_0.<InvokeNext>b__0()
   at ServiceControl.Infrastructure.RavenDB.RavenUnitOfWorkBehavior.Invoke(IncomingContext context, Action next) in C:\Code\Particular\ServiceControl\src\ServiceControl\Infrastructure\RavenDB\RavenUnitOfWorkBehavior.cs:line 23
   at NServiceBus.BehaviorChain`1.InvokeNext(T context)
   at NServiceBus.BehaviorChain`1.<>c__DisplayClass4_0.<InvokeNext>b__0()
   at NServiceBus.ChildContainerBehavior.Invoke(IncomingContext context, Action next)
   at NServiceBus.BehaviorChain`1.InvokeNext(T context)
   at NServiceBus.BehaviorChain`1.<>c__DisplayClass4_0.<InvokeNext>b__0()
   at NServiceBus.ProcessingStatisticsBehavior.Invoke(IncomingContext context, Action next)
   at NServiceBus.BehaviorChain`1.InvokeNext(T context)
   at NServiceBus.BehaviorChain`1.Invoke()
   at NServiceBus.Pipeline.PipelineExecutor.Execute[T](BehaviorChain`1 pipelineAction, T context)
   at NServiceBus.Unicast.Transport.TransportReceiver.OnTransportMessageReceived(TransportMessage msg)
   at NServiceBus.Unicast.Transport.TransportReceiver.ProcessMessage(TransportMessage message)
   at NServiceBus.Unicast.Transport.TransportReceiver.TryProcess(TransportMessage message)
   at NServiceBus.Transports.Msmq.MsmqDequeueStrategy.Action()
```

Sample Subscribe message headers from v6 endpoint (pulled from error queue)
```
<?xml version="1.0"?>
<ArrayOfHeaderInfo xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <HeaderInfo>
    <Key>NServiceBus.Version</Key>
    <Value>6.0.0</Value>
  </HeaderInfo>
  <HeaderInfo>
    <Key>NServiceBus.TimeSent</Key>
    <Value>2016-02-01 01:58:15:018540 Z</Value>
  </HeaderInfo>
  <HeaderInfo>
    <Key>NServiceBus.ControlMessage</Key>
    <Value>True</Value>
  </HeaderInfo>
  <HeaderInfo>
    <Key>NServiceBus.MessageIntent</Key>
    <Value>Subscribe</Value>
  </HeaderInfo>
  <HeaderInfo>
    <Key>SubscriptionMessageType</Key>
    <Value>ServiceControl.Contracts.MessageFailed, ServiceControl.Contracts, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null</Value>
  </HeaderInfo>
  <HeaderInfo>
    <Key>NServiceBus.SubscriberAddress</Key>
    <Value>ListenToServiceControl@MIKE_LAPTOP</Value>
  </HeaderInfo>
  <HeaderInfo>
    <Key>NServiceBus.SubscriberEndpoint</Key>
    <Value>ListenToServiceControl</Value>
  </HeaderInfo>
  <HeaderInfo>
    <Key>CorrId</Key>
    <Value />
  </HeaderInfo>
  <HeaderInfo>
    <Key>NServiceBus.MessageId</Key>
    <Value>413a4e94-6cb5-490e-8f43-f50d416afa75\16521231</Value>
  </HeaderInfo>
  <HeaderInfo>
    <Key>NServiceBus.CorrelationId</Key>
  </HeaderInfo>
  <HeaderInfo>
    <Key>$.diagnostics.hostid</Key>
    <Value>7c499f534f85270f73b3c010a68594de</Value>
  </HeaderInfo>
  <HeaderInfo>
    <Key>$.diagnostics.hostdisplayname</Key>
    <Value>MIKE_LAPTOP</Value>
  </HeaderInfo>
  <HeaderInfo>
    <Key>NServiceBus.FLRetries</Key>
    <Value>2</Value>
  </HeaderInfo>
  <HeaderInfo>
    <Key>NServiceBus.ExceptionInfo.ExceptionType</Key>
    <Value>System.InvalidOperationException</Value>
  </HeaderInfo>
  <HeaderInfo>
    <Key>NServiceBus.ExceptionInfo.HelpLink</Key>
  </HeaderInfo>
  <HeaderInfo>
    <Key>NServiceBus.ExceptionInfo.Message</Key>
    <Value>Subscription message arrived without a valid ReplyToAddress</Value>
  </HeaderInfo>
  <HeaderInfo>
    <Key>NServiceBus.ExceptionInfo.Source</Key>
    <Value>NServiceBus.Core</Value>
  </HeaderInfo>
  <HeaderInfo>
    <Key>NServiceBus.ExceptionInfo.StackTrace</Key>
    <Value>System.InvalidOperationException: Subscription message arrived without a valid ReplyToAddress
   at NServiceBus.SubscriptionReceiverBehavior.Invoke(IncomingContext context, Action next)
   at NServiceBus.BehaviorChain`1.InvokeNext(T context)
   at NServiceBus.BehaviorChain`1.&lt;&gt;c__DisplayClass4_0.&lt;InvokeNext&gt;b__0()
   at NServiceBus.UnitOfWorkBehavior.Invoke(IncomingContext context, Action next)
   at NServiceBus.BehaviorChain`1.InvokeNext(T context)
   at NServiceBus.BehaviorChain`1.&lt;&gt;c__DisplayClass4_0.&lt;InvokeNext&gt;b__0()
   at ServiceControl.Infrastructure.RavenDB.RavenUnitOfWorkBehavior.Invoke(IncomingContext context, Action next) in C:\Code\Particular\ServiceControl\src\ServiceControl\Infrastructure\RavenDB\RavenUnitOfWorkBehavior.cs:line 23
   at NServiceBus.BehaviorChain`1.InvokeNext(T context)
   at NServiceBus.BehaviorChain`1.&lt;&gt;c__DisplayClass4_0.&lt;InvokeNext&gt;b__0()
   at NServiceBus.ChildContainerBehavior.Invoke(IncomingContext context, Action next)
   at NServiceBus.BehaviorChain`1.InvokeNext(T context)
   at NServiceBus.BehaviorChain`1.&lt;&gt;c__DisplayClass4_0.&lt;InvokeNext&gt;b__0()
   at NServiceBus.ProcessingStatisticsBehavior.Invoke(IncomingContext context, Action next)
   at NServiceBus.BehaviorChain`1.InvokeNext(T context)
   at NServiceBus.BehaviorChain`1.Invoke()
   at NServiceBus.Pipeline.PipelineExecutor.Execute[T](BehaviorChain`1 pipelineAction, T context)
   at NServiceBus.Unicast.Transport.TransportReceiver.OnTransportMessageReceived(TransportMessage msg)
   at NServiceBus.Unicast.Transport.TransportReceiver.ProcessMessage(TransportMessage message)
   at NServiceBus.Unicast.Transport.TransportReceiver.TryProcess(TransportMessage message)
   at NServiceBus.Transports.Msmq.MsmqDequeueStrategy.Action()</Value>
  </HeaderInfo>
  <HeaderInfo>
    <Key>NServiceBus.FailedQ</Key>
    <Value>Particular.ServiceControl@MIKE_LAPTOP</Value>
  </HeaderInfo>
  <HeaderInfo>
    <Key>NServiceBus.TimeOfFailure</Key>
    <Value>2016-02-01 01:58:15:307291 Z</Value>
  </HeaderInfo>
</ArrayOfHeaderInfo>
```

TODO:

 * [x] Fix exception
 * [ ] Figure out what to do for a scaled-out V6 MSMQ endpoint that subscribes to V5-published message.

**Comment by mikeminutillo** [comment]
OK. Apparently this is by design. You can fix this by calling `busConfiguration.UseLegacyMessageDrivenSubscriptionMode()`

@Particular/nservicebus-maintainers I don't think this is a sensible default. It can lead to message loss. If I send a subscription to a v5 endpoint and it fails to process it, the subscribe message goes into the error queue (so it is not lost) but any events published in the meantime will not arrive at the subscriber.

**Comment by mikeminutillo** [comment]
This API also assumes that all of the endpoints you are subscribing to are legacy or not legacy. In reality it is likely to be a mixture or both.

**Comment by danielmarbach** [comment]
ping @SzymonPobiega

**Comment by SzymonPobiega** [comment]
The reasoning behind this thing was that if you scale out and use client-side distribution, the V5 subscription handling was not able to recognize multiple subscriptions coming from a single, scaled-out endpoint.

Now, based on my proposal here https://github.com/Particular/NServiceBus/issues/3369 and a spike here https://github.com/Particular/NServiceBus/pull/3374 (all transports treat the shared receiver address as the main one) the problem of event distribution seems to affect only scaled-out MSMQ endpoints so I no longer see the point in defaulting to a braking change (and potentially message loss) option.

We already decided to tell people who use distributor their V5 deployment to keep it when upgrading to V6 because it will allow them to use the V6 cluster in same way as old V5 cluster and in the same time allow other V6 endpoints to use the V6 cluster directly.

I think we should extend that guidance and say that if you want to have a V6 cluster (even a new one) that talks to any V5 endpoints, you need to set up a distributor in front of that cluster.

**Comment by mikeminutillo** [comment]
@SzymonPobiega Now that #3374 has been merged. Is it possible for a v6 endpoint to subscribe to a v5 one without additional configuration?

**Comment by SzymonPobiega** [comment]
Yeah, should work in all cases except for the scaled-out MSMQ V6 cluster which has to go through the distributor. Otherwise the events will get send to every instance. This issue should stay open though until I have a proper doco issue raised or done to document that.

**Comment by SzymonPobiega** [comment]
https://github.com/Particular/NServiceBus/pull/3517 attempts to fix this.

**Comment by andreasohlund** [comment]
@mikeminutillo since #3517 is merge can you verify and close this if you are happy with the fix?

:cop:  @SzymonPobiega when you're pulls get merged please make sure to close related issues

**Comment by SzymonPobiega** [comment]
@andreasohlund there is no doco issue raised yet so I need to leave this one open. #3517 only fixes the exception @mikeminutillo raised. The remaining issue is if you deploy a V6 cluster on MSMQ and forget to put a distributor in front of it, each endpoint will subscribe by itself causing events to be delivered to each instance.

**Comment by danielmarbach** [comment]
@SzymonPobiega sounds like you need a TF to work on 

> The remaining issue is if you deploy a V6 cluster on MSMQ and forget to put a distributor in front of it, each endpoint will subscribe by itself causing events to be delivered to each instance.

right? Can you kick it off?

**Comment by SzymonPobiega** [comment]
I think it belongs to the 133 TF (myself and @janovesk ).

**Comment by andreasohlund** [comment]
>there is no doco issue raised yet so I need to leave this one open. #3517 only fixes the exception

Can you add this as a check list in the description?

**Comment by timbussmann** [comment]
@SzymonPobiega @mikeminutillo does this doco PR https://github.com/Particular/docs.particular.net/pull/1315 "fix" the remaining task in the description?

**Comment by SzymonPobiega** [comment]
@timbussmann yes. @mikeminutillo do you think it is enough?

**Comment by mikeminutillo** [comment]
I *think* this is OK. This will only happen when someone adds a new v6 endpoint to an existing v5 solution and then tries to scale it out. It seems likely that the customer would check the docs before doing that.
