### ISSUE TITLE
Failures during acceptance test initialization throw away the exception message and stack trace outside Visual Studio

### ISSUE THREAD

**Issue by janovesk** [Particular/NServiceBus#3391]
## Given the following test 
```csharp
public class WhenThrowingDuringInitialization : NServiceBusAcceptanceTest
{
    [Test]
    public async Task ShouldShowErrorInLogOnBuildServer()
    {
        await Scenario.Define<Context>(c => { })
            .WithEndpoint<Endpoint>()
            .Done(c => c.EndpointsStarted)
            .Run();
    }

    public class Context : ScenarioContext{}

    public class Endpoint : EndpointConfigurationBuilder
    {
        public Endpoint()
        {
            EndpointSetup<DefaultServer>(c => { c.EnableFeature<TestFeature>(); });
        }

        public class TestFeature : Feature
        {
            public TestFeature()
            {
                EnableByDefault();                    
            }

            protected override void Setup(FeatureConfigurationContext context)
            {
                context.RegisterStartupTask(b => new TestTask());
            }

            public class TestTask : FeatureStartupTask
            {
                protected override Task OnStart(IBusSession session)
                {
                    throw new NullReferenceException();
                }

                protected override Task OnStop(IBusSession session)
                {
                    return Task.FromResult(0);
                }
            }
        }
    }
}
```
## Output from local test run in Visual Studio: 
```csharp
MsmqTransport - Started @ 02/01/2016 14:18:27
License expires on 1/1/2020 12:00:00 AM
Queue ELEFANT\private$\Whenthrowingduringinitialization.Endpoint does not exist.
Did not attempt to add user 'ELEFANT\janovesk' to group 'Performance Monitor Users' since process is not running with elevate privileges. Processing will continue. To manually perform this action run the following command from an admin console:
net localgroup "Performance Monitor Users" "ELEFANT\janovesk" /add
Queue [private$\error] is running with [Everyone] and [NT AUTHORITY\ANONYMOUS LOGON] permissions. Consider setting appropriate permissions, if required by your organization. For more information, please consult the documentation.
Queue [private$\Whenthrowingduringinitialization.Endpoint] is running with [Everyone] and [NT AUTHORITY\ANONYMOUS LOGON] permissions. Consider setting appropriate permissions, if required by your organization. For more information, please consult the documentation.

Failed to start endpoint Whenthrowingduringinitialization.Endpoint System.NullReferenceException: Object reference not set to an instance of an object.
   at NServiceBus.AcceptanceTests.Basic.WhenThrowingDuringInitialization.Endpoint.TestFeature.TestTask.OnStart(IBusSession session) in C:\nsb\NServiceBus\src\NServiceBus.AcceptanceTests\Basic\When_sending_from_a_send_only.cs:line 46
   at NServiceBus.Features.FeatureStartupTask.PerformStartup(IBusSession session) in C:\nsb\NServiceBus\src\NServiceBus.Core\Features\FeatureStartupTask.cs:line 24
   at NServiceBus.Features.FeatureStartupTaskController.Start(IBuilder builder, IBusSession busSession) in C:\nsb\NServiceBus\src\NServiceBus.Core\Features\FeatureStartupTaskController.cs:line 22
   at NServiceBus.Features.FeatureActivator.<StartFeatures>d__5.MoveNext() in C:\nsb\NServiceBus\src\NServiceBus.Core\Features\FeatureActivator.cs:line 72
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at NServiceBus.StartableEndpoint.<StartFeatures>d__10.MoveNext() in C:\nsb\NServiceBus\src\NServiceBus.Core\StartableEndpoint.cs:line 92
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at NServiceBus.StartableEndpoint.<Start>d__6.MoveNext() in C:\nsb\NServiceBus\src\NServiceBus.Core\StartableEndpoint.cs:line 44
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at NServiceBus.AcceptanceTesting.Support.EndpointRunner.<Start>d__11.MoveNext() in C:\nsb\NServiceBus\src\NServiceBus.AcceptanceTesting\Support\EndpointRunner.cs:line 85
Stopping endpoint: Whenthrowingduringinitialization.Endpoint
Failed to stop endpoint Whenthrowingduringinitialization.Endpoint System.NullReferenceException: Object reference not set to an instance of an object.
   at NServiceBus.AcceptanceTesting.Support.EndpointRunner.<Stop>d__13.MoveNext() in C:\nsb\NServiceBus\src\NServiceBus.AcceptanceTesting\Support\EndpointRunner.cs:line 159```
Deleted 'FormatName:DIRECT=OS:elefant\private$\whenthrowingduringinitialization.endpoint' queue
MsmqTransport - Finished @ 02/01/2016 14:18:32
------------------------------------------------------
Test summary for: MsmqTransport


Using settings:
   Transport: NServiceBus.MsmqTransport, NServiceBus.Core, Version=6.0.0.0, Culture=neutral, PublicKeyToken=9fc386479f8a226c
   Transport.ConnectionString: cacheSendConnection=false;journal=false;


Endpoints:
     - Whenthrowingduringinitialization.Endpoint
Result: Successful - Duration: 00:00:04.6115939

Context:
TestRunId = 4440cb56-72be-49be-91ed-fc2456d5d50d
EndpointsStarted = True
HasNativePubSubSupport = False

Trace:

------------------------------------------------------
Total time for testrun: 00:00:04.7042484
```

Test fails as expected and we get the exception message and a nice stack trace.

## Output from the build server/NUnit stand alone
```csharp
***** NServiceBus.AcceptanceTests.Basic.WhenThrowingDuringInitialization.ShouldShowErrorInLogOnBuildServer
MsmqTransport - Started @ 02/01/2016 14:18:41
Stopping endpoint: Whenthrowingduringinitialization.Endpoint
Deleted 'FormatName:DIRECT=OS:elefant\private$\whenthrowingduringinitialization.endpoint' queue
MsmqTransport - Finished @ 02/01/2016 14:18:45
------------------------------------------------------
Test summary for: MsmqTransport




Using settings:
   Transport: NServiceBus.MsmqTransport, NServiceBus.Core, Version=6.0.0.0, Culture=neutral, PublicKeyToken=9fc386479f8a226c
   Transport.ConnectionString: cacheSendConnection=false;journal=false;




Endpoints:
     - Whenthrowingduringinitialization.Endpoint
Result: Successful - Duration: 00:00:04.5704432


Context:
TestRunId = de5764b1-5715-44e7-92ac-83e13775e055
EndpointsStarted = True
HasNativePubSubSupport = False


Trace:

------------------------------------------------------
Total time for testrun: 00:00:04.6379678
```

Test still fails, but the exception message and stack trace is gone. This happens when you run outside Visual Studio, like on the build server. This is clearly not optimal.

**Comment by janovesk** [comment]
Same applies to to any exception thrown during the initialization of installers.

**Comment by janovesk** [comment]
Ping @Particular/nservicebus-maintainers @timbussmann @danielmarbach

**Comment by timbussmann** [comment]
Looks like the output comes from the nUnit  `Trace` listener. If I add `Trace.Listeners.Cear()` as first call on the test method, I get the same output as on the buildserver. Looks like an nUnit configuration "issue"?

**Comment by danielmarbach** [comment]
Nunit upgrade is long overdue, have you tried 3.0?

**Comment by danielmarbach** [comment]
@timbussmann @janovesk @Particular/nservicebus-maintainers what do we do with this one? I haven't seen this for a while.

**Comment by timbussmann** [comment]
should we link this to the nunit 3 upgrade issue and then verify whether this is still an issue after the upgrade?

**Comment by danielmarbach** [comment]
yeah better than assuming. Can we label this one somehow?

**Comment by andreasohlund** [comment]
We've now updated to nunit3 is this still an issue?

**Comment by timbussmann** [comment]
tested with the nunit3 console runner and I can see the stack trace both on the test's log output and on the exception report from nunit itself. I'm closing this, please reopen if I missed something.
