### ISSUE TITLE
Flaky AT When_updating_existing_correlation_property.Should_blow_up()

### ISSUE THREAD

**Issue by johnsimons** [Particular/NServiceBus#3713]
In Rabbit we occasionally have this test failing with:
```
Expected: <System.AggregateException>
  But was:  null

   at NUnit.Framework.Assert.That(Object actual, IResolveConstraint expression, String message, Object[] args)
   at NUnit.Framework.Assert.Throws(IResolveConstraint expression, TestDelegate code, String message, Object[] args)
   at NUnit.Framework.Assert.Throws(Type expectedExceptionType, TestDelegate code, String message, Object[] args)
   at NUnit.Framework.Assert.Throws[T](TestDelegate code, String message, Object[] args)
   at NUnit.Framework.Assert.Throws[T](TestDelegate code)
   at NServiceBus.AcceptanceTests.Sagas.When_updating_existing_correlation_property.Should_blow_up() in C:\Projects\NServiceBus.RabbitMQ\src\NServiceBus.RabbitMQ.AcceptanceTests\App_Packages\NSB.AcceptanceTests.6.0.0-beta0002\Sagas\When_updating_existing_correlation_property.cs:line 16
```

It seems the done flag is set before the exception bubbles up:
```c#
if (message.SecondMessage)
{
                        Data.SomeId = Guid.NewGuid(); //this is not allowed
                        TestContext.ModifiedCorrelationProperty = true; // <- this is the done flag
                        return Task.FromResult(0);
 }
```
And it seems sometimes the endpoint terminates before the exception is raised.

To repro this issue run the test using https://github.com/Particular/NServiceBus.RabbitMQ/pull/136
You need to run the test as a group (individually I can't make it fail!):
![image](https://cloud.githubusercontent.com/assets/122651/14881487/8f7b5538-0d77-11e6-96d0-2b462459848e.png)

**Comment by timbussmann** [comment]
should be fixed with https://github.com/Particular/NServiceBus/pull/3712

**Comment by timbussmann** [comment]
closing this, since #3712 has been merged. Please reopen if the test continue to fail.
