### ISSUE TITLE
If PurgeOldFiles throws an exception the application will never start

### ISSUE THREAD

**Issue by janpieterz** [Particular/NServiceBus#3739]
I'm running an ASP.NET Core (RC1) app that suddenly went into a shutdown yesterday. Fix was to manually remove the log files it was trying to purge. For some reason it encountered an UnauthorizedAccessException and it was unable to just pass on (no try-catch). 

Seems to me that, since it is more of a cleanup-oriented task, it shouldn't be in the critical application path and prevent a successful startup.

Relevant piece of code: https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/Logging/RollingLogger.cs#L64

Exception:

```
Application startup exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.TypeInitializationException: The type initializer for 'NServiceBus.Unicast.MessageHandlerRegistry' threw an exception. ---> System.UnauthorizedAccessException: Access to the path 'C:\Octopus\Applications\ENM XXX\Intreba.Enm.Web\1.0.1111.1179_4\approot\runtimes\dnx-clr-win-x64.1.0.0-rc1-final\bin\nsb_log_2016-05-04_0.txt' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalDelete(String path, Boolean checkHost)
   at NServiceBus.Logging.RollingLogger.PurgeOldFiles(List`1 logFiles) in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Logging\RollingLogger.cs:line 75
   at NServiceBus.Logging.RollingLogger.Write(String message) in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Logging\RollingLogger.cs:line 34
   at NServiceBus.Logging.DefaultLoggerFactory.Write(String name, LogLevel messageLevel, String message) in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Logging\DefaultLoggerFactory.cs:line 57
   at NServiceBus.Logging.DefaultFactory.GetLoggingFactory() in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Logging\DefaultFactory.cs:line 32
   at System.Lazy`1.CreateValue()
--- End of stack trace from previous location where exception was thrown ---
   at NServiceBus.Logging.LogManager.GetLogger(Type type) in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Logging\LogManager.cs:line 61
   at NServiceBus.Unicast.MessageHandlerRegistry..cctor() in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Unicast\MessageHandlerRegistry.cs:line 202
   --- End of inner exception stack trace ---
   at NServiceBus.Unicast.MessageHandlerRegistry.RegisterHandler(Type handlerType) in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Unicast\MessageHandlerRegistry.cs:line 70
   at NServiceBus.Features.RegisterHandlersInOrder.ConfigureMessageHandlersIn(FeatureConfigurationContext context, IEnumerable`1 types) in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Unicast\Config\RegisterHandlersInOrder.cs:line 89
   at NServiceBus.Features.RegisterHandlersInOrder.LoadMessageHandlers(FeatureConfigurationContext context, IEnumerable`1 orderedTypes) in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Unicast\Config\RegisterHandlersInOrder.cs:line 77
   at NServiceBus.Features.RegisterHandlersInOrder.Setup(FeatureConfigurationContext context) in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Unicast\Config\RegisterHandlersInOrder.cs:line 33
   at NServiceBus.Features.FeatureActivator.ActivateFeature(FeatureState featureState, IEnumerable`1 featuresToActivate, FeatureConfigurationContext context) in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Features\FeatureActivator.cs:line 235
   at NServiceBus.Features.FeatureActivator.SetupFeatures(FeatureConfigurationContext context) in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Features\FeatureActivator.cs:line 116
   at NServiceBus.Configure.Initialize() in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Configure.cs:line 115
   at NServiceBus.Bus.CreateSendOnly(BusConfiguration configuration) in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Bus.cs:line 33
   at Intreba.Enm.Web.Startup.ConfigureServices(IServiceCollection services) in C:\Octopus\Applications\ENM XXX\Intreba.Enm.Web\1.0.1111.1179_4\approot\src\Intreba.Enm.Web\Startup.cs:line 91
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNet.Hosting.Startup.ConfigureServicesBuilder.Invoke(Object instance, IServiceCollection exportServices)
   at Microsoft.AspNet.Hosting.Internal.HostingEngine.BuildApplication()
```

**Comment by SimonCropp** [comment]
@janovesk good point. we will add a fix for this

**Comment by SimonCropp** [comment]
it does raise the question of what we do in the catch. the only thing to do is log an error. so if that fails it will still crash

**Comment by janpieterz** [comment]
Yeah, looked at the code and thought about that as well, otherwise I'd have done a simple pull request.

What if the try-catch would be only around the PurgeOldFiles? The SyncFileSystem call will then always pass even if that fails, and the write about it will succeed (unless of course the writing itself (AppendLine) also fails, which wasn't the case in our environment yesterday)

**Comment by SimonCropp** [comment]
@janpieterz i will put together a PR and we can start discussing it there

**Comment by SimonCropp** [comment]
first cut of a PR https://github.com/Particular/NServiceBus/pull/3741
