### ISSUE TITLE
System.ArgumentException was unhandled - Address contains multiple @ characters

### ISSUE THREAD

**Issue by johnsimons** [Particular/NServiceBus#3799]
This was reported in https://groups.google.com/d/msg/particularsoftware/3m2OF4qH1LQ/qhqnV-cgKAAJ

To reproduce:
Download https://github.com/Particular/docs.particular.net/tree/master/samples/pubsub/Core_6
and modify https://github.com/Particular/docs.particular.net/blob/master/samples/pubsub/Core_6/Subscriber1/App.config
to something like:
```xml
<add Assembly="Shared" Endpoint="Samples.PubSub.MyPublisher@mymachinename"/>
```

Exception:
```
System.ArgumentException was unhandled
  HResult=-2147024809
  Message=Address contains multiple @ characters. Address supplied: 'Samples.PubSub.MyPublisher@johnpc@JOHNPC2'
Parameter name: address
  ParamName=address
  Source=NServiceBus.Core
  StackTrace:
       at NServiceBus.MsmqAddress.Parse(String address) in C:\Build\src\NServiceBus.Core\Transports\Msmq\MsmqAddress.cs:line 25
       at NServiceBus.MsmqMessageDispatcher.ExecuteTransportOperation(ReadOnlyContextBag context, UnicastTransportOperation transportOperation) in C:\Build\src\NServiceBus.Core\Transports\Msmq\MsmqMessageDispatcher.cs:line 49
       at NServiceBus.MsmqMessageDispatcher.Dispatch(TransportOperations outgoingMessages, ContextBag context) in C:\Build\src\NServiceBus.Core\Transports\Msmq\MsmqMessageDispatcher.cs:line 36
       at NServiceBus.MessageDrivenSubscribeTerminator.<SendSubscribeMessageWithRetries>d__2.MoveNext() in C:\Build\src\NServiceBus.Core\Routing\MessageDrivenSubscriptions\MessageDrivenSubscribeTerminator.cs:line 56
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
       at NServiceBus.MessageDrivenSubscribeTerminator.<Terminate>d__1.MoveNext() in C:\Build\src\NServiceBus.Core\Routing\MessageDrivenSubscriptions\MessageDrivenSubscribeTerminator.cs:line 47
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
       at NServiceBus.Features.AutoSubscribe.ApplySubscriptions.<OnStart>d__1.MoveNext() in C:\Build\src\NServiceBus.Core\Routing\AutomaticSubscriptions\AutoSubscribe.cs:line 72
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
       at NServiceBus.Features.FeatureActivator.<StartFeatures>d__5.MoveNext() in C:\Build\src\NServiceBus.Core\Features\FeatureActivator.cs:line 71
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
       at NServiceBus.StartableEndpoint.<StartFeatures>d__4.MoveNext() in C:\Build\src\NServiceBus.Core\StartableEndpoint.cs:line 84
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
       at NServiceBus.StartableEndpoint.<Start>d__1.MoveNext() in C:\Build\src\NServiceBus.Core\StartableEndpoint.cs:line 44
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
       at NServiceBus.Endpoint.<Start>d__1.MoveNext() in C:\Build\src\NServiceBus.Core\Endpoint.cs:line 28
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
       at Program.<AsyncMain>d__1.MoveNext() in C:\Projects\docs.particular.net\samples\pubsub\Core_6\Subscriber1\Program.cs:line 23
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
       at Program.Main() in C:\Projects\docs.particular.net\samples\pubsub\Core_6\Subscriber1\Program.cs:line 10
  InnerException: 

```

**Comment by SzymonPobiega** [comment]
Fixing this as part of making routing RC ready: https://github.com/Particular/NServiceBus/pull/3801

**Comment by SimonCropp** [comment]
@SzymonPobiega shouldnt this be closed now?

**Comment by SzymonPobiega** [comment]
@SimonCropp I wanted to wait until the PR is merged. No closing.
