### ISSUE TITLE
Timeouts are queried after shutdown is initiated

### ISSUE THREAD

**Issue by ramonsmits** [Particular/NServiceBus#4078]
The following log entries seem to suggest that timeouts are queried even though the endpoint instance shutdown is initiated. The following results in a hang when using RavenDB persistence.

```
2016-08-19 17:54:02.0400|INFO|63|NServiceBus.Unicast.UnicastBus|Initiating shutdown.
2016-08-19 17:54:02.0400|DEBUG|63|NServiceBus.Unicast.UnicastBus|Stopping Main receiver
2016-08-19 17:54:02.0400|DEBUG|63|Host.Program|FirstChanceException
System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
2016-08-19 17:54:02.0400|DEBUG|63|Host.Program|FirstChanceException
System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at System.Threading.SemaphoreSlim.<WaitUntilCountOrTimeoutAsync>d__31.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
2016-08-19 17:54:02.0400|DEBUG|63|Host.Program|FirstChanceException
System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at System.Threading.SemaphoreSlim.<WaitUntilCountOrTimeoutAsync>d__31.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.MessagePump.<InnerProcessMessages>d__6.MoveNext() in C:\Build\src\NServiceBus.Core\Transports\Msmq\MessagePump.cs:line 148
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
2016-08-19 17:54:02.0545|DEBUG|63|NServiceBus.Unicast.UnicastBus|Stopping Timeout Message Processor receiver
2016-08-19 17:54:02.0545|DEBUG|63|NServiceBus.Unicast.UnicastBus|Stopping Timeout Dispatcher Processor receiver
2016-08-19 17:54:02.0545|DEBUG|31|NServiceBus.Unicast.UnicastBus|Stopped Timeout Message Processor receiver
2016-08-19 17:54:02.0545|DEBUG|7|NServiceBus.Unicast.UnicastBus|Stopped Timeout Dispatcher Processor receiver
2016-08-19 17:54:55.0322|DEBUG|126|NServiceBus.ExpiredTimeoutsPoller|Polling for timeouts at 08/19/2016 15:54:55.
```

**Comment by andreasohlund** [comment]
@DavidBoike is #4079 and #272 going to address this?

**Comment by DavidBoike** [comment]
@andreasohlund That's the intention but I have no proof it will fix it. It's based only on an assumption.

**Comment by andreasohlund** [comment]
PR merged, @ramonsmits can you see if this fixed it?

https://builds.particular.net/viewLog.html?buildId=182601&tab=buildResultsDiv&buildTypeId=NServiceBusCore_Build

**Comment by ramonsmits** [comment]
@andreasohlund I'll run the same scenario again (v6 perf test with ravendb) and see it any of those runs show this behavior.

**Comment by danielmarbach** [comment]
@ramonsmits any updates on this?

**Comment by danielmarbach** [comment]
ping @ramonsmits

**Comment by ramonsmits** [comment]
I've run the same test a number of times but could not reproduce it on beta 7. It's a race condition so its super hard to trigger that at shutdown. Any ideas on how to force the race condition?

**Comment by ramonsmits** [comment]
Using the Beta8 package from Myget resulted in the following shutdown sequence:

```
2016-09-02 09:06:26.1651|INFO|58|NServiceBus.Unicast.UnicastBus|Initiating shutdown.
2016-09-02 09:06:26.1651|DEBUG|58|NServiceBus.Unicast.UnicastBus|Stopping Main receiver
2016-09-02 09:06:26.1651|DEBUG|58|FirstChanceException|The operation was canceled.
System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
2016-09-02 09:06:26.1651|DEBUG|58|FirstChanceException|The operation was canceled.
System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at System.Threading.SemaphoreSlim.<WaitUntilCountOrTimeoutAsync>d__31.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
2016-09-02 09:06:26.1815|DEBUG|58|FirstChanceException|The operation was canceled.
System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at System.Threading.SemaphoreSlim.<WaitUntilCountOrTimeoutAsync>d__31.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.MessagePump.<InnerProcessMessages>d__6.MoveNext() in C:\Build\src\NServiceBus.Core\Transports\Msmq\MessagePump.cs:line 148
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
2016-09-02 09:06:26.1815|DEBUG|58|NServiceBus.Unicast.UnicastBus|Stopping Timeout Message Processor receiver
2016-09-02 09:06:26.1815|DEBUG|58|NServiceBus.Unicast.UnicastBus|Stopping Timeout Dispatcher Processor receiver
2016-09-02 09:06:26.1815|DEBUG|6|NServiceBus.Unicast.UnicastBus|Stopped Timeout Dispatcher Processor receiver
2016-09-02 09:06:26.1815|DEBUG|9|NServiceBus.Unicast.UnicastBus|Stopped Timeout Message Processor receiver
2016-09-02 09:06:56.1979|ERROR|42|NServiceBus.ReceiveWithNativeTransaction|The message pump failed to stop with in the time allowed(30s)
2016-09-02 09:06:56.1979|DEBUG|42|NServiceBus.Unicast.UnicastBus|Stopped Main receiver
2016-09-02 09:06:56.1979|DEBUG|42|FirstChanceException|A task was canceled.
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
2016-09-02 09:06:56.1979|DEBUG|42|FirstChanceException|A task was canceled.
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.ExpiredTimeoutsPoller.<InnerPoll>d__10.MoveNext() in C:\Build\src\NServiceBus.Core\DelayedDelivery\TimeoutManager\ExpiredTimeoutsPoller.cs:line 86
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
2016-09-02 09:06:56.1979|DEBUG|42|FirstChanceException|A task was canceled.
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
```

I don't know if this is the expected sequence but I think the following is suspicious:

> NServiceBus.ExpiredTimeoutsPoller.<InnerPoll>d__10.MoveNext() in C:\Build\src\NServiceBus.Core\DelayedDelivery\TimeoutManager\ExpiredTimeoutsPoller.cs:line 86

That seems to suggest that the timeout iteration is cancelled. I think that should not happen. Poller loop should stop looping but it should not abort an in progress timeout task.

**Comment by timbussmann** [comment]
it doesn't look very suspicious to me. Looking at the implementation, it seems to be fine to abort the delay. Does somebody feel that we need to dig deeper or can we close this?

**Comment by danielmarbach** [comment]
The stack trace shown shows the cancellation of Task.Delay happening https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/DelayedDelivery/TimeoutManager/ExpiredTimeoutsPoller.cs#L86 that is expected. @ramonsmits are you talking about this instead https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/DelayedDelivery/TimeoutManager/ExpiredTimeoutsPoller.cs#L102 ?

Closing since the description hints at line 86. If anything else is needed we can raise a new issue
