### ISSUE TITLE
NServiceBus.ExceptionInfo.Message	An error occurred while attempting to extract logical messages from transport message NServiceBus.TransportMessage

### ISSUE THREAD

**Issue by hnanchahal** [Particular/NServiceBus#4080]
I am receiving de-serialization messages on handing eventns from particular.ServiceControl.

**Headers:**

NServiceBus.MessageId	666faf48-0c44-4109-beb6-a66a009c8c93
NServiceBus.CorrelationId	bf397ea0-6aaa-4c7f-ba2c-a66a009c8c93
NServiceBus.MessageIntent	Publish
NServiceBus.Version	5.2.10
NServiceBus.TimeSent	2016-08-22 16:29:58:673549 Z
NServiceBus.ContentType	application/json
NServiceBus.EnclosedMessageTypes	ServiceControl.Contracts.MessageFailed, ServiceControl.Contracts, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
CorrId	666faf48-0c44-4109-beb6-a66a009c8c93\0
NServiceBus.ConversationId	68a1e495-d47a-4eef-8a96-a66a009c8c93
WinIdName	NT AUTHORITY\SYSTEM
NServiceBus.OriginatingMachine	MS10582
NServiceBus.OriginatingEndpoint	Particular.ServiceControl
NServiceBus.ReplyToAddress	Particular.ServiceControl@MS10582
NServiceBus.ExceptionInfo.ExceptionType	System.Runtime.Serialization.SerializationException
NServiceBus.ExceptionInfo.InnerExceptionType	System.Exception

Stack Trace:

at NServiceBus.DeserializeLogicalMessagesBehavior.Invoke(IncomingContext context, Action next) in c:\BuildAgent\work\1b05a2fea6e4cd32\src\NServiceBus.Core\Unicast\Messages\DeserializeLogicalMessagesBehavior.cs:line 49
   at NServiceBus.CallbackInvocationBehavior.Invoke(IncomingContext context, Action next) in c:\BuildAgent\work\1b05a2fea6e4cd32\src\NServiceBus.Core\Unicast\Behaviors\CallbackInvocationBehavior.cs:line 23
   at NServiceBus.ApplyIncomingTransportMessageMutatorsBehavior.Invoke(IncomingContext context, Action next) in c:\BuildAgent\work\1b05a2fea6e4cd32\src\NServiceBus.Core\MessageMutator\ApplyIncomingTransportMessageMutatorsBehavior.cs:line 20
   at NServiceBus.SubscriptionReceiverBehavior.Invoke(IncomingContext context, Action next) in c:\BuildAgent\work\1b05a2fea6e4cd32\src\NServiceBus.Core\Unicast\Subscriptions\MessageDrivenSubscriptions\SubscriptionReceiverBehavior.cs:line 32
   at NServiceBus.UnitOfWorkBehavior.Invoke(IncomingContext context, Action next) in c:\BuildAgent\work\1b05a2fea6e4cd32\src\NServiceBus.Core\UnitOfWork\UnitOfWorkBehavior.cs:line 43
   at NServiceBus.ChildContainerBehavior.Invoke(IncomingContext context, Action next) in c:\BuildAgent\work\1b05a2fea6e4cd32\src\NServiceBus.Core\Unicast\Behaviors\ChildContainerBehavior.cs:line 17
   at NServiceBus.ProcessingStatisticsBehavior.Invoke(IncomingContext context, Action next) in c:\BuildAgent\work\1b05a2fea6e4cd32\src\NServiceBus.Core\Monitoring\ProcessingStatisticsBehavior.cs:line 23
   at NServiceBus.AuditBehavior.Invoke(IncomingContext context, Action next) in c:\BuildAgent\work\1b05a2fea6e4cd32\src\NServiceBus.Core\Audit\AuditBehavior.cs:line 20
   at NServiceBus.Pipeline.PipelineExecutor.Execute[T](BehaviorChain`1 pipelineAction, T context) in c:\BuildAgent\work\1b05a2fea6e4cd32\src\NServiceBus.Core\Pipeline\PipelineExecutor.cs:line 127
   at NServiceBus.Unicast.Transport.TransportReceiver.ProcessMessage(TransportMessage message) in c:\BuildAgent\work\1b05a2fea6e4cd32\src\

**Comment by andreasohlund** [comment]
Hi @hnanchahal sorry for the delay.

Can you verify that you have the conventions setup correctly:

http://docs.particular.net/servicecontrol/contracts#custom-notification-and-alerting-using-servicecontrol-events-subscribing-to-servicecontrol-events

Also is your endpoint configured to use the jsonserializer?(XML is the default)

http://docs.particular.net/nservicebus/serialization/

**Comment by hnanchahal** [comment]
Here is the configuration for Serialization:

public class EndpointConfig : IConfigureThisEndpoint, AsA_Server
    {
        public void Customize(BusConfiguration configuration)
        {
            var builder = new ContainerBuilder();

            configuration.UseSerialization<JsonSerializer>();

![image](https://cloud.githubusercontent.com/assets/16055046/18062029/e897fadc-6dd9-11e6-9524-319d6809650d.png)

 <UnicastBusConfig>
    <MessageEndpointMappings>
      <add Messages="ServiceControl.Contracts" Endpoint="Particular.ServiceControl@ms10582" />
    </MessageEndpointMappings>
  </UnicastBusConfig>

Using a 5.0.0.0 version of NServicebus.

**Comment by andreasohlund** [comment]
Do you have 

```
var conventions = busConfiguration.Conventions();
conventions.DefiningEventsAs(type =>
{
    return typeof(IEvent).IsAssignableFrom(type) ||
           // include ServiceControl events
           type.Namespace != null &&
           type.Namespace.StartsWith("ServiceControl.Contracts");
});
```

or similar in there as well?

**Comment by hnanchahal** [comment]
While investigating the errors in ServiceInsight, i do see the messages that i am expecting in the Body of the failed messages but i see the exception in the headers:

![image](https://cloud.githubusercontent.com/assets/16055046/18063771/38b1e26a-6de1-11e6-846e-99e113feacb9.png)

**Comment by hnanchahal** [comment]
here is my complete configuration:

 public void Customize(BusConfiguration configuration)
        {
            var builder = new ContainerBuilder();

            configuration.UseSerialization<JsonSerializer>();

            configuration.Conventions()
                .DefiningEventsAs(t => typeof(IEvent).IsAssignableFrom(t) || IsServiceControlContract(t));

            configuration.UsePersistence<InMemoryPersistence>();
            configuration.ConfigureSerilogLogging();
            configuration.AssembliesToScan(AllAssemblies.Matching("Starbucks.NsbAudit."));
            var container = builder.Build();
        }

        private static bool IsServiceControlContract(Type t)
        {
            return t.Namespace != null && t.Namespace.StartsWith("ServiceControl.Contracts");
        }

**Comment by andreasohlund** [comment]
>configuration.AssembliesToScan(AllAssemblies.Matching("Starbucks.NsbAudit."));

That line would mean that the contracts dll won't get included in scanning, can you try to remove it?

http://docs.particular.net/nservicebus/hosting/assembly-scanning

**Comment by hnanchahal** [comment]
Perfect! That did the trick. Thanks a lot for helping on this.

**Comment by andreasohlund** [comment]
Glad you got it working @hnanchahal just reach out if you have any other issues!
