### ISSUE TITLE
MessageMapper throws exception when Message contains an Exception Property

### ISSUE THREAD

**Issue by ppittle** [Particular/NServiceBus#4101]
`<package id="NServiceBus" version="6.0.0-beta0004" targetFramework="net452" />`

I have a message class like:

    public class SomethingWentWrongMessage : IMessage
    {
          public Exception ThingThatBroke {get;set;}
    }

When starting an Endpoint, I get an exception:

```
We can only generate a concrete implementation for 'ICustomAttributeProvider' 
because the interface contains methods. Make sure interface messages do not contain methods.    
at NServiceBus.MessageInterfaces.MessageMapper.Reflection.MessageMapper.GenerateImplementationFor(Type interfaceType) in C:\Build\src\NServiceBus.Core\MessageInterfaces\MessageMapper\Reflection\MessageMapper.cs:line 222
   at NServiceBus.MessageInterfaces.MessageMapper.Reflection.MessageMapper.InitType(Type t) in C:\Build\src\NServiceBus.Core\MessageInterfaces\MessageMapper\Reflection\MessageMapper.cs:line 186
   at NServiceBus.MessageInterfaces.MessageMapper.Reflection.MessageMapper.InitType(Type t) in C:\Build\src\NServiceBus.Core\MessageInterfaces\MessageMapper\Reflection\MessageMapper.cs:line 207
   at NServiceBus.MessageInterfaces.MessageMapper.Reflection.MessageMapper.InitType(Type t) in C:\Build\src\NServiceBus.Core\MessageInterfaces\MessageMapper\Reflection\MessageMapper.cs:line 207
   at NServiceBus.MessageInterfaces.MessageMapper.Reflection.MessageMapper.InitType(Type t) in C:\Build\src\NServiceBus.Core\MessageInterfaces\MessageMapper\Reflection\MessageMapper.cs:line 207
   at NServiceBus.MessageInterfaces.MessageMapper.Reflection.MessageMapper.InitType(Type t) in C:\Build\src\NServiceBus.Core\MessageInterfaces\MessageMapper\Reflection\MessageMapper.cs:line 207
   at NServiceBus.MessageInterfaces.MessageMapper.Reflection.MessageMapper.InitType(Type t) in C:\Build\src\NServiceBus.Core\MessageInterfaces\MessageMapper\Reflection\MessageMapper.cs:line 207
   at NServiceBus.MessageInterfaces.MessageMapper.Reflection.MessageMapper.InitType(Type t) in C:\Build\src\NServiceBus.Core\MessageInterfaces\MessageMapper\Reflection\MessageMapper.cs:line 207
   at NServiceBus.MessageInterfaces.MessageMapper.Reflection.MessageMapper.InitType(Type t) in C:\Build\src\NServiceBus.Core\MessageInterfaces\MessageMapper\Reflection\MessageMapper.cs:line 207
   at NServiceBus.MessageInterfaces.MessageMapper.Reflection.MessageMapper.Initialize(IEnumerable`1 types) in C:\Build\src\NServiceBus.Core\MessageInterfaces\MessageMapper\Reflection\MessageMapper.cs:line 36
   at NServiceBus.SerializationFeature.Setup(FeatureConfigurationContext context) in C:\Build\src\NServiceBus.Core\Serialization\SerializationFeature.cs:line 30
   at NServiceBus.Features.Feature.SetupFeature(FeatureConfigurationContext config) in C:\Build\src\NServiceBus.Core\Features\Feature.cs:line 204
   at NServiceBus.Features.FeatureActivator.ActivateFeature(FeatureInfo featureInfo, List`1 featuresToActivate, IConfigureComponents container, PipelineSettings pipelineSettings) in C:\Build\src\NServiceBus.Core\Features\FeatureActivator.cs:line 195
   at NServiceBus.Features.FeatureActivator.SetupFeatures(IConfigureComponents container, PipelineSettings pipelineSettings) in C:\Build\src\NServiceBus.Core\Features\FeatureActivator.cs:line 59
   at NServiceBus.InitializableEndpoint.Initialize() in C:\Build\src\NServiceBus.Core\InitializableEndpoint.cs:line 48
   at NServiceBus.Endpoint.Create(EndpointConfiguration configuration) in C:\Build\src\NServiceBus.Core\Endpoint.cs:line 17
```

**a)** Is this by design?  Is there a limitation against having `Exception` in an `IMessage`?
**b)** Don't think the wording of the error message is correct "We **can only generate a concrete implementation** for 'ICustomAttributeProvider' because the interface contains methods"

**Comment by danielmarbach** [comment]
@ppittle thanks for bringing it up. @bording will look into it. Poor soul ;)

**Comment by ppittle** [comment]
@danielmarbach, @bording  - Any insights into when Particular will cut new nuget packages and up them to nuget.org?  And will this fix be in time for the next beta release?

**Comment by bording** [comment]
@ppittle Still not sure on timing, but from my investigations so far, I can see that the reason it is failing is that that our `MessageMapper` class is digging into all the properties of the `Exception` class, and `ICustomAttributeProvider` is in there somewhere, and the interface has methods on it, which is the reason for the error message you're seeing.

I'm still trying to determine what sort of changes we can make to the `MessageMapper` class to enable this without breaking some other scenarios.

That being said, even if we do make a change to the `MessageMapper`, it looks like the XML serializer does not support serializing `Exception`, because most of its properties are get-only. The json serializer seems to handle it ok, though.

**Comment by andreasohlund** [comment]
@ppittle are you still stuck here?

would it be an option to change your message contract to avoid using the `Exception` type, tying your contract to type you don't control is in general a bad idea from a versioning perspective. 

Another option would be to serialize the Exception explicitly on the sender side, eg too json, and transfer it as a `public string Exception` on the message?

**Comment by andreasohlund** [comment]
@bording this is an issue in v5 as well right?

**Comment by ppittle** [comment]
@andreasohlund I'll treat the Property as an `object` for now.  But I'd prefer to use `Exception`.  Once you guys have a fix out I'll switch back.

**Comment by bording** [comment]
@andreasohlund Just ran a quick test, and v5 logs a warning:

`WARN  NServiceBus.MessageInterfaces.MessageMapper.Reflection.MessageMapper Interface ICustomAttributeProvider contains methods and can there for not be mapped. Be aware that non mapped interface can't be used to send messages.`

But you can the message type can still be used because it's not an interface. If I use the XML serializer, the `Exception` property isn't serialized properly because of all the get-only properties on the type.

However, if I switch to the JSON serializer instead, everything works correctly despite the warning. I can send and receive the message, and the Exception is serialized correctly.

So, the exception we're throwing here that shuts down the endpoint on startup does appear to be new to v6!

**Comment by andreasohlund** [comment]
See https://github.com/Particular/NServiceBus/pull/4108#issuecomment-246932775 for a proposed fix

**Comment by MpDzik** [comment]
I encountered the same problem when a message contains a property of `System.Type` type. This worked properly 5.2.x and stopped working in 6.0.

**Comment by andreasohlund** [comment]
We've merged a fix https://github.com/Particular/NServiceBus/pull/4133, it will be included in the upcoming RTM.

@MpDzik @ppittle are you blocked by this atm?

**Comment by MpDzik** [comment]
@andreasohlund I'm not really blocked, as I'm still using NServiceBus 5.2.16 on production. I found this problem while migrating my applications to NServiceBus 6. If this issue is fixed in RTM then this is perfectly fine for me.
