### ISSUE TITLE
Acpt test: When_pump_throws_on_stop is flaky

### ISSUE THREAD

**Issue by andreasohlund** [Particular/NServiceBus#4387]
It fails now and then on the build server (see details below)

https://builds.particular.net/viewLog.html?buildId=201639&tab=buildResultsDiv&buildTypeId=NServiceBusCore_Build

<details>
  Expected: String containing "Receiver Main listening to queue PumpThrowsOnStop.EndpointThatThrowsOnPumpStop threw an exception on stopping. System.InvalidOperationException: ExceptionInPumpStop"
  But was:  "Receiver Legacy Retries Processor listening to queue PumpThrowsOnStop.EndpointThatThrowsOnPumpStop.Retries threw an exception on stopping. System.InvalidOperationException: ExceptionInPumpStop
   at NServiceBus.AcceptanceTests.Core.FakeTransport.FakeReceiver.<Stop>d__3.MoveNext() in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.AcceptanceTests\Core\FakeTransport\FakeReceiver.cs:line 32
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.TransportReceiver.<Stop>d__6.MoveNext() in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Transports\TransportReceiver.cs:line 59"

at NServiceBus.AcceptanceTests.Core.Stopping.When_pump_throws_on_stop.<Should_log_exception>d__0.MoveNext() in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.AcceptanceTests\Core\Stopping\When_pump_throws_on_stop.cs:line 23
--- End of stack trace from previous location where exception was thrown ---
at NUnit.Framework.Internal.ExceptionHelper.Rethrow(Exception exception)
at NUnit.Framework.Internal.AsyncInvocationRegion.AsyncTaskInvocationRegion.WaitForPendingOperationsToComplete(Object invocationResult)
at NUnit.Framework.Internal.Commands.TestMethodCommand.RunAsyncTestMethod(TestExecutionContext context)

------- Stdout: -------
MsmqTransport - Started @ 12/12/2016 13:18:24
Stopping endpoint: PumpThrowsOnStop.EndpointThatThrowsOnPumpStop
Endpoint: PumpThrowsOnStop.EndpointThatThrowsOnPumpStop stopped (00:00:00.0041140s)
MsmqTransport - Finished @ 12/12/2016 13:18:24
------------------------------------------------------
Test summary for: MsmqTransport

Using settings:
   Transport.ConnectionString: cacheSendConnection=false;journal=false;
   Persistence: NServiceBus.InMemoryPersistence
   ConfigureTestExecution.PumpThrowsOnStop.EndpointThatThrowsOnPumpStop: ConfigureEndpointMsmqTransport; ConfigureEndpointInMemoryPersistence
   Transport: NServiceBus.MsmqTransport

Endpoints:
     - PumpThrowsOnStop.EndpointThatThrowsOnPumpStop
Result: Successful - Duration: 00:00:00.0701836

Context:
TestRunId = 5bb19c69-6b79-4d95-9dc3-9ea6f9613c88
EndpointsStarted = True
HasNativePubSubSupport = False

Trace:

------------------------------------------------------
Total time for testrun: 00:00:00.0702938
</details>

**Comment by timbussmann** [comment]
I'll have a look into this
