### ISSUE TITLE
MSMQ: When configuring a remote error queue, API throws a misleading warning

### ISSUE THREAD

**Issue by indualagarsamy** [Particular/NServiceBus#4517]
When configuring the error queue and providing a centralized remote machine address, either FQDN or just the machine name, the endpoint provides the following log:

```
2017-03-01 05:23:35.430 INFO  NServiceBus.MsmqQueueCreator 'error@dpc2.testdomain.local' is a remote queue and won't be created
...
2017-03-01 05:23:35.545 WARN  NServiceBus.QueuePermissions Unable to verify remote queue 'dpc2.testdomain.local\private$\error'. Make sure the queue exists, and that the address is correct. Processing will still continue.
System.Messaging.MessageQueueException (0x80004005): Invalid queue path name.
   at System.Messaging.MessageQueue.ResolveFormatNameFromQueuePath(String queuePath, Boolean throwException)
   at System.Messaging.MessageQueue.Exists(String path)
   at NServiceBus.QueuePermissions.CheckQueue(String address) in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Transports\Msmq\QueuePermissions.cs:line 22
```

The INFO clearly states that the remote queue won't be created. However, there is also a WARN logged, which is misleading, as it also shows an exception. 

Discussed this with @HEskandari and @gbiellem and we think this is a bug and needs to be fixed. 
We propose the following:
Just log, one WARN (without the exception), stating that, "Make sure the queue exists, and that the address is correct as we cannot verify the remote queue. Processing of messages in this endpoint will still continue."
---

Customer Case: 00025177

**Comment by andreasohlund** [comment]
What core version is this? (I have a hunch that we've fixed this recently)

**Comment by indualagarsamy** [comment]
@andreasohlund - 6.1.3

**Comment by indualagarsamy** [comment]
@andreasohlund - I looked at the develop branch, we log the WARN with the exception:
https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/Transports/Msmq/QueuePermissions.cs#L34-L37

**Comment by andreasohlund** [comment]
yea, I though https://github.com/Particular/NServiceBus/pull/4366 fixed this but you're correct

How about we long a plain INFO without the exception stating that we couldn't check permissions since its remote?

That would mean that:

### If installers are enabled: 

* We log info that we can't create/make sure it exists since its remote
* We log info that we can't check that the queue has appropriate permissions since its remote


### If installers are not enabled

* We log info that we can't check that the queue has appropriate permissions since its remote

Thoughts?

**Comment by danielmarbach** [comment]
I'm good with log info and removing the exception because I agree it is not actually something you want to see the exception details

**Comment by indualagarsamy** [comment]
I think it should be a WARN and not INFO. People filter our INFO in deployments and this is saying that we don't check remote queues to see if they exist and that the users should make sure config is correct. Otherwise error messages might be ending up in DLQ without the user being aware.

**Comment by andreasohlund** [comment]
>I think it should be a WARN and not INFO. People filter our INFO in deployments and this is saying that we don't check remote queues to see if they exist and that the users should make sure config is correct. Otherwise error messages might be ending up in DLQ without the user being aware

Permissions on remote queues can't be checked unless the service account is domain admin. 

Given this and that error and audit is very likely to be remote you will have a WARN log on each startup?

Perhaps we shouldn't even try to check permissions on remote queues since its unlikely to work anyway?

**Comment by indualagarsamy** [comment]
@andreasohlund - I agree. It makes no sense to check for remote queue permissions. I see your point about the warn log on every startup. However, consider this scenario. There's a misconfiguration. Messages are going to TDLQ, but the user isn't aware and they look at the logs on the prod server and there's nothing, because INFO is filtered. It makes troubleshooting a little harder. No one looks at the logs unless there's an issue and in this case, as long as we make the wording very clear, it can be a warning. Just without the exception stack trace, as that makes it look like there's something wrong most definitely.


Sent from my iPhone

**Comment by andreasohlund** [comment]
Not checking remote queues seems to fix all this?

In short we would only log a info saying queue is remote so we are not able to check.

If local and fails we log just like we do today?

**Comment by indualagarsamy** [comment]
Discussed with @andreasohlund. Logging INFO rather than warning makes sense.

Sent from my iPhone
