### ISSUE TITLE
Acceptance tests has problems deserializing jsons

### ISSUE THREAD

**Issue by pablocastilla** [Particular/NServiceBus#4554]
Hi!

I don't know if I am doing something wrong in the kafka transport, but when I execute acceptance tests I have some failures which I think are not in my side (but I am not sure about this).

For instance: Should_start_the_saga_and_request_a_timeout and others gave me the following exception:

Activated	Event	Time	Duration	Thread
	error onMessage: NServiceBus.MessageDeserializationException: An error occurred while attempting to extract logical messages from transport message 72131697-09ef-4a76-b3f5-a738008312b8 ---> Newtonsoft.Json.JsonSerializationException: Could not create an instance of type NServiceBus.AcceptanceTests.Sagas.When_started_by_base_event_from_other_saga+SomethingHappenedEvent. Type is an interface or abstract class and cannot be instantiated. Path 'DataId', line 1, position 10.
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateNewObject(JsonReader reader, JsonObjectContract objectContract, JsonProperty containerMember, JsonProperty containerProperty, String id, Boolean& createdFromNonDefaultCreator) in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Transports\MessageContext.cs:line 0
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue) in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Transports\MessageContext.cs:line 0
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue) in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Transports\MessageContext.cs:line 0
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent) in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Transports\MessageContext.cs:line 0
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType) in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Transports\MessageContext.cs:line 0
   at NServiceBus.JsonMessageSerializer.<>c__DisplayClass6_0.<Deserialize>b__0(Type x) in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Serializers\Json\JsonMessageSerializer.cs:line 124
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at NServiceBus.JsonMessageSerializer.Deserialize(Stream stream, IList`1 messageTypes) in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Serializers\Json\JsonMessageSerializer.cs:line 115
   at NServiceBus.DeserializeLogicalMessagesConnector.Extract(IncomingMessage physicalMessage) in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Pipeline\Incoming\DeserializeLogicalMessagesConnector.cs:line 115
   at NServiceBus.DeserializeLogicalMessagesConnector.ExtractWithExceptionHandling(IncomingMessage message) in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Pipeline\Incoming\DeserializeLogicalMessagesConnector.cs:line 44
   --- End of inner exception stack trace ---
   at NServiceBus.DeserializeLogicalMessagesConnector.ExtractWithExceptionHandling(IncomingMessage message) in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Pipeline\Incoming\DeserializeLogicalMessagesConnector.cs:line 48
   at NServiceBus.DeserializeLogicalMessagesConnector.<Invoke>d__1.MoveNext() in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Pipeline\Incoming\DeserializeLogicalMessagesConnector.cs:line 27
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.InvokeAuditPipelineBehavior.<Invoke>d__1.MoveNext() in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Audit\InvokeAuditPipelineBehavior.cs:line 18
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.ProcessingStatisticsBehavior.<Invoke>d__0.MoveNext() in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Performance\Statistics\ProcessingStatisticsBehavior.cs:line 27
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.ReceivePerformanceDiagnosticsBehavior.<Invoke>d__2.MoveNext() in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Performance\Statistics\ReceivePerformanceDiagnosticsBehavior.cs:line 40
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.TransportReceiveToPhysicalMessageProcessingConnector.<Invoke>d__1.MoveNext() in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Pipeline\Incoming\TransportReceiveToPhysicalMessageProcessingConnector.cs:line 37
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.AcceptanceTesting.Support.FailTestOnErrorMessageFeature.CaptureExceptionBehavior.<Invoke>d__1.MoveNext() in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.AcceptanceTesting\Support\FailTestOnErrorMessageFeature.cs:line 59
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.MainPipelineExecutor.<Invoke>d__1.MoveNext() in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Pipeline\MainPipelineExecutor.cs:line 32
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at NServiceBus.Transports.Kafka.Connection.ConsumerHolder.<Process>d__35.MoveNext() in C:\Users\sesa221523\Source\Repos\NServiceBus.Kafka\src\NServiceBus.Kafka\Connection\ConsumerHolder.cs:line 380	10.51s

**Comment by timbussmann** [comment]
hey @pablocastilla 

I tried to switch this test to use the JSON serializer and it works fine for me. Do you have a repro I can have a look at?

**Comment by timbussmann** [comment]
hey @pablocastilla , any updates on this issue?

**Comment by pablocastilla** [comment]
It is strange, sometimes it fails and sometimes it doesn't fail. I think you can close at this moment. I will reopen it if I find something.

Thanks so much

**Comment by timbussmann** [comment]
will close this for now then. Happy to reopen this if you find a way to reproduce the issue so we can have a closer look at this.
