### ISSUE TITLE
Constantly throwing transaction exceptions

### ISSUE THREAD

**Issue by dasjestyr** [Particular/NServiceBus#4608]
So I have a process that issues a few thousand commands to the bus and I'm not getting errors during that part. While I'm waiting for the handler for that command to pick up and hit a break point (which it never does), NSB is emitting and exception that indicates that a connection has not been disposed and/or it's causing some conflict with the transaction. A couple other things I noticed is that, while a few thousand command were issued, the table/queue only contains one or two. Here is the exception

```
System.Exception: Failed to send message to [dbo].[DAS.Services.Reviews] ---> System.InvalidOperationException: The transaction associated with the current connection has completed but has not been disposed.  The transaction must be disposed before the connection can be used to execute SQL statements.
   at System.Data.SqlClient.TdsParser.TdsExecuteRPC(SqlCommand cmd, _SqlRPC[] rpcArray, Int32 timeout, Boolean inSchema, SqlNotificationRequest notificationRequest, TdsParserStateObject stateObj, Boolean isCommandProc, Boolean sync, TaskCompletionSource`1 completion, Int32 startRpc, Int32 startParam)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   at System.Data.SqlClient.SqlCommand.BeginExecuteNonQueryInternal(CommandBehavior behavior, AsyncCallback callback, Object stateObject, Int32 timeout, Boolean inRetry, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.BeginExecuteNonQueryAsync(AsyncCallback callback, Object stateObject)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncImpl(Func`3 beginMethod, Func`2 endFunction, Action`1 endAction, Object state, TaskCreationOptions creationOptions)
   at System.Threading.Tasks.TaskFactory`1.FromAsync(Func`3 beginMethod, Func`2 endMethod, Object state)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQueryAsync(CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.Transport.SQLServer.TableBasedQueue.<SendRawMessage>d__9.MoveNext() in C:\BuildAgent\work\888dd942b44bad5a\src\NServiceBus.SqlServer\Queuing\TableBasedQueue.cs:line 91
   --- End of inner exception stack trace ---
   at NServiceBus.Transport.SQLServer.TableBasedQueue.ThrowFailedToSendException(Exception ex) in C:\BuildAgent\work\888dd942b44bad5a\src\NServiceBus.SqlServer\Queuing\TableBasedQueue.cs:line 128
   at NServiceBus.Transport.SQLServer.TableBasedQueue.<SendRawMessage>d__9.MoveNext() in C:\BuildAgent\work\888dd942b44bad5a\src\NServiceBus.SqlServer\Queuing\TableBasedQueue.cs:line 103
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.Transport.SQLServer.TableBasedQueueDispatcher.<Send>d__6.MoveNext() in C:\BuildAgent\work\888dd942b44bad5a\src\NServiceBus.SqlServer\Sending\TableBasedQueueDispatcher.cs:line 96
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.Transport.SQLServer.TableBasedQueueDispatcher.<DispatchAsIsolated>d__2.MoveNext() in C:\BuildAgent\work\888dd942b44bad5a\src\NServiceBus.SqlServer\Sending\TableBasedQueueDispatcher.cs:line 27
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.Transport.SQLServer.MessageDispatcher.<Dispatch>d__1.MoveNext() in C:\BuildAgent\work\888dd942b44bad5a\src\NServiceBus.SqlServer\Sending\MessageDispatcher.cs:line 20
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.TransportReceiveToPhysicalMessageProcessingConnector.<Invoke>d__1.MoveNext() in C:\Build\src\NServiceBus.Core\Pipeline\Incoming\TransportReceiveToPhysicalMessageProcessingConnector.cs:line 57
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.MainPipelineExecutor.<Invoke>d__1.MoveNext() in C:\Build\src\NServiceBus.Core\Pipeline\MainPipelineExecutor.cs:line 32
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.Transport.SQLServer.ReceiveStrategy.<TryProcessingMessage>d__12.MoveNext() in C:\BuildAgent\work\888dd942b44bad5a\src\NServiceBus.SqlServer\Receiving\ReceiveStrategy.cs:line 33
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.Transport.SQLServer.ReceiveWithNativeTransaction.<TryProcess>d__4.MoveNext() in C:\BuildAgent\work\888dd942b44bad5a\src\NServiceBus.SqlServer\Receiving\ReceiveWithNativeTransaction.cs:line 112

```

**Comment by timbussmann** [comment]
@dasjestyr as this seems to be an issue with sending messages, can you share that code (or a repro sample) with us? Also, did you make sure to `await` operations properly?

**Comment by dasjestyr** [comment]
Here's how the commands are being issued:

``` csharp
private async Task SpawnIngestionCommands(
  Guid clientId, 
  IMessageHandlerContext context)
{
  // skip vendasta because it works a little differently and is covered in overload
  foreach (var source in _providerFactory.RegisteredSources.Where(source => source != ReviewSource.Vendasta))
  {
      if (await HasBeenRecentlyUpdated(clientId, source).ConfigureAwait(false))
          continue;

      var clientInfo = _reviewConfigCache.ClientConfigurations[clientId];
      if (clientInfo == null)
      {
          Logger.Debug("Could not find any review site configuration for {client}", this, clientId);
          continue; // allow process to continue
      }

      if (!TryGetClientIds(source, clientId, clientInfo, out List<string> apiIds))
      {
          Logger.Debug("Could not find any api Ids for {client}", this, clientId);
          continue; // allow process to continue
      }

      await SendIngestionCommand(clientId, context, source, apiIds).ConfigureAwait(false);
  }
}

private async Task SendIngestionCommand(
  Guid clientId,
  IMessageHandlerContext context,
  ReviewSource source,
  List<string> clientSiteIds)
{
  foreach (var siteId in clientSiteIds)
  {
      var command = new BulkIngestionCommand
      {
          ClientId = clientId,
          ReviewSource = source.ToString(),
          ExternalClientId = siteId,
          RequestDateTime = DateTime.Now
      };
      
      if(_shouldSpawnCommands)
      { 
          await context.SendLocal(command).ConfigureAwait(false);
          Logger.Verbose("Queued ingestion command for client {@Command}.", this, command);
      }
  }
}
```

**Comment by timbussmann** [comment]
@dasjestyr are you just invoking this method from a message handler or is more logic involved there? Are you using the same sql server for business data / queries?

**Comment by dasjestyr** [comment]
This is being invoked from a handler that is handling a different command. Basically CommandA is issued by a scheduler to start spawning these other commands. CommandB is the one pasted above which spawns about 7000 more commands. The sql server is the same server that we're using for business operations, just a separate physical database (nsb_dev.dbo.*). The server isn't under any noteworthy load. 

In the meanwhile (I needed to get it working again), I've switched the transport to Azure Service Bus and no longer have this problem, but now I'm getting the occasional error stating that a lock is being lost which feels like the ASB equivalent to this same issue, so I'd still like to understand what may be causing this.

**Comment by timbussmann** [comment]
@dasjestyr are you opening a new sql server connection and/or transaction somewhere within that handler logic (e.g. in `HasBeenRecentlyUpdated`)?

> but now I'm getting the occasional error stating that a lock is being lost 

This sounds like the message handling code takes longer than the default message lock (which sounds reasonable when sending 7000 messages).

**Comment by dasjestyr** [comment]
Nope. SQL is only being use for the bus and nothing else. The lock errors are curious because the lock life is like a minute and a half. And I get those errors within the first few seconds.

**Comment by timbussmann** [comment]
@Particular/sqlserver-transport-maintainers can you help us out here?

**Comment by MarcinHoppe** [comment]
@timbussmann See https://github.com/Particular/NServiceBus.SqlServer/issues/359#issuecomment-296741735.

**Comment by timbussmann** [comment]
I guess it makes sense to not have the same issue in two repos. As this seems to belong to sql transport, are you good with me closing this issue in favor of https://github.com/Particular/NServiceBus.SqlServer/issues/359 (and reopen this in case some further steps are required) @dasjestyr @Particular/sqlserver-transport-maintainers ?

**Comment by timbussmann** [comment]
closing this then. Please feel free to comment on https://github.com/Particular/NServiceBus.SqlServer/issues/359 to further discuss this issue. I'll leave it to @Particular/sqlserver-transport-maintainers whether they want to investigate this further or not.
