### ISSUE TITLE
MSMQ queue permissions created by NSB Host installer cause warning when running the Host

### ISSUE THREAD

**Issue by agross** [Particular/NServiceBus#4735]
Hi, 

I upgraded from NSB5/Host 6 to NSB6/Host 7 this week. After the upgrade the host issued a warning that the MSMQ queue permissions are not ideal for production.

I tried deleting the queues on a test system so that the installer would recreate them, but the error persists.

Versions of NSB used (`paket.lock` file):

    NServiceBus (6.3)
    NServiceBus.Host (7.0.1)
      NServiceBus (>= 6.0 < 7.0)
    NServiceBus.Log4Net (2.0)
      log4net (>= 2.0 < 3.0)
      NServiceBus (>= 6.0 < 7.0)

Installer:
```powershell
Exec {
  & .\bin\NServiceBus.Host.exe `
    -install `
    "-serviceName=does-not-matter" `
    "-username=NetworkService" `
    '-password=""'
} 
```

NSB log (installer part):
```
2017-05-23 13:25:39,372 [        1] DEBUG rviceBus.MsmqQueueCreator - Creating 'GROSSWEBER.qa.ops.Timeouts@TRITON1026' if needed.
2017-05-23 13:25:39,466 [        1] DEBUG rviceBus.MsmqQueueCreator - Created queue, path: [TRITON1026\private$\GROSSWEBER.qa.ops.Timeouts], identity: [NT AUTHORITY\NETWORK SERVICE], transactional: [True]
2017-05-23 13:25:39,731 [        1] DEBUG rviceBus.MsmqQueueCreator - Creating 'GROSSWEBER.qa.ops.TimeoutsDispatcher@TRITON1026' if needed.
2017-05-23 13:25:39,762 [        1] DEBUG rviceBus.MsmqQueueCreator - Created queue, path: [TRITON1026\private$\GROSSWEBER.qa.ops.TimeoutsDispatcher], identity: [NT AUTHORITY\NETWORK SERVICE], transactional: [True]
2017-05-23 13:25:40,012 [        1] DEBUG rviceBus.MsmqQueueCreator - Creating 'GROSSWEBER.qa.ops.Retries@TRITON1026' if needed.
2017-05-23 13:25:40,043 [        1] DEBUG rviceBus.MsmqQueueCreator - Created queue, path: [TRITON1026\private$\GROSSWEBER.qa.ops.Retries], identity: [NT AUTHORITY\NETWORK SERVICE], transactional: [True]
2017-05-23 13:25:40,246 [        1] DEBUG rviceBus.MsmqQueueCreator - Creating 'GROSSWEBER.qa.ops@TRITON1026' if needed.
2017-05-23 13:25:40,292 [        1] DEBUG rviceBus.MsmqQueueCreator - Created queue, path: [TRITON1026\private$\GROSSWEBER.qa.ops], identity: [NT AUTHORITY\NETWORK SERVICE], transactional: [True]
2017-05-23 13:25:40,511 [        1] DEBUG rviceBus.MsmqQueueCreator - Creating 'GROSSWEBER.qa.errors@localhost' if needed.
```

NSB logs (runtime part):
```
2017-05-23 13:25:49,498 [        4] DEBUG iceBus.ErrorQueueSettings - Error queue retrieved from code configuration via 'EndpointConfiguration.SendFailedMessagesTo()'.
2017-05-23 13:25:49,686 [        4] DEBUG rviceBus.QueuePermissions - Checking if queue exists: TRITON1026\private$\GROSSWEBER.qa.errors.
2017-05-23 13:25:49,686 [        4] DEBUG rviceBus.QueuePermissions - Verified that the queue: [TRITON1026\private$\GROSSWEBER.qa.errors] exists
2017-05-23 13:25:49,701 [        4] WARN  rviceBus.QueuePermissions - Queue [private$\GROSSWEBER.qa.errors] is running with [Everyone] with AccessRights set to [GenericWrite]. Consider setting appropriate permissions, if required by the organization. For more information, consult the documentation.
2017-05-23 13:25:49,717 [        4] WARN  rviceBus.QueuePermissions - Queue [private$\GROSSWEBER.qa.errors] is running with [NT AUTHORITY\ANONYMOUS LOGON] with AccessRights set to [WriteMessage]. Consider setting appropriate permissions, if required by the organization. For more information, consult the documentation.
2017-05-23 13:25:49,717 [        4] DEBUG rviceBus.QueuePermissions - Checking if queue exists: TRITON1026\private$\GROSSWEBER.qa.audit.
2017-05-23 13:25:49,717 [        4] DEBUG rviceBus.QueuePermissions - Verified that the queue: [TRITON1026\private$\GROSSWEBER.qa.audit] exists
2017-05-23 13:25:49,717 [        4] WARN  rviceBus.QueuePermissions - Queue [private$\GROSSWEBER.qa.audit] is running with [Everyone] with AccessRights set to [GenericWrite]. Consider setting appropriate permissions, if required by the organization. For more information, consult the documentation.
2017-05-23 13:25:49,717 [        4] WARN  rviceBus.QueuePermissions - Queue [private$\GROSSWEBER.qa.audit] is running with [NT AUTHORITY\ANONYMOUS LOGON] with AccessRights set to [WriteMessage]. Consider setting appropriate permissions, if required by the organization. For more information, consult the documentation.
2017-05-23 13:25:49,732 [        4] DEBUG rviceBus.QueuePermissions - Checking if queue exists: TRITON1026\private$\GROSSWEBER.qa.ops.Timeouts.
2017-05-23 13:25:49,732 [        4] DEBUG rviceBus.QueuePermissions - Verified that the queue: [TRITON1026\private$\GROSSWEBER.qa.ops.Timeouts] exists
2017-05-23 13:25:49,732 [        4] WARN  rviceBus.QueuePermissions - Queue [private$\GROSSWEBER.qa.ops.Timeouts] is running with [Everyone] with AccessRights set to [GenericWrite]. Consider setting appropriate permissions, if required by the organization. For more information, consult the documentation.
2017-05-23 13:25:49,732 [        4] WARN  rviceBus.QueuePermissions - Queue [private$\GROSSWEBER.qa.ops.Timeouts] is running with [NT AUTHORITY\ANONYMOUS LOGON] with AccessRights set to [WriteMessage]. Consider setting appropriate permissions, if required by the organization. For more information, consult the documentation.
2017-05-23 13:25:49,732 [        4] DEBUG rviceBus.QueuePermissions - Checking if queue exists: TRITON1026\private$\GROSSWEBER.qa.ops.TimeoutsDispatcher.
2017-05-23 13:25:49,732 [        4] DEBUG rviceBus.QueuePermissions - Verified that the queue: [TRITON1026\private$\GROSSWEBER.qa.ops.TimeoutsDispatcher] exists
2017-05-23 13:25:49,748 [        4] WARN  rviceBus.QueuePermissions - Queue [private$\GROSSWEBER.qa.ops.TimeoutsDispatcher] is running with [Everyone] with AccessRights set to [GenericWrite]. Consider setting appropriate permissions, if required by the organization. For more information, consult the documentation.
2017-05-23 13:25:49,748 [        4] WARN  rviceBus.QueuePermissions - Queue [private$\GROSSWEBER.qa.ops.TimeoutsDispatcher] is running with [NT AUTHORITY\ANONYMOUS LOGON] with AccessRights set to [WriteMessage]. Consider setting appropriate permissions, if required by the organization. For more information, consult the documentation.
2017-05-23 13:25:49,748 [        4] DEBUG rviceBus.QueuePermissions - Checking if queue exists: TRITON1026\private$\GROSSWEBER.qa.ops.Retries.
2017-05-23 13:25:49,748 [        4] DEBUG rviceBus.QueuePermissions - Verified that the queue: [TRITON1026\private$\GROSSWEBER.qa.ops.Retries] exists
2017-05-23 13:25:49,748 [        4] WARN  rviceBus.QueuePermissions - Queue [private$\GROSSWEBER.qa.ops.Retries] is running with [Everyone] with AccessRights set to [GenericWrite]. Consider setting appropriate permissions, if required by the organization. For more information, consult the documentation.
2017-05-23 13:25:49,748 [        4] WARN  rviceBus.QueuePermissions - Queue [private$\GROSSWEBER.qa.ops.Retries] is running with [NT AUTHORITY\ANONYMOUS LOGON] with AccessRights set to [WriteMessage]. Consider setting appropriate permissions, if required by the organization. For more information, consult the documentation.
2017-05-23 13:25:49,748 [        4] DEBUG rviceBus.QueuePermissions - Checking if queue exists: TRITON1026\private$\GROSSWEBER.qa.ops.
2017-05-23 13:25:49,748 [        4] DEBUG rviceBus.QueuePermissions - Verified that the queue: [TRITON1026\private$\GROSSWEBER.qa.ops] exists
2017-05-23 13:25:49,764 [        4] WARN  rviceBus.QueuePermissions - Queue [private$\GROSSWEBER.qa.ops] is running with [Everyone] with AccessRights set to [GenericWrite]. Consider setting appropriate permissions, if required by the organization. For more information, consult the documentation.
2017-05-23 13:25:49,764 [        4] WARN  rviceBus.QueuePermissions - Queue [private$\GROSSWEBER.qa.ops] is running with [NT AUTHORITY\ANONYMOUS LOGON] with AccessRights set to [WriteMessage]. Consider setting appropriate permissions, if required by the organization. For more information, consult the documentation.
```

![2017-05-23_13-29-06](https://cloud.githubusercontent.com/assets/16245/26352405/f08d33e2-3fbb-11e7-94f7-7c253b326f66.png)

**Comment by agross** [comment]
FYI, this is a Windows Server 2008 R2 Web instance (no domain membership).

**Comment by ramonsmits** [comment]
@agross The default permissions applied can be seen as rather 'open'. In environments that are very strict on security, the defaults might not be applicable.

The default permissions allow any user to send a message to a queue which is a potential risk as a rogue user could write garbage to a queue or fill a queue so that storage quota will be reached potentially crippling the system.

We log a warning to reflect this concern as this is often neglected.

This can be resolved by altering permissions that suit your business. Instead of using Everyone to only use the accounts (groups or users) that should only send messages.

This is not something our nservicebus (host) installer actions for an endpoint can resolve as it is unaware of the permissions and credentials of other endpoints.

Please see the following documentation:

- https://docs.particular.net/nservicebus/msmq/#permissions

**Comment by agross** [comment]
@ramonsmits Thank you for the explanation.

I see this a bit differently. First off, I expect NSB to be secure by default and by logging a warning you inform your users/admins that it's not.

What is a rather strange decision is that the Host itself installs queues with permissions it will later bark about. That's not very consistent from my point of view.

People with more "open" requirements w.r.t. their queues will always have the opportunity to add more ACLs as per your linked docs. But the defaults NSB installs should be safe.

I use two profiles, one for staging/production and one for development. I can very well see that NSB can be smart about what profile may require what kind of permissions.

**Comment by ramonsmits** [comment]
@agross Regarding *the defaults NSB installs should be safe*. These are the permissions applied by MSMQ itself when creating a queue which you can try out by manually creating a queue. We previously choose to not conflict with the default MSMQ permission as that means that after creating a queue we would need to remove permissions which might not be expected behavior for our customers thus us raising a warning about a certain unwanted situation was (at that moment) more desirable.

What I've done is extended the current documentation with the error message as that was not present and might help others to find that documentation in the future.

- https://github.com/Particular/docs.particular.net/pull/2768

What I'll also do is discuss this to see if we might want to alter this behavior in a future major version as modifying this behavior would be a breaking change.

**Comment by agross** [comment]
I went and followed the warning instructions and removed `Everyone`s ACEs from the ACL for one of the queues that warnings where issued for.

Now the Host cannot start:
```
2017-05-24 11:02:22,936 [        4] FATAL viceBus.StartableEndpoint - Receiver Main failed to initialize.
System.InvalidOperationException: There is a problem with the input inputQueue: FormatName:DIRECT=OS:TRITON1026\private$\GROSSWEBER.qa.ops. See the enclosed exception for details. ---> System.Messaging.MessageQueueException: Access to Message Queuing system is denied.
   at System.Messaging.MessageQueue.MQCacheableInfo.get_Transactional()
   at System.Messaging.MessageQueue.get_Transactional()
   at NServiceBus.MessagePump.QueueIsTransactional() in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Transports\Msmq\MessagePump.cs:line 204
   --- End of inner exception stack trace ---
   at NServiceBus.MessagePump.QueueIsTransactional() in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Transports\Msmq\MessagePump.cs:line 208
   at NServiceBus.MessagePump.Init(Func`2 onMessage, Func`2 onError, CriticalError criticalError, PushSettings settings) in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Transports\Msmq\MessagePump.cs:line 43
   at NServiceBus.TransportReceiver.Init() in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Transports\TransportReceiver.cs:line 33
   at NServiceBus.StartableEndpoint.<InitializeReceivers>d__3.MoveNext() in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\StartableEndpoint.cs:line 62
2017-05-24 11:02:24,812 [        4] FATAL   NServiceBus.GenericHost - Exception when starting endpoint.
System.InvalidOperationException: There is a problem with the input inputQueue: FormatName:DIRECT=OS:TRITON1026\private$\GROSSWEBER.qa.ops. See the enclosed exception for details. ---> System.Messaging.MessageQueueException: Access to Message Queuing system is denied.
   at System.Messaging.MessageQueue.MQCacheableInfo.get_Transactional()
   at System.Messaging.MessageQueue.get_Transactional()
   at NServiceBus.MessagePump.QueueIsTransactional() in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Transports\Msmq\MessagePump.cs:line 204
   --- End of inner exception stack trace ---
   at NServiceBus.MessagePump.QueueIsTransactional() in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Transports\Msmq\MessagePump.cs:line 208
   at NServiceBus.MessagePump.Init(Func`2 onMessage, Func`2 onError, CriticalError criticalError, PushSettings settings) in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Transports\Msmq\MessagePump.cs:line 43
   at NServiceBus.TransportReceiver.Init() in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Transports\TransportReceiver.cs:line 33
   at NServiceBus.StartableEndpoint.<InitializeReceivers>d__3.MoveNext() in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\StartableEndpoint.cs:line 71
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.StartableEndpoint.<Start>d__1.MoveNext() in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\StartableEndpoint.cs:line 40
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.GenericHost.<Start>d__1.MoveNext() in C:\BuildAgent\work\fc89e968acb99302\src\NServiceBus.Hosting.Windows\GenericHost.cs:line 49
```

What is the recommended ACL for queues that only need to be accessed by a single Host with other Hosts possibly sending messages to it?

**Comment by timbussmann** [comment]
Moved to https://github.com/Particular/NServiceBus.Transport.Msmq/issues/21.
