### ISSUE TITLE
NSB 7 Alpha: When license has expired, reports a unfriendly fatal error.

### ISSUE THREAD

**Issue by indualagarsamy** [Particular/NServiceBus#4801]
**Steps to Repro**
- Create a simple sample which uses the following packages:
  ```xml
  <packages>
  <package id="NServiceBus" version="7.0.0-alpha0029" targetFramework="net461" />
  <package id="NServiceBus.Transport.Msmq" version="1.0.0-alpha0037" targetFramework="net461" />
  </packages>
  ```
- Make sure you're working with an expired license. 
- Create a sample that sends a message to itself and processes it. 
- Make sure you're working with an expired license.
- When the endpoint starts, the following exception is thrown:

```
2017-06-19 21:11:54.204 INFO  NServiceBus.LicenseManager No valid license could be found, falling back to trial license with start date '5/24/2017'

2017-06-19 21:11:54.214 WARN  NServiceBus.LicenseManager Trial for the Particular Service Platform has expired.
2017-06-19 21:11:54.325 FATAL NServiceBus.Features.LicenseReminder Failed to initialize the license
System.Resources.MissingManifestResourceException: Could not find any resources appropriate for the specified culture or the neutral culture.  Make sure "NServiceBus.LicenseExpiredForm.resources" was correctly embedded or linked into assembly "NServiceBus.Core" at compile time, or that all the satellite assemblies required are loadable and fully signed.
   at System.Resources.ManifestBasedResourceGroveler.HandleResourceStreamMissing(String fileName)
   at System.Resources.ManifestBasedResourceGroveler.GrovelForResourceSet(CultureInfo culture, Dictionary`2 localResourceSets, Boolean tryParents, Boolean createIfNotExists, StackCrawlMark& stackMark)
   at System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo requestedCulture, Boolean createIfNotExists, Boolean tryParents, StackCrawlMark& stackMark)
   at System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo culture, Boolean createIfNotExists, Boolean tryParents)
   at System.Resources.ResourceManager.GetObject(String name, CultureInfo culture, Boolean wrapUnmanagedMemStream)
   at System.Resources.ResourceManager.GetObject(String name)
   at NServiceBus.LicenseExpiredForm.InitializeComponent() in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Licensing\LicenseExpiredForm.Designer.cs:line 148
   at NServiceBus.LicenseExpiredForm..ctor() in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Licensing\LicenseExpiredForm.cs:line 17
   at NServiceBus.LicenseExpiredFormDisplayer.PromptUserForLicense(License currentLicense) in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Licensing\LicenseExpiredFormDisplayer.cs:line 14
   at NServiceBus.LicenseManager.PromptUserForLicenseIfTrialHasExpired() in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Licensing\LicenseManager.cs:line 85
   at NServiceBus.LicenseManager.InitializeLicense(String licenseText, String licenseFilePath) in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Licensing\LicenseManager.cs:line 31
   at NServiceBus.Features.LicenseReminder.Setup(FeatureConfigurationContext context) in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Licensing\LicenseReminder.cs:line 21
```

**Comment by andreasohlund** [comment]
@bording can you take a look at this?

**Comment by bording** [comment]
Since the new project format does't actually understand winforms, it's embedding the form's resource file in the assembly under a different name than what the form is expecting. The name of the resource is `NServiceBus.Licensing.LicenseExpiredForm.resources`, but the form is looking for `NServiceBus.LicenseExpiredForm.resources`. I'm not sure if there is a way to control what name is used when the resource is embedded, but if we change the namespace of the `LicenseExpiredForm` class from `NServiceBus` to `NServiceBus.Licensing`, then the form can find the resource.

I'll submit a PR with that change.
