### ISSUE TITLE
Unobtrusive conventions don't respect the IsInterface check

### ISSUE THREAD

**Issue by indualagarsamy** [Particular/NServiceBus#4860]
This was reported by a customer. 

Steps to reproduce:
- Run the version 5 of the unobtrusive sample after modifying this line:
https://github.com/Particular/docs.particular.net/blob/master/samples/unobtrusive/Core_5/Shared/ConventionExtensions.cs#L21
to also include && type.IsInterface and type E in the Server application and the event is published. 

- Make the same changes to the Version 6 Sample and when you press E in the Server an exception is thrown:

```
System.Exception occurred
  HResult=0x80131500
  Message=Could not find metadata for 'Events.IMyEvent__impl'.
Ensure the following:
1. 'Events.IMyEvent__impl' is included in initial scanning. 
2. 'Events.IMyEvent__impl' implements either 'IMessage', 'IEvent' or 'ICommand' or alternatively, if you don't want to implement an interface, you can use 'Unobtrusive Mode'.
  Source=NServiceBus.Core
  StackTrace:
   at NServiceBus.Unicast.Messages.MessageMetadataRegistry.GetMessageMetadata(Type messageType)
   at NServiceBus.SerializeMessageConnector.SerializeEnclosedMessageTypes(Type messageType)
   at NServiceBus.SerializeMessageConnector.<Invoke>d__1.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.DataBusSendBehavior.<Invoke>d__1.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.MutateOutgoingMessageBehavior.<InvokeOutgoingMessageMutators>d__1.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at CommandSender.<PublishEvent>d__1.MoveNext() in C:\dev\docs.particular.net\samples\unobtrusive\Core_6\Server\CommandSender.cs:line 34
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at CommandSender.<Start>d__0.MoveNext() in C:\dev\docs.particular.net\samples\unobtrusive\Core_6\Server\CommandSender.cs:line 22
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Program.<AsyncMain>d__1.MoveNext() in C:\dev\docs.particular.net\samples\unobtrusive\Core_6\Server\Program.cs:line 25
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Program.Main() in C:\dev\docs.particular.net\samples\unobtrusive\Core_6\Server\Program.cs:line 9
```

**Comment by dbelcham** [comment]
@indualagarsamy I updated your issue to add in the missing pieces to successfully repro this. I have verified that V6 does do what you said while V5 doesn't.

**Comment by indualagarsamy** [comment]
Thanks @dbelcham.

**Comment by timbussmann** [comment]
targeting a fix for v7 for now. After we know more about the issue and the required fix we can decide whether we should backport this to v6 as well.

**Comment by dbelcham** [comment]
I can't seem to replicate this with v7 running against Framework 4.5.2 using 7.0.0-alpharelease0009 and VS 15.3 Preview
![image](https://user-images.githubusercontent.com/1378057/28635272-566f2b1c-7210-11e7-833c-4a799fc76947.png)

**Comment by bording** [comment]
@dbelcham Can you also try the latest alpha package to make sure it's still OK there?

I have to say I wasn't expecting it to work in v7, since we haven't changed anything that I would expect to be relevant. What version of V6 did you repro it with?

**Comment by dbelcham** [comment]
Ah..didn't see the newer alpha out there. Same successful results with 7.0.0-alpharelease0026.

V6 failures were repro'd on 6.3.4.

**Comment by dbelcham** [comment]
Investigation has shown the following
### V6
- The `IOutgoingLogicalMessageContext.Message.MessageType` value changes from `IMyEvent` when entering the `EncryptBehavior.Invoke(...)` method to `IMyEvent__Impl` when leaving the `EncryptBehavior`.
- Because the `MessageType` value changes to a type (`IMyEvent__Impl`) that wasn't scanned and registered, serialization of the outgoing message fails.
- The change in type that occurs inside the `EncryptionBehavior` code is caused by the call to the `OutgoingLogicalMessageContext.UpdateMessage(...)` call on [line 25](https://github.com/Particular/NServiceBus/blob/master/src/NServiceBus.Core/Encryption/EncryptBehavior.cs#L25). The `UpdateMessage` method is passed a copy of the `currentMessageToSend` which, at this point in time, is of type `IMyEvent__Impl`. 
- Inside the `OutgoingLogicalMessageContext.UpdateMessage` method a new `OutgoingLogicalMessage` is created based on the passed in `IMyEvent__Impl` instance. `newInstance.GetType()` on [line 25](https://github.com/Particular/NServiceBus/blob/master/src/NServiceBus.Core/Pipeline/Outgoing/OutgoingLogicalMessageContext.cs#L25) is the place where the message type in the `IOutgoingLogicalMessageContext.Message` is changed causing the failure.
- The only other location that `OutgoingLogicalMessageContext.UpdateMessage` is called is from the `MutateOutgoingMessageBehavior.InvokeOutgoingMessageMutators` method. On [line 29]() a new instance of `MutateOutoingMessageContext` is created and it is passed `context.Message.Instance` which is of type `IMyEvent__Impl`. Any mutator that is subsequently invoked will only see the `IMyEvent__Impl` type. If the `MutateOutgoingMessageContext.OutgoingMessage` is modified, [line 49]() of `MutateOutgoingMessageBehavior` will call `OutgoingLogicalMessageContext.UpdateMessage` and change the outgoing message type to `IMyEvent__Impl` causing the same problem as seen by the `EncryptionBehavior` code.
- The `IMutateOutgoingMessage` implementation needs to look like the following code since you're working with an incoming instance of `IMyEvent_Impl` and you want to retain that type in the `context.OutgoingMessage` when leaving the mutator.
```c#
        public Task MutateOutgoing(MutateOutgoingMessageContext context)
        {
            dynamic outgoingMessage = context.OutgoingMessage;

            outgoingMessage.EventId = Guid.NewGuid();

            context.OutgoingMessage = outgoingMessage;
            
            return Task.CompletedTask;
        }
```

### V7
- By default, sending an event of type `IMyEvent` will succeed because the `EncryptBehavior` is not in the pipeline. This is why [my previous repro failed](https://github.com/Particular/NServiceBus/issues/4860#issuecomment-318128457)
- Cannot verify that adding the `NServiceBus.Encryption.MessageProperty` package causes the same behavoir as is seen in V6 since that package is not v7 compliant yet. Based on a review of the code, the behavior should be the same though.
- The `MutateOutgoingMessageBehavior` bug seen in v6 will also be present in v7

### Fixing this
Right now two courses of action seem possible.
1) Update the `EncryptionBehavior` and `MutateOutgoingMessageBehavior.InvokeOutgoingMessageMutators` to have access to the `MessageMapper` class. Not sure if `MessageMapper` is available via DI right now or not (need to investigate this). This solution also feels dirty since we're trying to work towards a DI-less world long term.
2) Change the signature of the `OutgoingLogicalMessageContext.UpdateMessage` method to ensure that the message type is retained correctly when the message itself is updated. This will definitely be a breaking change.

### ToDo
- [ ] determine if `MessageMapper` is available via DI to determine if option 1 is possible
- [ ] figure out which solution we want to implement

**Comment by bording** [comment]
@dbelcham Nice investigation! As we discussed, it would also be worth looking at the v5 implementation to see how it avoids this problem.

**Comment by timbussmann** [comment]
feels like option 1 is a suitable approach for v6 (we can probably also put the mapper on the context to avoid DI) while option 2 would be the desired solution for v7?

**Comment by timbussmann** [comment]
I also wonder whether we should disallow changing the message type within the pipeline (verify that the new instance is assignable to the message type). I think that would break some samples we have, but it feels this is far too dangerous to be a valid supported scenario (and you can always fall back to use interface messages).

**Comment by dbelcham** [comment]
@timbussmann I might have been slightly wrong in option 1. I think the `MessageMapper` is going to need to be injected into the `OutgoingLogicalMessageContext.UpdateMessage` method. We know the proper type outside of that call, but inside that code all we have is the "new message" (which is the `__Impl`). The message type isn't visible for change outside of that method.

I'm also starting to think that because `OutgoingLogicalMessageContext.UpdateMessage` only has the "new message" available, we're not going to be able to determine _if_ we need to override the type. Would we look at the "new message" type name to see if `newMessage.GetType().Name.EndsWith("__Impl")` and use that as our trigger for needing to overwrite the type to the base as determined by `MessageMapper`? I'm not completely convinced that this would be robust enough.

**Comment by dbelcham** [comment]
@bording checked v5 and put notes above. Doesn't seem to be an issue, or possible, there.

**Comment by dbelcham** [comment]
@timbussmann after some playing around I don't think we can use the idea we talked about that did:
```c#
if (Message.Instance != newInstance)
{
    Message = new OutgoingLogicalMessage(newInstance.GetType(), newInstance);
}
```
The problem is that the `newInstance` is a reference copy of the original `Message.Instance` so any modification of property values on the `newInstance` (which is what the `EncryptionBehavior` and possibly mutators will be doing) is going to be reflected in the `Message.Instance` as well. That means the equality comparison will always return true.

I did verify that when `Message.Instance` is a `IMyEvent__Impl` a call to `mapper.GetMappedTypeFor(Message.Instance.GetType())` will return the correct original type (`IMyEvent`). I think we're going to have to look at how to get `MessageMapper` into the `UpdateMessage(...)` method and use it to set the type.

**Comment by timbussmann** [comment]
@dbelcham 
> The problem is that the newInstance is a reference copy of the original Message.Instance so any modification of property values on the newInstance (which is what the EncryptionBehavior and possibly mutators will be doing) is going to be reflected in the Message.Instance as well. That means the equality comparison will always return true.

I fail to the see the problem with that, that would be intentional?
* If only properties are modified, there is no need to assign a new `OutgoingLogicalMessage`, as the current one already has a reference to the same type instance and the type of the instance didn't change either, so nothing needs to be changed.
* Only if somebody replaces the instance with a completely different type instance we need to update `OutgoingLogicalMessage` as not just the instance, but also the instance's type changed.
