### ISSUE TITLE
Key not present (NServiceBus.PipelineConfiguration)

### ISSUE THREAD

**Issue by markgould** [Particular/NServiceBus#5053]
We received a strange error in one of our applications today:

```
Caught exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---&gt; System.Collections.Generic.KeyNotFoundException: The given key (NServiceBus.PipelineConfiguration) was not present in the dictionary.
   at NServiceBus.Settings.SettingsHolder.Get(String key) in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Settings\SettingsHolder.cs:line 94
   at NServiceBus.Settings.SettingsHolder.Get[T]() in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Settings\SettingsHolder.cs:line 72
   at NServiceBus.PipelineCache.&lt;&gt;c__DisplayClass2_0`1.&lt;FromMainPipeline&gt;b__0() in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Pipeline\PipelineCache.cs:line 44
   at System.Lazy`1.CreateValue()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Lazy`1.get_Value()
   at NServiceBus.PipelineCache.Pipeline[TContext]() in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Pipeline\PipelineCache.cs:line 33
   at NServiceBus.MessageOperations.Publish(IBehaviorContext context, Type messageType, Object message, PublishOptions options) in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Unicast\MessageOperations.cs:line 24
   at NServiceBus.MessageSession.Publish(Object message, PublishOptions options) in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\MessageSession.cs:line 25
   at RefundTrac.Server.RefundContext.PostToTax() in C:\agent\_work\15\s\src\RefundTrac.Server\RefundContext.cs:line 117
```

This happens to be in an app hosted in IIS, so we're looking into if the app was recycled/restarted around the same time. The endpoint is being initialized from Application_Start in the Global.asax, so I'm not sure how a message could be being processed before the endpoint is initialized.

Any suggestions on how to start tracking down this issue? NServiceBus 6.4.0

**Comment by andreasohlund** [comment]
The lazy feels like a smoking gun to me.

Is PostToTax() the result of a webcall? (ie happens outside of a handler)

**Comment by andreasohlund** [comment]
My hunch is indeed an app pool recycle since that "stops" the endpoint , that in turn clears everything including wiping the setting holder

https://github.com/Particular/NServiceBus/blob/master/src/NServiceBus.Core/Unicast/RunningEndpointInstance.cs#L57

and if you have a web request that comes in after that it might use a message session that is in an invalid state

https://github.com/Particular/NServiceBus/blob/master/src/NServiceBus.Core/Unicast/RunningEndpointInstance.cs#L79

@Particular/nservicebus-maintainers regardless if this is the issue should we add guards for this?

**Comment by timbussmann** [comment]
+1 on adding safeguards for better exceptions.

**Comment by markgould** [comment]
Yes, it happens out of a handler. I'm requesting the NServiceBus log from our client. They claim it is only being recycled at night but the log should tell me if the endpoint is starting/stopping around the time the error happened.

**Comment by markgould** [comment]
Ok, found some more info. The customer appears to be having some database issues causing the endpoint to shut down. Like you said, this would leave the endpoint in an invalid state. I'm wondering what is the best workaround for this. The webapp is running but the endpoint inside of it is now shutdown.

```
2017-10-25 11:34:47.595 FATAL NServiceBus Failed to peek RefundTrac.Web.Timeouts@[dbo]@[TaxNSB]
System.Data.SqlClient.SqlException (0x80131904): Connection Timeout Expired.  The timeout period elapsed during the post-login phase.  The connection could have timed out while waiting for server to complete the login process and respond; Or it could have timed out while attempting to create multiple active connections.  The duration spent while attempting to connect to this server was - [Pre-Login] initialization=10; handshake=15; [Login] initialization=0; 
---Removed stack trace for brevity
2017-10-25 11:34:48.861 INFO  NServiceBus.Unicast.UnicastBus Shutdown complete.
2017-10-25 11:34:48.861 INFO  NServiceBus.Unicast.UnicastBus Shutdown complete.
2017-10-25 11:34:48.861 INFO  NServiceBus.Unicast.UnicastBus Shutdown complete.
2017-10-25 11:34:48.861 INFO  NServiceBus.Unicast.UnicastBus Shutdown complete.
```

**Comment by andreasohlund** [comment]
Is recycling the website even a possibility?

In v7 the default behavior is to retry forever but that won't help you right now.

**Comment by andreasohlund** [comment]
Strike that, you can get the same "retry forever behavior" in v6 by overriding the critical error action and make it a no-op.

https://docs.particular.net/nservicebus/hosting/cloud-services-host/critical?version=cloudserviceshost_8#handling-critical-errors

Would that work for you?

**Comment by andreasohlund** [comment]
Sorry wrong link, should be: https://docs.particular.net/nservicebus/hosting/critical-errors

**Comment by markgould** [comment]
I think that would be a good solution for, I'll try that out. Thanks for the quick response!

**Comment by andreasohlund** [comment]
@markgould did the custom critical action work for you?

**Comment by markgould** [comment]
It looks to have, we haven't seen any issues since. I tried some testing of taking down databases while the endpoint was running and it looks to be working fine. Thanks!

**Comment by andreasohlund** [comment]
Awesome, closing this for now, just reopen this issue if needed.
