### ISSUE TITLE
XML deserialization fails for events with list of KeyvaluePair in NServiceBus 7.0.0-RC1

### ISSUE THREAD

**Issue by notepid** [Particular/NServiceBus#5148]
The following even fails on processing endpoint. The event does not reach the event handler.
We are using NServiceBus.RabbitMQ-RC1 as transport

```
public interface SomeEvent : IEvent
{
   List<KeyValuePair<string, string>> Claims { get; set; }
}
```

```
NServiceBus.MessageDeserializationException: An error occurred while attempting to extract logical messages from incoming physical message dd2e17b8-b286-47bf-b3e1-a8c600778874 ---> System.ArgumentNullException: Value cannot be null.
Parameter name: meth
   at System.Reflection.Emit.DynamicILGenerator.Emit(OpCode opcode, MethodInfo meth)
   at NServiceBus.DelegateFactory.CreateSet(PropertyInfo property)
   at NServiceBus.XmlDeserialization.GetObjectOfTypeFromNode(Type t, XmlNode node)
   at NServiceBus.XmlDeserialization.Process(XmlNode node, Object parent, Type nodeType)
   at NServiceBus.XmlDeserialization.GetPropertyValue(Type type, XmlNode n)
   at NServiceBus.XmlDeserialization.GetObjectOfTypeFromNode(Type t, XmlNode node)
   at NServiceBus.XmlDeserialization.Process(XmlNode node, Object parent, Type nodeType)
   at NServiceBus.XmlDeserialization.ProcessRootTypes(IEnumerable`1 rootTypes, XmlDocument doc, ICollection`1 result)
   at NServiceBus.XmlDeserialization.Deserialize(Stream stream, IList`1 messageTypesToDeserialize)
   at NServiceBus.XmlMessageSerializer.Deserialize(Stream stream, IList`1 messageTypesToDeserialize)
   at NServiceBus.DeserializeLogicalMessagesConnector.Extract(IncomingMessage physicalMessage)
   at NServiceBus.DeserializeLogicalMessagesConnector.ExtractWithExceptionHandling(IncomingMessage message)
   --- End of inner exception stack trace ---
   at NServiceBus.DeserializeLogicalMessagesConnector.ExtractWithExceptionHandling(IncomingMessage message)
   at NServiceBus.DeserializeLogicalMessagesConnector.<Invoke>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.UnitOfWorkBehavior.<InvokeUnitsOfWork>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.MutateIncomingTransportMessageBehavior.<InvokeIncomingTransportMessagesMutators>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.InvokeAuditPipelineBehavior.<Invoke>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.ProcessingStatisticsBehavior.<Invoke>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.TransportReceiveToPhysicalMessageProcessingConnector.<Invoke>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.MainPipelineExecutor.<Invoke>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at NServiceBus.Transport.RabbitMQ.MessagePump.<Process>d__29.MoveNext()
```

**Comment by andreasohlund** [comment]
`List<KeyValuePair<string, string>> Claims { get; set; }` is not supported by the serializer. Would you be able to use `Dictionary<string,string>` instead?

**Comment by notepid** [comment]
We solved it by creating a new KVP class instead of using KeyValuePair. Mostly wanted to inform you guys about this if it was supposed to work.

**Comment by andreasohlund** [comment]
Got it, thanks for letting us know 👍
