### ISSUE TITLE
AssemblyScanner enforcing core reference prevents ILMerging

### ISSUE THREAD

**Issue by danielmarbach** [Particular/NServiceBus#5311]
As part of a customer case I got asked whether core can be ILMerged. The requirement of ILMerging core comes from Dynamics CRM 365. Apparently, Dynamics CRM 365 allows a plugin to be only one assembly.

https://blogs.msdn.microsoft.com/crm/2010/11/09/how-to-reference-assemblies-from-plug-ins/
https://community.dynamics.com/365/sales/b/thrivestechnicaldynamics365blog/archive/2017/02/27/external-assemblies-in-dynamics-crm-plugins-with-ilmerge

The problem is though that the core can't be ILMerged anymore starting from v6 and higher. When NServiceBus is ILMerged into an assembly the scanner logic skips the assembly because it looks to the scanner like it does not reference the core (`GetReferencedAssemblies()` will not return the core as a reference, see https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/Hosting/Helpers/AssemblyScanner.cs#L186). Loading an assembly with an ILMerged core will lead to

```
System.Exception: Can't find any behaviors/connectors for the root context (NServiceBus.Pipeline.ITransportReceiveContext)
   at NServiceBus.PipelineModelBuilder.Build()
   at NServiceBus.StepRegistrationsCoordinator.BuildPipelineModelFor[TRootContext]()
   at NServiceBus.Pipeline`1..ctor(IBuilder builder, PipelineModifications pipelineModifications)
   at NServiceBus.ReceiveComponent.<Initialize>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at NServiceBus.StartableEndpoint.<Start>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at NServiceBus.Endpoint.<Start>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at ConsoleApp2.Program.<Main>d__0.MoveNext()
```

see also https://discuss.particular.net/t/cant-find-any-behaviors-connectors-for-the-root-context/441/2

Tried to hack around that problem by doing the following

```
            // workaround to avoid 
            //  Can't find any behaviors/connectors for the root context (NServiceBus.Pipeline.ITransportReceiveContext)
            var types = Assembly.GetExecutingAssembly().GetTypes();
            var methodInfo = endpointConfiguration.GetType()
                .GetMethod("TypesToScanInternal", BindingFlags.Instance | BindingFlags.NonPublic);
            methodInfo.Invoke(endpointConfiguration, new object[] { types });
```

which then leads to the next problem

```
2018-12-17 15:52:44.514 FATAL NServiceBus.Features.LicenseReminder Failed to initialize the license
System.Exception: No ReleaseDateAttribute could be found in assembly, please make sure GitVersion is enabled
   at Particular.Licensing.ReleaseDateReader.GetReleaseDate()
   at Particular.Licensing.LicenseExpirationChecker.HasLicenseExpired(License license)
   at Particular.Licensing.LicenseSourceResult.<>c.<DetermineBestLicenseSourceResult>b__12_3(LicenseSourceResult p)
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at Particular.Licensing.LicenseSourceResult.DetermineBestLicenseSourceResult(LicenseSourceResult[] sourceResults)
   at Particular.Licensing.LicenseSourceHKLMRegKey.Find(String applicationName)
   at Particular.Licensing.ActiveLicense.<>c__DisplayClass0_0.<Find>b__0(LicenseSource licenseSource)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Particular.Licensing.ActiveLicense.Find(String applicationName, LicenseSource[] licenseSources)
   at NServiceBus.LicenseManager.InitializeLicense(String licenseText, String licenseFilePath)
   at NServiceBus.Features.LicenseReminder.Setup(FeatureConfigurationContext context)
```

**Comment by ricred** [comment]
Any new info/workaround on this bug ?
Having a similar problem when publish messages via NServicebus from stored procedure with MSMQ as transportlayer.

**Comment by andreasohlund** [comment]
@ricred no update on this at this moment. My suggestion would be to switch to native C# from your stored proc to avoid referencing NServiceBus.

https://docs.particular.net/transports/msmq/operations-scripting#native-send-the-native-send-helper-methods-in-c

That only works for sends but you could send to an "integration" endpoint that will then do a `Publish`. Would that work for you?
