### ISSUE TITLE
Restarting endpoint throws exception

### ISSUE THREAD

**Issue by devindran** [Particular/NServiceBus#5319]
I am running NSB as a self hosted .net core app which includes a http endpoint. In the event of any connection issues that cannot self recover, I would like to be able to manually restart this endpoint.

My constraints are that I cannot restart the entire app as the http endpoint may be taking in traffic.

I can stop the instance through IEndpointInstance.Stop, but if I try to restart it using Endpoint.Start(myEndpointConfiguration), it throws the following exception

Unhandled Exception: System.Exception: Unable to set the value for key: NServiceBus.AssemblyScannerConfiguration. The settings has been locked for modifications. Move any configuration code earlier in the configuration pipeline
   at NServiceBus.Settings.SettingsHolder.EnsureWriteEnabled(String key) in C:\BuildAgent\work\b549d46003942065\src\NServiceBus.Core\Settings\SettingsHolder.cs:line 320
   at NServiceBus.Settings.SettingsHolder.Set(String key, Object value) in C:\BuildAgent\work\b549d46003942065\src\NServiceBus.Core\Settings\SettingsHolder.cs:line 196
   at NServiceBus.Settings.SettingsHolder.GetOrCreate[T]() in C:\BuildAgent\work\b549d46003942065\src\NServiceBus.Core\Settings\SettingsHolder.cs:line 183
   at NServiceBus.EndpointConfiguration.GetAllowedCoreTypes() in C:\BuildAgent\work\b549d46003942065\src\NServiceBus.Core\EndpointConfiguration.cs:line 254
   at NServiceBus.EndpointConfiguration.Build() in C:\BuildAgent\work\b549d46003942065\src\NServiceBus.Core\EndpointConfiguration.cs:line 142
   at NServiceBus.Endpoint.Create(EndpointConfiguration configuration) in C:\BuildAgent\work\b549d46003942065\src\NServiceBus.Core\Endpoint.cs:line 16
   at NServiceBus.Endpoint.Start(EndpointConfiguration configuration)

It seems like the EndpointConfiguration can only be started once and if I attempt it a second time it will fail. Is this by design?

**Comment by danielmarbach** [comment]
@devindran Yes that is by design. You can only use the endpoint configuration once. When you restart an endpoint you have to create a new endpoint configuration.
