### ISSUE TITLE
Learning transport: UnauthorizedAccessException with incorrect file permissions 

### ISSUE THREAD

**Issue by dbelcham** [Particular/NServiceBus#5323]
UnauthorizedAccessException with incorrect file permissions results in infinite loop not  stopping the endpoint.

Core: 7.1.3

Exception:
```
2019-01-23 09:15:23.497 FATAL NServiceBus Failure to process messages
System.UnauthorizedAccessException: Access to the path is denied.
   at System.IO.FileSystem.MoveFile(String sourceFullPath, String destFullPath)
   at System.IO.File.Move(String sourceFileName, String destFileName)
   at NServiceBus.AsyncFile.Move(String sourcePath, String targetPath)
   at NServiceBus.LearningTransportMessagePump.InnerProcessMessages()
   at NServiceBus.LearningTransportMessagePump.ProcessMessages()
```

I would expect the endpoint to verify permissions on start or to atleast gracefully handle persmissions to either stop the endpoint or to atleast not running in an infinite loop consuming CPU resources.

**Comment by SzymonPobiega** [comment]
The code does invoke `CriticalError` when this problem occurs so if the critical handler is configured properly it takes care of the problem.

Checking for permissions seems to be a very complex problem here because we would have to verify is the process has rights to move a file from the input queue directory to a transaction directory.

I'll raise a separate issue to investigate how various components use critical error and what do the assume.
