### ISSUE TITLE
Assembly scanning broken in .NET Core 3.0

### ISSUE THREAD

**Issue by jbogard** [Particular/NServiceBus#5361]
Steps to reproduce:

1. `dotnet new nsbdockercontainer`
2. Change target framework to `netcoreapp3.0`
3. Build and run in Visual Studio 2019

Error message:

```
Exception details:
System.ArgumentException: Empty path name is not legal.
Parameter name: path
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at System.IO.File.OpenRead(String path)
   at NServiceBus.AssemblyValidator.ValidateAssemblyFile(String assemblyPath, Boolean& shouldLoad, String& reason) in C:\dev\NServiceBus\src\NServiceBus.Core\Hosting\Helpers\AssemblyValidator.cs:line 45
   at NServiceBus.Hosting.Helpers.AssemblyScanner.TryLoadScannableAssembly(String assemblyPath, AssemblyScannerResults results, Assembly& assembly) in C:\dev\NServiceBus\src\NServiceBus.Core\Hosting\Helpers\AssemblyScanner.cs:line 132
   at NServiceBus.Hosting.Helpers.AssemblyScanner.GetScannableAssemblies() in C:\dev\NServiceBus\src\NServiceBus.Core\Hosting\Helpers\AssemblyScanner.cs:line 100
   at NServiceBus.EndpointConfiguration.Scan(AssemblyScanner assemblyScanner) in C:\dev\NServiceBus\src\NServiceBus.Core\EndpointConfiguration.cs:line 269
   at NServiceBus.EndpointConfiguration.GetAllowedTypes(String path) in C:\dev\NServiceBus\src\NServiceBus.Core\EndpointConfiguration.cs:line 249
   at NServiceBus.EndpointConfiguration.Build() in C:\dev\NServiceBus\src\NServiceBus.Core\EndpointConfiguration.cs:line 138
   at NServiceBus.Endpoint.Create(EndpointConfiguration configuration) in C:\dev\NServiceBus\src\NServiceBus.Core\Endpoint.cs:line 17
   at NServiceBus.Endpoint.Start(EndpointConfiguration configuration) in C:\dev\NServiceBus\src\NServiceBus.Core\Endpoint.cs:line 27
   at Nsb30HostingBug.Host.Start() in C:\dev\Nsb30HostingBug\Nsb30HostingBug\Host.cs:line 53
```

Details:

The AssemblyScanner class runs through the `AppDomain.CurrentDomain.GetData("TRUSTED_PLATFORM_ASSEMBLIES")` values split on `;`. However, with .NET Core 3.0, that value has a trailing semicolon. `netcoreapp2.2`:

```
...
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.2.3\WindowsBase.dll;C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.2.3\mscorlib.dll;C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.2.3\netstandard.dll;C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.2.3\System.Private.CoreLib.dll
```

`netcoreapp3.0`:

```
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.0.0-preview3-27503-5\mscorlib.dll;C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.0.0-preview3-27503-5\netstandard.dll;C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.0.0-preview3-27503-5\System.Private.CoreLib.dll;
```

Note that last semicolon.

**Comment by bording** [comment]
@jbogard This has already been reported (#5348) and filed as a .NET Core bug (https://github.com/dotnet/core-setup/issues/5553). It should be fixed in the next .NET Core preview, so we're not going to make any changes in NServiceBus.

**Comment by jbogard** [comment]
🍻

**Comment by bording** [comment]
.NET Core 3.0 Preview 4 is out, and I've just confirmed that the fix is in there and NServiceBus is working! 🎉

**Comment by lailabougria** [comment]
Hi Jimmy, 

We wanted to inform you that we now fully support NServiceBus on top of .NET Core 3.1. We'll be publishing a blog post on it soon, but thought you might be interested to [read about it already](https://particular.net/blog/nservicebus-7-for-net-core-is-here).
