### ISSUE TITLE
NSB6: MSMQ transport interfers with RabbitMQ?

### ISSUE THREAD

**Issue by pardahlman** [Particular/NServiceBus#5365]
I have an application running NServiceBus 6.5.5. It is configured to host two endpoints, one using RabbitMQ as transport and the other MSMQ.

Using the RabbitMQ transport, it is possible to use `IEndpointInstance.Publish` and `IMessageHandlers` gets correctly created and invoked with messages published on RabbitMQ.

_However_, when using `IMessageHandlerContext.Publish` in the RabbitMQ context, I get the following exception

```
System.Exception: The MSMQ transport only supports unicast transport operations.
at NServiceBus.MsmqMessageDispatcher.Dispatch(TransportOperations outgoingMessages, TransportTransaction transaction, ContextBag context) in C:\BuildAgent\work\b549d46003942065\src\NServiceBus.Core\Transports\Msmq\MsmqMessageDispatcher.cs:line 33
at NServiceBus.ForkExtensions.Fork[TFromContext,TToContext,TForkContext](IForkConnector`3 forkConnector, TForkContext context) in C:\BuildAgent\work\b549d46003942065\src\NServiceBus.Core\Pipeline\ForkExtensions.cs:line 13
at NServiceBus.TransportReceiveToPhysicalMessageProcessingConnector.<Invoke>d__1.MoveNext() in C:\BuildAgent\work\b549d46003942065\src\NServiceBus.Core\Pipeline\Incoming\TransportReceiveToPhysicalMessageProcessingConnector.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at NServiceBus.MainPipelineExecutor.<Invoke>d__1.MoveNext() in C:\BuildAgent\work\b549d46003942065\src\NServiceBus.Core\Pipeline\MainPipelineExecutor.cs:line 34
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at NServiceBus.Transport.RabbitMQ.MessagePump.<Process>d__28.MoveNext() in C:\BuildAgent\work\15dcdbe5f88af6ed\src\NServiceBus.RabbitMQ\Receiving\MessagePump.cs:line 248
```

The stack trace suggests that it is the **RabbitMQ** `MessagePump` that at some point invokes the **MSMQ** MsmqMessageDispatcher.

At some point I had a similar problem where the RabbitMQ transport interfered with MSMQ, but this was resolved using 

```csharp
configuration.AssemblyScanner().ExcludeAssemblies("NServiceBus.Transports.RabbitMQ.dll");
```

However, in NSB6, MSMQ transport is part of the core library, and excluding that was not a good idea (`Can't find any behaviors/connectors for the root context`).

Any suggestions?

**Comment by andreasohlund** [comment]
This sounds like issue with scanning the rabbit mq transport assembly. Do you see anything in the logs?

Would you be able to upload a minimal reproduction so that we can take a look?

**Comment by pardahlman** [comment]
Hej, @andreasohlund - thanks for getting back on this 👍

Long story short, I found the problem. I was under the impression that the internal container was only used for resolving handlers, so I used the same instance for both transports 🙈 . As it clearly states in the documentation _"Note that all NServiceBus services will be injected into the passed in dependency injection instance."_.

So using separate containers for the different transports solved the issue.

**Comment by andreasohlund** [comment]
Ah, got it!

Glad you got it going 👍
