### ISSUE TITLE
System.ArgumentOutOfRangeException: The size of FileContent exceeds the configured maximum length of 1048576 bytes. (Parameter 'message')

### ISSUE THREAD

**Issue by JSCProjects** [Particular/NServiceBus#5558]
I'm receiving the following error when I try to handle a message with a (azure)databus property. (Redacted some names) 

```
System.ArgumentOutOfRangeException: The size of FileContent exceeds the configured maximum length of 1048576 bytes. (Parameter 'message')
   at Handlers.Process......CommandHandler.Handle(.....FileCommand message, IMessageHandlerContext context) in /app/Application.....Listener/Handlers/.....CommandHandler.cs:line 31
   at NServiceBus.InvokeHandlerTerminator.Terminate(IInvokeHandlerContext context)
   at NServiceBus.LoadHandlersConnector.Invoke(IIncomingLogicalMessageContext context, Func`2 stage)
   at NServiceBus.ScheduledTaskHandlingBehavior.Invoke(IIncomingLogicalMessageContext context, Func`2 next)
   at NServiceBus.DataBusReceiveBehavior.Invoke(IIncomingLogicalMessageContext context, Func`2 next)
   at NServiceBus.DeserializeMessageConnector.Invoke(IIncomingPhysicalMessageContext context, Func`2 stage)
   at ReceivePerformanceDiagnosticsBehavior.Invoke(IIncomingPhysicalMessageContext context, Func`2 next)
   at NServiceBus.Transport.AzureServiceBus.TransactionScopeSuppressBehavior.Invoke(IIncomingPhysicalMessageContext context, Func`1 next)
   at NServiceBus.ProcessingStatisticsBehavior.Invoke(IIncomingPhysicalMessageContext context, Func`2 next)
   at NServiceBus.TransportReceiveToPhysicalMessageConnector.Invoke(ITransportReceiveContext context, Func`2 next)
   at NServiceBus.MainPipelineExecutor.Invoke(MessageContext messageContext)
   at NServiceBus.Transport.AzureServiceBus.MessagePump.InnerProcessMessage(Task`1 receiveTask)
```

 ```
   <PackageReference Include="NServiceBus" Version="7.2.0" />
    <PackageReference Include="NServiceBus.DataBus.AzureBlobStorage" Version="3.0.1" />
    <PackageReference Include="NServiceBus.Heartbeat" Version="3.0.1" />
    <PackageReference Include="NServiceBus.Metrics.ServiceControl" Version="3.0.4" />
    <PackageReference Include="NServiceBus.MicrosoftLogging" Version="1.3.1" />
    <PackageReference Include="NServiceBus.MSDependencyInjection" Version="0.1.4" />
    <PackageReference Include="NServiceBus.Newtonsoft.Json" Version="2.2.0" />
    <PackageReference Include="NServiceBus.Persistence.AzureStorage" Version="2.3.0" />
    <PackageReference Include="NServiceBus.Transport.AzureServiceBus" Version="1.4.0" />
```

`<TargetFramework>netcoreapp3.1</TargetFramework>`

**Comment by yvesgoeleven** [comment]
@JSCProjects What's the code on CommandHandler.cs:line 31?

**Comment by JSCProjects** [comment]
> @JSCProjects What's the code on CommandHandler.cs:line 31?
> 
> It seems that the exception originates at that specific line

OOps.
