### ISSUE TITLE
Assembly scanning broken in .NET5 when using SingleFile Deployments

### ISSUE THREAD

**Issue by Raagh** [Particular/NServiceBus#5935]
NServiceBus version: 7.4.4
.Net5

The following exception occurs when trying to run a console application (.Net5) that has been published using SingleFile Deployments. The exception is thrown at the Endpoint.Start() method:

```
EndpointConfiguration configuration = new EndpointConfiguration("MainProject");

configuration.UseTransport<LearningTransport>();
configuration.UsePersistence<LearningPersistence>();

IEndpointInstance endpoint = await NServiceBus.Endpoint.Start(configuration).ConfigureAwait(false);
```

Steps to reproduce:

Clone the [reproduction repository](https://github.com/Raagh/SingleFileNServiceBusNet5BugRepro)
Publish
Run

Error message:

```
Unhandled exception. System.ArgumentException: Empty path name is not legal. (Parameter 'path')
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at NServiceBus.AssemblyValidator.ValidateAssemblyFile(String assemblyPath, Boolean& shouldLoad, String& reason) in /_/src/NServiceBus.Core/Hosting/Helpers/AssemblyValidator.cs:line 82
   at NServiceBus.Hosting.Helpers.AssemblyScanner.TryLoadScannableAssembly(String assemblyPath, AssemblyScannerResults results, Assembly& assembly) in /_/src/NServiceBus.Core/Hosting/Helpers/AssemblyScanner.cs:line 175
   at NServiceBus.Hosting.Helpers.AssemblyScanner.GetScannableAssemblies() in /_/src/NServiceBus.Core/Hosting/Helpers/AssemblyScanner.cs:line 101
   at NServiceBus.AssemblyScanningComponent.Initialize(Configuration configuration, SettingsHolder settings) in /_/src/NServiceBus.Core/Hosting/Helpers/AssemblyScanningComponent.cs:line 41
   at NServiceBus.HostCreator.CreateWithInternallyManagedContainer(EndpointConfiguration endpointConfiguration) in /_/src/NServiceBus.Core/Hosting/HostCreator.cs:line 50
   at NServiceBus.Endpoint.Start(EndpointConfiguration configuration) in /_/src/NServiceBus.Core/Endpoint.cs:line 29
   at MainProject.Program.Main(String[] args) in C:\Users\Patricio\RiderProjects\NServiceBusReproRepo\MainProject\Program.cs:line 16
   at MainProject.Program.<Main>(String[] args)
```

...

The code works as expected if you debug it or publish it as a regular application.

**Comment by HEskandari** [comment]
@Raagh The SingleFile deployment requires the app not relying on some [APIs](https://docs.microsoft.com/en-us/dotnet/core/deploying/single-file#api-incompatibility). While this particular scenario is not using an unsupported API, it is assuming the file that is read via `File.OpenRead(path)` has a path on disk, but in this case the path seem to be empty.

There might be other cases (using different transport/persistence) where either an unsupported API is used, or there are assumptions like this as we never tested specifically for SingleFile deployments.

**Comment by bording** [comment]
@Raagh I've taken a quick look at your repro, and it turns out there is a pretty simple change we can make in the assembly scanner to make this work properly.

The reason it is failing is because of this line: https://github.com/Particular/NServiceBus/blob/master/src/NServiceBus.Core/Hosting/Helpers/AssemblyScanner.cs#L98

We need to change that to:

```csharp
if (!string.IsNullOrEmpty(platformAssembliesString))
```

**Comment by Raagh** [comment]
Hey @bording, thank you for taking the time to check the issue, I created a [pr](https://github.com/Particular/NServiceBus/pull/5954) based on your findings. Have a great day

**Comment by andreasohlund** [comment]
Fixed in https://github.com/Particular/NServiceBus/pull/5954
