### ISSUE TITLE
Critical error action is not invoked and endpoint is terminated when fetching timeouts fails

### ISSUE THREAD

**Issue by jjanuszkiewicz** [Particular/NServiceBus#6027]
We have an application using NServiceBus 7.1.10, with the following critical error action:

    busConfiguration.DefineCriticalErrorAction(async context => Environment.Exit(42));

Today we've faced the situation shown below - the timeouts storage failed and NSB endpoint got terminated, but the critical error action was not fired, so our application kept running in defunct state.

Is this a known bug/limitation/...?

    2021-04-20 02:33:56,868 [21] FATAL NServiceBus - Repeated failures when fetching timeouts from storage, endpoint will be terminated.
    NHibernate.TransactionException: Begin failed with SQL exception ---> System.Data.SqlClient.SqlException: A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server) ---> System.ComponentModel.Win32Exception: The network path was not found
       --- End of inner exception stack trace ---
       at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling, SqlAuthenticationProviderManager sqlAuthProviderManager)
       at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
       at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
       at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
       at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
       at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
       at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
       at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
       at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
       at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
       at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
       at System.Data.SqlClient.SqlConnection.Open()
       at NHibernate.Connection.DriverConnectionProvider.GetConnection()
       at NHibernate.AdoNet.ConnectionManager.GetConnection()
       at NHibernate.Transaction.AdoTransaction.Begin(IsolationLevel isolationLevel)
       --- End of inner exception stack trace ---
       at NHibernate.Transaction.AdoTransaction.Begin(IsolationLevel isolationLevel)
       at NHibernate.Impl.StatelessSessionImpl.BeginTransaction(IsolationLevel isolationLevel)
       at NServiceBus.TimeoutPersisters.NHibernate.TimeoutPersister.GetNextChunk(DateTime startSlice)
       at NServiceBus.ExpiredTimeoutsPoller.<SpinOnce>d__11.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at NServiceBus.ExpiredTimeoutsPoller.<InnerPoll>d__10.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at NServiceBus.ExpiredTimeoutsPoller.<Poll>d__9.MoveNext()

**Comment by danielmarbach** [comment]
@jjanuszkiewicz The timeout persister has a circuit breaker wired up and after two minutes it will actually trigger the critical error

https://github.com/Particular/NServiceBus/blob/6accaa7d8c001816ce4c71251a66d22f89d0079c/src/NServiceBus.Core/DelayedDelivery/TimeoutManager/TimeoutManager.cs#L52

which also prints the message you saw

> Repeated failures when fetching timeouts from storage, endpoint will be terminated

https://github.com/Particular/NServiceBus/blob/6accaa7d8c001816ce4c71251a66d22f89d0079c/src/NServiceBus.Core/DelayedDelivery/TimeoutManager/TimeoutManager.cs#L54

Where do you define the critical action in your code. Do you use some kind one of the [special configuration hooks](https://docs.particular.net/nservicebus/lifecycle/iwanttorunbeforeconfigurationisfinalized) provided by NServiceBus or do you do it directly where the endpoint configuration is defined?

**Comment by jjanuszkiewicz** [comment]
@danielmarbach we define it like this:

    var configuration = new EndpointConfiguration(_componentNameProvider.EndpointName);
    // ... all the normal transport, persistence, recoverability etc configuration
    configuration.DefineCriticalErrorAction(async context => Environment.Exit(42));

and start it immediately:

    var endpoint = await Endpoint.Start(configuration).ConfigureAwait(false);

**Comment by danielmarbach** [comment]
Hmmm. Yeah, there is nothing suspicious in that code. I've been going through the minor changes and couldn't immediately find something that would indicate a bug. Would it be an option for you to upgrade to 7.4.x to see if that resolves it? Or do you have a way to somehow reproduce it in a minimalistic sample?

Meanwhile I will check with some of my colleagues and further investigate

**Comment by jjanuszkiewicz** [comment]
I'll try to get a repro and an upgrade to 7.4 a go, I'll let you know when I have it (probably not today/tomorrow).

**Comment by WilliamBZA** [comment]
I've tried to reproduce this too and couldn't get it working. I'm going to close this but if you see this happening again, please reopen and let us know - preferably with some repro steps so that we can try and identify what's happening.
