### ISSUE TITLE
DiagnosticsFeature throws NotImplementedException in v8 alpha

### ISSUE THREAD

**Issue by buvinghausen** [Particular/NServiceBus#6090]
The following line clears up the error
```cs
endpointConfiguration.DisableFeature<DiagnosticsFeature>();
```

System.NotImplementedException
  HResult=0x80004001
  Message=The method or operation is not implemented.
  Source=NServiceBus.Core
  StackTrace:
   at NServiceBus.Settings.SettingsHolder.SetDefault[T](Object value) in /_/src/NServiceBus.Core/obsoletes-v8.cs:line 339
   at NServiceBus.Extensions.Diagnostics.DiagnosticsFeature.<>c.<.ctor>b__0_0(SettingsHolder settings)
   at NServiceBus.Features.Feature.ConfigureDefaults(SettingsHolder settings) in /_/src/NServiceBus.Core/Features/Feature.cs:line 211
   at NServiceBus.Features.FeatureActivator.SetupFeatures(FeatureConfigurationContext featureConfigurationContext) in /_/src/NServiceBus.Core/Features/FeatureActivator.cs:line 57
   at NServiceBus.FeatureComponent.Initalize(FeatureConfigurationContext featureConfigurationContext) in /_/src/NServiceBus.Core/Features/FeatureComponent.cs:line 29
   at NServiceBus.EndpointCreator.Configure() in /_/src/NServiceBus.Core/EndpointCreator.cs:line 63
   at NServiceBus.EndpointCreator.Create(SettingsHolder settings, Configuration hostingConfiguration) in /_/src/NServiceBus.Core/EndpointCreator.cs:line 28
   at NServiceBus.HostCreator.CreateWithExternallyManagedContainer(EndpointConfiguration endpointConfiguration, IServiceCollection serviceCollection) in /_/src/NServiceBus.Core/Hosting/HostCreator.cs:line 30
   at NServiceBus.EndpointWithExternallyManagedContainer.Create(EndpointConfiguration configuration, IServiceCollection serviceCollection) in /_/src/NServiceBus.Core/EndpointWithExternallyManagedContainer.cs:line 18
   at Assurely.Hosting.Common.NServiceBus.NServiceBusExtensions.<>c__DisplayClass1_0.<UseNServiceBus>b__5(CancellationToken cancellationToken) in C:\Users\Administrator\Documents\GitHub\Assurely\Hosting\src\Common\NServiceBus\NServiceBusExtensions.cs:line 130

**Comment by SzymonPobiega** [comment]
I guess you picked one of the not really working pre-release packages. We release them frequently internally when developing various features and some of them have only limited set of features working. I'll ping my colleagues to let them know.

**Comment by adamralph** [comment]
@buvinghausen as @SzymonPobiega says, the current pre-release packages which reference NServiceBus 8.x are not yet ready for consumption and are not all aligned with each other with respect to package reference versions. That is why we have only pushed specific packages to myget (for internal testing), rather than nuget.org.

To avoid these issues, it's best to only consume packages which we publish to nuget.org. If you find issues with the packages that are published to nuget.org, please feel free to raise them here.

**Comment by buvinghausen** [comment]
@SzymonPobiega & @adamralph I'm fully aware I shouldn't be using these packages day to day but I saw the [7 to 8 upgrade guide](https://docs.particular.net/nservicebus/upgrades/7to8/) and decided to make sure my generic multi-host with DryIoc configuration would still work in the new world order with the wholesale obsolescence of the [NServiceBus.Extensions.DependencyInjection](https://github.com/Particular/NServiceBus.Extensions.DependencyInjection) package which I use heavily.  The good news is I moved from using the [UseContainer](https://github.com/Particular/NServiceBus.Extensions.DependencyInjection/blob/release-1.0/src/NServiceBus.Extensions.DependencyInjection/ContainerExtensions.cs#L18) and [ConfigureContainer](https://github.com/Particular/NServiceBus.Extensions.DependencyInjection/blob/release-1.0/src/NServiceBus.Extensions.DependencyInjection/ContainerSettings.cs#L20) functions and now use the [EndpointWithExternallyManagedServiceProvider](https://github.com/Particular/NServiceBus.Extensions.DependencyInjection/blob/release-1.0/src/NServiceBus.Extensions.DependencyInjection/EndpointWithExternallyManagedServiceProvider.cs#L9) class directly which lends itself to an easy swap over to [EndpointWithExternallyManagedContainer](https://github.com/Particular/NServiceBus/blob/master/src/NServiceBus.Core/EndpointWithExternallyManagedContainer.cs#L8) class once v8 drops so it was a win for me.

These two issues were just things I ran aground on while trying to get the stack to even boot so I figured I would simply raise awareness.

**Comment by adamralph** [comment]
👍 thanks @buvinghausen — we appreciate the heads up, and I guess having that upgrade already showing in our docs may make it tempting to try out the alpha packages now. 🙂

Perhaps I overreached a little in my previous comment: there could be things which are genuinely broken in the alphas, and I guess we _would_ like to hear about those things early if possible, so if in doubt, please do raise issues. 👍

In both this case, and https://github.com/Particular/NServiceBus.Storage.MongoDB/issues/198, the problems are almost certainly caused by misalignment of package versions, and that _will_ be fixed before the packages go to nuget.org.
