### ISSUE TITLE
Could not enumerate all types for 'NServiceBus.Persistence.CosmosDB'

### ISSUE THREAD

**Issue by kylejuliandev** [Particular/NServiceBus#6226]
Hi,

I recently began to experiment with upgrading my applications to .NET 6.0 following the [announcement](https://discuss.particular.net/t/nservicebus-support-for-net-6-complete/2902) for support. Below is a list of packages we use from Particular, with before and after versions.

  |Package Name|Old Version|New Version|
|---------------|-------------|-----------|
|NServiceBus|7.4.7|7.6.0|
|NServiceBus.Callbacks|3.0.0|3.0.0|
|NServiceBus.Extensions.Hosting|1.1.0|1.1.0|
|NServiceBus.Heartbeat|3.0.1|3.0.1|
|NServiceBus.Metrics.ServiceControl|3.0.6|3.0.6|
|NServiceBus.Newtonsoft.Json|2.3.0|2.3.0|
|NServiceBus.Persistence.AzureStorage|2.4.2|2.4.2|
|NServiceBus.Persistence.CosmosDB|0.2.1|1.0.0|
|NServiceBus.SagaAudit|3.0.1|3.0.1|
|NServiceBus.Serilog|7.15.0|7.16.0|
|NServiceBus.Transport.AzureServiceBus|1.9.0|2.0.2|

So only changes to `NServiceBus`, `NServiceBus.Persistence.CosmosDB`, `NServiceBus.Serilog`, and `NServiceBus.Transport.AzureServiceBus`

Upon upgrading one of my applications it began to fail to start up. The application uses the CosmosDB Persistence provider for its Saga storage needs. This application now targets `net6.0` and the above NServiceBus packages. I will add, no code changes were necessary for the upgrade process. Everything was compiled and built.

Below is the exception message and stack trace.

<details>
  <summary>Exception Message</summary>
  
```
Could not enumerate all types for 'NServiceBus.Persistence.CosmosDB, Version=1.0.0.0, Culture=neutral, PublicKeyToken=9fc386479f8a226c'.
	Exceptions:
	System.TypeLoadException: Method 'PatchItem' in type 'NServiceBus.Persistence.CosmosDB.SharedTransactionalBatch' from assembly 'NServiceBus.Persistence.CosmosDB, Version=1.0.0.0, Culture=neutral, PublicKeyToken=9fc386479f8a226c' does not have an implementation.
```
</details>

<details>
    <summary>Exception Stacktrace</summary>

```
at NServiceBus.Hosting.Helpers.AssemblyScanner.AddTypesToResult(Assembly assembly, AssemblyScannerResults results) in /_/src/NServiceBus.Core/Hosting/Helpers/AssemblyScanner.cs:line 387
at NServiceBus.Hosting.Helpers.AssemblyScanner.GetScannableAssemblies() in /_/src/NServiceBus.Core/Hosting/Helpers/AssemblyScanner.cs:line 79
at NServiceBus.AssemblyScanningComponent.Initialize(Configuration configuration, SettingsHolder settings) in /_/src/NServiceBus.Core/Hosting/Helpers/AssemblyScanningComponent.cs:line 41
at NServiceBus.HostCreator.CreateWithExternallyManagedContainer(EndpointConfiguration endpointConfiguration, IConfigureComponents externalContainer) in /_/src/NServiceBus.Core/Hosting/HostCreator.cs:line 16
at NServiceBus.EndpointWithExternallyManagedContainer.Create(EndpointConfiguration configuration, IConfigureComponents configureComponents) in /_/src/NServiceBus.Core/EndpointWithExternallyManagedContainer.cs:line 20
at NServiceBus.HostBuilderExtensions.<>c__DisplayClass0_0.<UseNServiceBus>b__0(HostBuilderContext ctx, IServiceCollection serviceCollection) in /_/src/NServiceBus.Extensions.Hosting/HostBuilderExtensions.cs:line 34
at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
at Microsoft.Extensions.Hosting.HostBuilder.Build()
at myapp.WorkerService.Program.Main(String[] args) in C:\repos\myapp-service\myapp-messaging\src\myapp.WorkerService\Program.cs:line 31
```
</details>

Please let me know if you need any more details

Kind Regards,

**Comment by kylejuliandev** [comment]
I can work around it by explicitly excluding the `NServiceBus.Persistence.CosmosDB.dll` assembly from the scanning process. Although, I did not have to do this before the upgrade/migration.

**Comment by kylejuliandev** [comment]
Moved to NServiceBus.Persistence.CosmosDB
