### ISSUE TITLE
Bug: Unhandled exception. System.NotImplementedException

### ISSUE THREAD

**Issue by KenBonny** [Particular/NServiceBus#6628]
# Expected behavior

The api/worker to start up normally.

# What happens

During startup, my applications (send only api, worker that processes messages) crash with the following error:

```
Unhandled exception. System.NotImplementedException: The method or operation is not implemented.
   at NServiceBus.Settings.SettingsHolder.SetDefault[T](Object value) in /_/src/NServiceBus.Core/obsoletes-v8.cs:line 341
   at NServiceBus.Extensions.Diagnostics.DiagnosticsFeature.<>c.<.ctor>b__0_0(SettingsHolder settings)
   at NServiceBus.Features.Feature.ConfigureDefaults(SettingsHolder settings) in /_/src/NServiceBus.Core/Features/Feature.cs:line 211
   at NServiceBus.Features.FeatureActivator.SetupFeatures(FeatureConfigurationContext featureConfigurationContext) in /_/src/NServiceBus.Core/Features/FeatureActivator.cs:line 38
   at NServiceBus.FeatureComponent.Initalize(FeatureConfigurationContext featureConfigurationContext) in /_/src/NServiceBus.Core/Features/FeatureComponent.cs:line 29
   at NServiceBus.EndpointCreator.Configure() in /_/src/NServiceBus.Core/EndpointCreator.cs:line 61
   at NServiceBus.EndpointCreator.Create(SettingsHolder settings, Configuration hostingConfiguration) in /_/src/NServiceBus.Core/EndpointCreator.cs:line 26
   at NServiceBus.HostCreator.CreateWithExternallyManagedContainer(EndpointConfiguration endpointConfiguration, IServiceCollection serviceCollection) in /_/src/NServiceBus.Core/Hosting/HostCreator.cs:line 30
   at NServiceBus.EndpointWithExternallyManagedContainer.Create(EndpointConfiguration configuration, IServiceCollection serviceCollection) in /_/src/NServiceBus.Core/EndpointWithExternallyManagedContainer.cs:line 18
   at NServiceBus.HostBuilderExtensions.<>c__DisplayClass0_0.<UseNServiceBus>b__0(HostBuilderContext ctx, IServiceCollection serviceCollection) in /_/src/NServiceBus.Extensions.Hosting/HostBuilderExtensions.cs:line 34
   at Microsoft.AspNetCore.Builder.ConfigureHostBuilder.ConfigureServices(Action`2 configureDelegate)
```

# API setup

```csharp
var endpointConfiguration = new EndpointConfiguration(NServiceBusEndpointName);
endpointConfiguration.EnableInstallers();
endpointConfiguration.UseSerialization<NewtonsoftJsonSerializer>();
endpointConfiguration.LicensePath(context.Configuration.GetValue<string>("NServiceBus:LicensePath"));
endpointConfiguration.EnableOpenTelemetry();
endpointConfiguration.SendOnly();
endpointConfiguration.DisableFeature<DiagnosticsFeature>();

TransportDefinition transport = context.HostingEnvironment.IsDevelopment()
            ? new RabbitMQTransport(
                RoutingTopology.Conventional(QueueType.Classic),
                context.Configuration.GetValue<string>("NServiceBus:ConnectionString"))
            : new AzureServiceBusTransport(context.Configuration.GetValue<string>("NServiceBus:ConnectionString"));
var routing = endpointConfiguration.UseTransport(transport);

const string workerEndpoint = "Worker";
routing.RouteToEndpoint(typeof(TestMessage).Assembly, workerEndpoint);

var tracing = endpointConfiguration.EnableSerilogTracing();
tracing.EnableMessageTracing();
tracing.EnableSagaTracing();

return endpointConfiguration;
```

# Worker setup

```csharp
var endpointConfiguration = new EndpointConfiguration(NServiceBusEndpointName);
endpointConfiguration.EnableInstallers();
endpointConfiguration.UseSerialization<NewtonsoftJsonSerializer>();
endpointConfiguration.LicensePath(context.Configuration.GetValue<string>("NServiceBus:LicensePath"));
endpointConfiguration.SendFailedMessagesTo("error");
endpointConfiguration.AuditProcessedMessagesTo("audit");
endpointConfiguration.EnableOutbox();
endpointConfiguration.EnableOpenTelemetry();
endpointConfiguration.DisableFeature<DiagnosticsFeature>();

TransportDefinition transport = context.HostingEnvironment.IsDevelopment()
        ? new RabbitMQTransport(
            RoutingTopology.Conventional(QueueType.Classic),
            context.Configuration.GetValue<string>("NServiceBus:ConnectionString"))
        : new AzureServiceBusTransport(context.Configuration.GetValue<string>("NServiceBus:ConnectionString"));
var routing = endpointConfiguration.UseTransport(transport);
routing.RouteToEndpoint(typeof(TestMessage).Assembly, NServiceBusEndpointName);

var persistence = endpointConfiguration.UsePersistence<SqlPersistence>();
persistence.TablePrefix(NServiceBusEndpointName.Replace(".", string.Empty));
persistence.SqlDialect<SqlDialect.MsSqlServer>().Schema("nsb");
persistence.ConnectionBuilder(() => new SqlConnection(context.Configuration.GetConnectionString("ConnectionString")));

var r = endpointConfiguration.Recoverability();
var o = new DbContextOptionsBuilder<EtiketteringDbContext>()
        .UseSqlServer(context.Configuration.GetConnectionString("ConnectionString"))
        .Options;

r.CustomPolicy(
        (recoveryConfig, errorContext) =>
            CustomRecoverabilityPolicy.ExponentialBackoff(recoveryConfig, errorContext, () => new DbContext(o)));

var tracing = endpointConfiguration.EnableSerilogTracing();
tracing.EnableMessageTracing();
tracing.EnableSagaTracing();

return endpointConfiguration;
```

# Workaround

By disabling the `DiagnosticsFeature`, the error goes away: `endpointConfiguration.DisableFeature<DiagnosticsFeature>();`

# Installed packages

At the time of writing, these are the latest package versions.

- NServiceBus 8.0.1
- NServiceBus.Extensions.Diagnostics 2.1.1
- NServiceBus.Extensions.Diagnostics.OpenTelemetry 2.0.0
- NServiceBus.Extensions.Hosting 2.0.0
- NServiceBus.Metrics 4.0.0
- NServiceBus.Newtonsoft.Json 3.0.0
- NServiceBus.Persistence.Sql 7.0.0
- NServiceBus.RabbitMQ 8.0.0
- NServiceBus.Serilog 9.0.1
- NServiceBus.Testing 8.0.0
- NServiceBus.Transport.AzureServiceBus 3.1.1

**Comment by danielmarbach** [comment]
@KenBonny Thanks for raising such a detailed issue. It looks like @jbogard extension `NServiceBus.Extensions.Diagnostics` is still using an obsoleted method

In fact the extension itself is archived and [tied to NServiceBus v7](https://github.com/jbogard/NServiceBus.Extensions.Diagnostics/blob/master/src/NServiceBus.Extensions.Diagnostics/NServiceBus.Extensions.Diagnostics.csproj#L26). What did you do to make that work? Did you recompile your own version of the extension?

**Comment by jbogard** [comment]
Yep, that extension has no reason to live (🎊) on V8, it should only be used on 7.

**Comment by KenBonny** [comment]
🤦 

I don't need @jbogard extension anymore since OpenTelemetry is now natively supported. With that package removed, it works perfectly.

Sorry to trouble you guys with that.

**Comment by danielmarbach** [comment]
No worries. We are here to help.
