### ISSUE TITLE
Registering IAsyncDisposable implementations throws an InvalidOperationException

### ISSUE THREAD

**Issue by danielmarbach** [Particular/NServiceBus#6659]
## Who's affected

User's trying to register `IAsyncDisposable` registrations

## Symptoms

When registering scoped async disposables and resolving them as part of the pipeline the messages associated with that handler go through a series of retries and are eventually moved to the error queue.

```text
2022-12-23 11:04:23.388 ERROR Moving message '1243a077-6606-4fc7-ae43-af7400a56572' to the error queue 'error' because processing failed due to an exception:
System.InvalidOperationException: 'AsyncDisposable' type only implements IAsyncDisposable. Use DisposeAsync to dispose the container.
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.Dispose()
   at NServiceBus.MainPipelineExecutor.Invoke(MessageContext messageContext, CancellationToken cancellationToken) in /_/src/NServiceBus.Core/Pipeline/MainPipelineExecutor.cs:line 63
   at NServiceBus.LearningTransportMessagePump.ProcessFile(ILearningTransportTransaction transaction, String messageId, CancellationToken messageProcessingCancellationToken) in /_/src/NServiceBus.Core/Transports/Learning/LearningTransportMessagePump.cs:line 340
```

The problem is relatively simple to reproduce by for example taking the full duplex sample, adding 

```csharp
public class AsyncDisposable : IAsyncDisposable
{
    public ValueTask DisposeAsync()
    {
        return new ValueTask();
    }
}
```

and changing the handler constructor to

```csharp
    private readonly AsyncDisposable _asyncDisposable;

    public RequestDataMessageHandler(AsyncDisposable asyncDisposable)
    {
        _asyncDisposable = asyncDisposable;
    }
```

and registering the async disposable

```csharp
        endpointConfiguration.RegisterComponents(c =>
        {
            c.AddScoped<AsyncDisposable>();
        });
```

This will then move all messages associated with that handler into the error queue. 

The problem of **scoped async disposables** not being disposed applies both for the **internal and the external managed mode.**

The issue does not only apply to scoped async disposables but also singleton async disposables. When a singleton async disposable is registered, the disposable never gets disposed when the endpoint is stopped, effectively creating a resource leak.

The issue for singletons applies only to the **internal managed mode**, since users are responsible to properly dispose the externally managed container. 

## Backport

- [Master](https://github.com/Particular/NServiceBus/pull/6650)
- [8.0.3](https://github.com/Particular/NServiceBus/pull/6658)

**Comment by danielmarbach** [comment]
Will be released with 8.0.3
