### ISSUE TITLE
Collection was modified in SetExceptionMetadata

### ISSUE THREAD

**Issue by SimonCropp** [Particular/NServiceBus#6661]
Not sure if this one should be in the sql transport or core

we got this in prod. dont know how to replicate yet

```
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.

   at System.Collections.ListDictionaryInternal.NodeEnumerator.MoveNext()

   at NServiceBus.FaultMetadataExtractor.SetExceptionMetadata(Dictionary`2 headers, Exception e) in /_/src/NServiceBus.Core/Recoverability/FaultMetadataExtractor.cs:line 50

   at NServiceBus.FaultMetadataExtractor.Extract(ErrorContext errorContext) in /_/src/NServiceBus.Core/Recoverability/FaultMetadataExtractor.cs:line 24

   at NServiceBus.RecoverabilityPipelineExecutor`1.Invoke(ErrorContext errorContext, CancellationToken cancellationToken) in /_/src/NServiceBus.Core/Recoverability/RecoverabilityPipelineExecutor.cs:line 41

   at NServiceBus.Transport.SqlServer.ProcessStrategy.HandleError(Exception exception, Message message, TransportTransaction transportTransaction, Int32 processingAttempts, ContextBag context, CancellationToken cancellationToken) in /_/src/NServiceBus.Transport.SqlServer/Receiving/ProcessStrategy.cs:line 63
```

the code in question is

```
 static void SetExceptionMetadata(Dictionary<string, string> headers, Exception e)
        {
            headers["NServiceBus.ExceptionInfo.ExceptionType"] = e.GetType().FullName;

            if (e.InnerException != null)
            {
                headers["NServiceBus.ExceptionInfo.InnerExceptionType"] = e.InnerException.GetType().FullName;
            }

            headers["NServiceBus.ExceptionInfo.HelpLink"] = e.HelpLink;
            headers["NServiceBus.ExceptionInfo.Message"] = Truncate(e.GetMessage(), 16384);
            headers["NServiceBus.ExceptionInfo.Source"] = e.Source;
            headers["NServiceBus.ExceptionInfo.StackTrace"] = e.ToString();
            headers["NServiceBus.TimeOfFailure"] = DateTimeOffsetHelper.ToWireFormattedString(DateTimeOffset.UtcNow);

            if (e.Data == null)
            {
                return;
            }
            foreach (DictionaryEntry entry in e.Data)
            {
                if (entry.Value == null)
                {
                    continue;
                }
                headers["NServiceBus.ExceptionInfo.Data." + entry.Key] = entry.Value.ToString();
            }
        }
```

with the exception on `foreach (DictionaryEntry entry in e.Data)`.

**Comment by SimonCropp** [comment]
any ideas ?

**Comment by SimonCropp** [comment]
could it be that notifications does a whenall.
```
        Task INotificationSubscriptions<TEvent>.Raise(TEvent @event, CancellationToken cancellationToken) =>
            Task.WhenAll(subscriptions.Select(s => s.Invoke(@event, cancellationToken)));
```

and OnMessageSentToErrorQueue goes through that path (i think?) so multiple things can be manipulating the data on different threads?

**Comment by timbussmann** [comment]
what version are you using in prod?

> could it be that notifications does a whenall.

Yes `OnMessageSentToErrorQueue` goes through that path, so the event callbacks could be potentially executed concurrently and operate on the same exception instance which could cause such a problem. However, the code of the `FaultMetadataExtractor` should be executed quite a bit before the notifications are raised, so there should be no way how the notifications could influence the `FaultMetadataExtractor` logic.

**Comment by timbussmann** [comment]
How often are you observing this error?

Do you use other packages that might work with the exception in an async way, e.g. OpenTelemetry, logging, or something like that?

**Comment by SimonCropp** [comment]
> How often are you observing this error?

rarely. 20 times in the past month

> work with the exception in an async way, 

not in an async way.

but https://github.com/NServiceBusExtensions/NServiceBus.Serilog uses the data as a bucket to map data between 

writing:

https://github.com/NServiceBusExtensions/NServiceBus.Serilog/blob/main/src/NServiceBus.Serilog/LogInjection/InjectIncomingPhysicalBehavior.cs#L84

reading and removal: 

https://github.com/NServiceBusExtensions/NServiceBus.Serilog/blob/main/src/NServiceBus.Serilog/ExceptionEnricher.cs#L47

but i cant see how that would be happening on a different thread

**Comment by timbussmann** [comment]
I can definitely imagine that the collection modification in the `ExceptionEnricher` might be related. However I've been unable to isolate/reproduce the issue using Serilog and enrichers, it seems like the enrichers are always called synchronously when logging, therefore, as long as there is nothing that tries to log the exception in parallel/concurrently, this shouldn't cause the error. Are there special configurations or sinks that might change this behavior?

Would there be a way to remove the `data.Remove(key);` part from `TryReadData` to see if that really is the issue causing the problem?

It seems there might be some approaches to make the code more resilient by either:
- copying the `Exception.Data` collection before iterating it
- wrapping the iteration in a try/catch

copying the collection seems to be a fairly expensive way of preventing this from happening and I kinda dislike this without fully understanding in what circumstances we can run into such an issue.
